### ISSUE TITLE
"Get code" for CPT with 'show in menu' set to second-level page not outputting correctly

### ISSUE THREAD

**Issue by FriendlyWP** [WebDevStudios/custom-post-type-ui#132]
Get Code outputs 

'show_in_menu' => true,

whenever the second field (cpt_custom_post_type[show_in_menu_string]) is filled in / set to a top-level admin page like tools.php. The contents of that field are ignored.

This happens whether or not the dropdown True/False for 'show in menu' is set to either True or False, as long as the second field is filled in. 

Using v. 0.8.2 in WP 3.8.

**Comment by tw2113** [comment]
@FriendlyWP could you confirm whether this is still happening in the dev branch here on GitHub?

**Comment by tw2113** [comment]
Disregard, I double checked and saw that it for sure was not. Fixed in dev branch now.
