### ISSUE TITLE
'hierarchical' => true for taxonomies rewrite

### ISSUE THREAD

**Issue by jonathan-dejong** [WebDevStudios/custom-post-type-ui#138]
Don't think I've found any issue like this currently open..

We've encountered a project where the permalinks for hierarchical terms need to display in hierarchy.. such as site.com/parentterm/childterm/ instead of site.com/childterm 

I've found this answer which describes how to achieve this: http://wordpress.stackexchange.com/a/17329

It'd be nice to see it as a feature.. I might give it a shot myself and send a pull request but honestly I'm so damn swamped with stuff already (which you guys probably are as well).. =/

**Comment by tw2113** [comment]
Not the only commit related to this, but at least the commit that adds the inputs: 735eae0fbe946f0c00c1fbfd816ae2f80a31de5e

It'll be in 0.9. Closing this issue.
