### ISSUE TITLE
Enhancement request: allow use of Dashicons for CPT icons, for WP 3.8 and up

### ISSUE THREAD

**Issue by mrmukaoy** [WebDevStudios/custom-post-type-ui#140]
Current status allows only for use of an image for CPT icon. Would like to use the new dashicons font instead.
http://melchoyce.github.io/dashicons/

**Comment by tw2113** [comment]
Should be in 0.9.0. Double check the dev branch if you can @mrmukaoy and let me know if it's working as expected. I'd appreciate confirmation. If it's not working, I'll reopen the issue.
