### ISSUE TITLE
Wrong Label 

### ISSUE THREAD

**Issue by wannesdebacker** [WebDevStudios/custom-post-type-ui#149]
The example value in the Advanced Label Options after View should be "View" instead of "View Item". The next field allready says "View Item"

![screenshot](https://f.cloud.github.com/assets/2697192/1954484/455abe26-81d8-11e3-979d-936778d0e80c.jpg)

**Comment by tw2113** [comment]
Fixed in the dev branch, which will be 0.9.0.
