### ISSUE TITLE
Apostrophes in type description breaks exported code

### ISSUE THREAD

**Issue by mortona42** [WebDevStudios/custom-post-type-ui#155]
```php
add_action('init', 'cptui_register_my_cpt_story');
function cptui_register_my_cpt_story() {
  register_post_type('story', array(
    'label' => 'Stories',
    'description' => 'Examples of my company's work.',
```

I suggest either always using double quotes, or else checking for values that require them.

**Comment by tw2113** [comment]
@mortona42 can you download the dev branch here and confirm that this is fixed the way you expect?

**Comment by tw2113** [comment]
Gonna mark closed for now. Can re-open if not fixed.
