### ISSUE TITLE
Make a check for array values unserialized

### ISSUE THREAD

**Issue by Demak** [WebDevStudios/custom-post-type-ui#156]
Under some server configurations core wordpress functions such as get_option() and $wpdb->get_results do not sometimes unsearialize arrays which are stored in database. This can result post types or taxonomies not being registered or displayed. To counter this, array values received from database should be tested for array type and for serialized string if array check fails.

example code:
$cpt_post_types = get_option('cpt_custom_post_types');
if(!is_array($cpt_post_types)){
	$test_serialize=unserialize($cpt_post_types);
	if($test_serialize){
		$cpt_post_types=$test_serialize;
	}else{
		return false;
	}
}

**Comment by tw2113** [comment]
Closing as is_array() checks are in place before we attempt to register any.
