### ISSUE TITLE
YARPP support

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#162]
Preferably just a hook that users can grab onto and input the necessary parts.

http://wordpress.org/support/topic/yarpp-support-true?replies=5#post-5534811

**Comment by tw2113** [comment]
@johndugan Do you know where in the register_post_type process this needs to be added? The "supports" array? part of the `$args` array?

**Comment by sc0ttkclark** [comment]
Yep, I learned the hard way.

```php
if ( defined( 'YARPP_VERSION' ) ) {
    $cpt_args[ 'yarpp_support' ] = true;
}
```

It's a root level option, it's not in 'supports' array (sad face)

**Comment by tw2113** [comment]
Sounds like it'd be better off for a filter on the root level then. It may come in 0.9.0, may be held off until 1.0.0 though. We'll see. I want to get the next one out the door soonish.

**Comment by tw2113** [comment]
Realized it'd be easy enough with one last filter before the registration. See 6122ad7

**Comment by johndugan** [comment]
@tw2113 sorry for the delayed response... Thanks @sc0ttkclark for stepping in :-)

**Comment by tw2113** [comment]
No worries. Feel like testing out version 0.9.0? Grab a copy of the dev branch!
