### ISSUE TITLE
custom post type - rewrite option doesn't work

### ISSUE THREAD

**Issue by Pravdomil** [WebDevStudios/custom-post-type-ui#163]
try to turn off rewrite and you still get rewrite => array("slug" => $something)
it should be set to false

http://pastebin.com/BwVVWRrZ

**Comment by tw2113** [comment]
@Pravdomil could you download the dev branch copy and confirm that this is fixed in what will be the 0.9.0 version?

**Comment by Pravdomil** [comment]
Well I already created my own cpt & tax manager
https://wordpress.org/plugins/custom-post-types-and-taxonomies-manager/
