### ISSUE TITLE
Taxonomy admin does not output utf8 characters

### ISSUE THREAD

**Issue by wycks** [WebDevStudios/custom-post-type-ui#172]
As seen in screenshot the accented character is missing in the UI.

![cpt-ui](https://cloud.githubusercontent.com/assets/875757/3742010/f3bee90c-1764-11e4-8eb3-8949aa8ce3c1.jpg)

**Comment by tw2113** [comment]
out of curiosity, how would i go about making sure those don't disappear?

**Comment by wycks** [comment]
I didn't look at this plugins code, by default this should work out of the box since accented characters are still valid UTF-8,  it's likely there is code which is stripping out the character, or perhaps a server related encoding issue ( so duplicating this problem is probably a a good idea).

I would check the database entry and see if the accented characters are stored, or how they are stored (HTML entity or just raw), that way you will know if they are being stripped on input or output.

**Comment by tw2113** [comment]
If it's a server encoding issue, then my localhost has that happening. As an alternative, I'm thinking about using remove_accents() on the slugs before registration, and possible for the slug field for the plugin's screens. Not sure if it's going to cause any immediate trouble. Would appreciate some thoughts on it, if you have a moment.

**Comment by wycks** [comment]
Yes I think `remove_accents()` would be acceptable solution. I know there are more difficult languages (such as swedish) which converts double letters in single (like æ). I also see that some browsers will now render a slug (urls) with accented characters in it.

I always use this function for slugs as best practise though, since having weird characters in a slug does cause issues with other php/WordPress functions, JavaScript and even css.

As long as the new function does touch any existing user settings (what if someone re-saves their ctp, or re-activates the plugin, etc)  I think it would be pretty safe.

**Comment by tw2113** [comment]
My initial plans were to use it right before passing in the tax/type slugs into their respective register_* functions, as well as probably on display in the UI field for them. Kind of iffy on that last part, but I'm not sure which way would be more confusing.

The existing settings may prove a bump in the road though, because there'd suddenly be new characters in the slugs instead of removed ones like original. I also just heard from Nacin that both remove_accents() and sanitize_title() are slow and deliberately not used on runtime.

May have to leave this one as is, in order to not disrupt. A note about accents and special characters may go further.

**Comment by wycks** [comment]
I don't really get why, you're not running those functions every load , you simply run them once if the user enters a non valid character and string the non-accented slug in the database.

At least that way they can read the word.

**Comment by tw2113** [comment]
Well, it's a case of stuck between a rock and a hard place. If the post type or taxonomy are already created in CPTUI, and they go edit it, if I suddenly have this new function running, it alters what they've already registered and created with, and the associations will be off.

I can't think of any sane way to do it for just new users or new types/taxes, and I'm not keen on trying to alter all entries in the db to match the new version.

As much as it sucks, i'd rather not break a lot of existing content :)

**Comment by wycks** [comment]
ya agreed, maintainability is hard.
