### ISSUE TITLE
Get Code feature needs to sanitize the slug to be used in the function name

### ISSUE THREAD

**Issue by circlecube** [WebDevStudios/custom-post-type-ui#177]
`
add_action('init', 'cptui_register_my_taxes_machine-type');
function cptui_register_my_taxes_machine-type() {
`
should be something like
`
add_action('init', 'cptui_register_my_taxes_machine_type');
function cptui_register_my_taxes_machine_type() {
`

**Comment by tw2113** [comment]
Closing with that said :)
