### ISSUE TITLE
"Supports" list to include JetPack's Publicize feature

### ISSUE THREAD

**Issue by DougJoseph** [WebDevStudios/custom-post-type-ui#185]
Thanks for such a GREAT PLUGIN!!!

Since this was announced:

http://jetpack.me/2014/01/31/jetpack-2-8-introducing-markdown-and-improving-monitor/

"Publicize now offers Support for Custom Post Types.... allowing to automatically post new entries from any CPT to social media networks. You’d need to make one small tweak in the code defining the CPT—just add 'publicize' to the CPT’s 'supports' array.

"For example, to enable the title, editor, Publicize, and Jetpack’s new support for Markdown: 'supports' => array( 'title', 'editor', 'publicize', 'wpcom-markdown' ),"

... Is there any chance a tweak could be made so that CPT advanced settings includes "Publicize" under the "Supports" section of checkboxes? That would be so awesome.

**Comment by tw2113** [comment]
@DougJoseph Gonna be doing it via filter. 8be1584308 and 98f81a9ff4a2

Prevents having to save it in the option we create, but still gets it added both before registration, as well as on export with the get_code if you're leaving the plugin :)

Closing as it's been added.

**Comment by DougJoseph** [comment]
Wow! Sounds great. Thank you!
