### ISSUE TITLE
I cant manage my post types (screenshot)

### ISSUE THREAD

**Issue by SAASquatchy** [WebDevStudios/custom-post-type-ui#196]
![image](https://cloud.githubusercontent.com/assets/2753439/5709424/09cb1f8e-9a57-11e4-8d59-f7dd9f54828c.png)

When I click on manage post types it lists them but there are no links to be able to change or delete them.

**Comment by tw2113** [comment]
From the looks of the empty list, none of the available ones that would be editable are from CPTUI. Note that we don't tap into 3rd party post types and allow them to be editable by our plugin. We just handle ones created ourselves.

**Comment by tw2113** [comment]
Closing because this screen will be gone in 0.9.0
