### ISSUE TITLE
Metabox taxonomy support

### ISSUE THREAD

**Issue by Hube2** [WebDevStudios/custom-post-type-ui#201]
Not sure if you might already have plans for this, but it would be a nice feature to add. The ability to set what type of metabox widget is show a taxonomy, independent of it being hierarchical or not. For example, a hierarchical taxonomy gets the "Category" widget and non hierarchical taxonomies get the "Tag" widget. It is possible to set which of these will appear. It is also possible to make them so that new items cannot be added to them (Ala Post Formats). All this can be done with standard WP filters.

Not in a huge hurry for it, but I know it would make my life a bit easier.

Thanks for reading this,

~JH

**Comment by tw2113** [comment]
@Hube2 can you point me to any sort of examples for this type of thing? I'm not quite sure what to google for myself so I can figure out if I can integrate it.

**Comment by Hube2** [comment]
You can alter if a taxonomy uses the category or tag meta box by setting the 'meta_box_cb' argument of when registering a taxonomy. This is documented in the Codex, sort of:

```

meta_box_cb
    (callback) (optional) Provide a callback function name for the meta box display. (Available since 3.8)

        Default: null 

Note: Defaults to the categories meta box (post_categories_meta_box() in meta-boxes.php) for hierarchical taxonomies and the tags meta box (post_tags_meta_box()) for non-hierarchical taxonomies. No meta box is shown if set to false. 
```
It really doesn't say specifically that you can switch them, but, specifying one of the default callbacks it is possible to swap them.

```
// will cause the taxonomy to use the hierarchical category type
// checkbox metabox even if the taxonomy is not hierarchical.
'meta_box_cb' => 'post_categories_meta_box'
```

```
// will cause the taxonomy to use the hierarchical tag type
// metabox even if the taxonomy is is hierarchical.
'meta_box_cb' => 'post_tags_meta_box'
```

Making the terms non-editable is a bit more tricky and I'm not sure that remember where I discovered it, I do remember hunting for quite a while and doing some trial and error testing to get it to work.

Not sure that it would be useful to a lot of people. My thought is that a developer could set up a taxonomy and the terms needed on a site and then later disable the ability to add/edit/delete terms so that the client can't alter them. This can be accomplished by adding modifying the 'capabilities' argument when registering a taxonomy.

The following is an example of the code I'm using in a plugin that I'm creating that adds a non-hierarchical taxonomy that uses the category meta box and that does not allow the editing of terms.

```
$taxonomy = 'name-of-taxonomy-here';
$taxonomy_post_types = array('page'); // list of post type to attach the taxonomy to
$taxonomy_args = array(
    'label' => '',
    'labels' => array(),
    'public' => false,
    'show_ui' => true,
    'show_in_nav_menus' => false,
    'show_tagcloud' => false,
    'meta_box_cb' => 'post_categories_meta_box',
    'show_admin_column' => true,
    'hierarchical' => false,
    'query_var' => $taxonomy,
    'rewrite' => false,
    'capabilities' => array(
        'manage_terms' => false,
        'edit_terms' => false,
        'delete_terms' => false,
        'assign_terms' => 'edit_posts'
    )
);
register_taxonomy($taxonomy, $taxonomy_post_types, $taxonomy_args);
```

~JH

**Comment by tw2113** [comment]
Related: #311

**Comment by tw2113** [comment]
Closing in favor of 311
