### ISSUE TITLE
The Menu Icon of Custom Post Types

### ISSUE THREAD

**Issue by appally** [WebDevStudios/custom-post-type-ui#202]
by default the menu icon of the wordpress is: https://developer.wordpress.org/resource/dashicons/
and http://melchoyce.github.io/dashicons/

but CPT UI only set Full URL for icon.why not use the dashicon?

**Comment by tw2113** [comment]
Dashicons are fully supported as of one of the last updates to the .org copy as well as in 0.9.0. The 0.8.x one may not have the best note about it, but I just checked and 0.9.0 has "(Full URL for icon or Dashicon class)" below the field.

**Comment by appally** [comment]
wow~ thank you!

**Comment by tw2113** [comment]
Welcome.
