### ISSUE TITLE
get code and escaped characters in description

### ISSUE THREAD

**Issue by davidh-ssec** [WebDevStudios/custom-post-type-ui#206]
If you have quotes (or I'm guessing other special characters) in the description of a CPT, the "Get Code" text doesn't have these characters escaped. If a user copy/pastes the text in to functions.php there is a syntax error. In my case I used an apostrophe (single quote) in my description and I got a syntax error. I'm new to PHP, so I'm not sure the "correct" way to sanitize this information. The quick solution for a user is to just escape the characters with a backslash.

**Comment by davidh-ssec** [comment]
I think this is similar to issue #100, but I don't think it is fixed by that commit.

**Comment by tw2113** [comment]
@davidh-ssec could you pull down a fresh copy of the dev branch and see if it's behaving the way you'd expect with this regard? At least in terms of the description field. If you could report any findings for the labels as well, that'd be awesome. I'm going to poke at the code and see how quotes are reacting in the labels as well.

**Comment by tw2113** [comment]
Decided to strip quotes from labels completely instead of trying to deal with escaping them and then removing the escape characters for display in the WP admin.

**Comment by davidh-ssec** [comment]
So should I still test the dev branch? When you strip these from labels, do you also strip them from the description?

**Comment by tw2113** [comment]
Yes, always the dev branch. Master is still at the state of 0.8.x

I strip quotes completely from labels, but leave quotes in the description, hopefully escaped appropriately.

**Comment by davidh-ssec** [comment]
Just tested what was in the dev branch with a simple description and the get code did show the single quote properly escaped. Thanks.

**Comment by tw2113** [comment]
Welcome. Thank you for helping test and confirm.
