### ISSUE TITLE
Admin Icons disappear

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#207]
Waiting on a bit more feedback, but one user had icons reported to be disappeared. Simply re-saving the options appears to have fixed the issue and returned them, but users shouldn't have to do so much.

**Comment by Daronspence** [comment]
+1 on this issue as well. Editing the CPT and re-saving it usually fixed it.

**Comment by tw2113** [comment]
I believe it's because I was passing in empty strings instead of expected `null`. This should be fixed in master now.
