### ISSUE TITLE
Frontend links are 404ing after upgrade

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#208]

**Comment by Daronspence** [comment]
+1 to this... scared the shit outta me when a client called with 400+ posts in a CPT that started 404ing...

**Comment by tw2113** [comment]
revert them back to 0.8.5

**Comment by Daronspence** [comment]
I did. Just adding a +1

**Comment by tw2113** [comment]
@Daronspence 0.9.5 is going to essentially revert you back to 0.8.5 with a new version number, in case you're curious.

**Comment by Daronspence** [comment]
Good to know (:

**Comment by jeichorn** [comment]
Thanks for the quick rollback release

**Comment by tw2113** [comment]
You're welcome. Wish I didn't have to do it, but it is what it is :|

**Comment by tw2113** [comment]
Discovered that query_var strictly checks for boolean values, and doesn't type cast string "true"/"false" to boolean counterparts, thus passing in a string of "true" makes the query var "true". This should also now be fixed in master.
