### ISSUE TITLE
Export not generating custom rewrite rules (V1)

### ISSUE THREAD

**Issue by JulienMelissas** [WebDevStudios/custom-post-type-ui#212]
When I create a new CPT, and then go to export it, some the rewrite functions are not generated.

Currently with `'with_front'` set to `false` and Custom Rewrite Slug set to `'/foo'` it's generating:
```
...
'hierarchical' => false,
'rewrite' => true,
'query_var' => true,
...
```
when it should be generating:
```
...
'hierarchical' => false,
'rewrite' => array( 'slug' => '/foo', 'with_front' => false ),
'query_var' => true,
...
```

**Comment by JulienMelissas** [comment]
Just for the record, this is happening with Custom Taxonomies as well.

**Comment by tw2113** [comment]
@JulienMelissas is this for the post types tab, or the "get code" tab? Trying to figure out where the source of the issue is going to be. If the "post types" tab in the import/export area, then it's probably not saving to the option properly.

**Comment by JulienMelissas** [comment]
Pretty sure this was in the "get code" tab - sorry for not clarifying!

**Comment by tw2113** [comment]
Gotcha, thanks.
