### ISSUE TITLE
The menu position in the sidebar isn't respected in version 1.0 anymore

### ISSUE THREAD

**Issue by rpkoller** [WebDevStudios/custom-post-type-ui#213]
I've updated CPT UI to version 1.0 on two of my local test installs. I was updating from version 0.8.5 on WP 4.1. Somehow the set menu position numbers aren't respected anymore in the latest version cuz the order is somehow mixed up. I have to admit i am unable to figure out a pattern like reveresed order or something alike. In both cases the intended original version ( CPT UI 0.8.5) is on the left and the updated version (CPT UI 1.0) on the right hand. Debug mode was switched on but there aren't any warnings or errors outputted. The first example has a complete mixed up order: 

![example1](https://cloud.githubusercontent.com/assets/1665422/6117162/1761b21c-b0b3-11e4-8402-6317338084e0.png)

The second example has only one position moved ( from the beginning to the end of the custom post types )

![example2](https://cloud.githubusercontent.com/assets/1665422/6117176/30a79eda-b0b3-11e4-984e-dd5677151317.png)
 
Best regards r.

**Comment by tw2113** [comment]
Thanks for reporting this. I'll look into what's possibly going on and if it's a bug-fix thing that needs pushed out, it'll be part of 1.0.1.

Hopefully the rest of it is working as expected still, but let me know of issues there as well.

**Comment by rpkoller** [comment]
Thanks for the quick feedback. If you need any further infos to track the issue down let me know. The rest of the plugin looks pretty solid so far! :) In the case i notice anything i will create another issue. 

p.s. how, or let's better say, where do you handle the localization? Via github or seperately somewhere else? Cuz the german localization is missing a few strings. If i find some time in the next days i might post a suggestion for updated localization files.

**Comment by tw2113** [comment]
I imagine most of the strings need updated because of how much rewriting went on with this. I probably need to refresh the pot file too after some changes today, now that I think about it.

Pull requests, zipped po/mo files that are emailed, either way works for me. I would love to be able to keep you on record for localization notes so that I can better prepare the task with future updates.

**Comment by rpkoller** [comment]
Sure, well just let me know when you've refreshed the pot file then i'll download and take a look whats missing as well as which parts might be updated.

**Comment by tw2113** [comment]
Pot file is updated in master.

**Comment by tw2113** [comment]
What menu position are you using with this?

**Comment by tw2113** [comment]
Hoping to have the menu position issue resolved. It's in the master branch here on github now

6ba6ac7955e32b3d3ab3124ac5e0ed8690018c1f

If you're feeling adventurous and have the dev site to use, please help confirm it's fixed and behaving as expected.

**Comment by rpkoller** [comment]
regarding the pot file: 
one general question. i've taken a look at the present state. the german localization uses a mix of amicable and formal forms of address. In english there is only "you". In german you distinguish between "Du" (second person singular) and "Sie" (third person singular). I think i would go with the latter in the cases necessary but try to avoid in general.  

regarding the positions: 

first picture: 
Yellow line has 31
brownish line has 32
purple line has 30
green line has 29
light blue line has 27
red line has 26
the last line ( no idea whats the name of that color ;)))  ) is 28

second picture: 
zitate line has 27
light brown line has 29
blue line has 31
purple line has 32 
green line has 33
unknown color line has 34
red line has 28

**Comment by rpkoller** [comment]
about the the fix. do i only have to replace the older plugin folder with the new one. i dont have to deactivate the plugin before?

**Comment by tw2113** [comment]
If you use the zip download for the branch, it'll append the branch name to the file, if I recall right. If you rename the extracted folder to match what's already on the site, then it should overwrite with the updates. If you wish to retain the old copy long enough to revert to, then leave the folder named differently, deactivate the current plugin, and activate the new one.

New one will be listed as "1.0.1" in your admin.

**Comment by tw2113** [comment]
I don't know German at all, so i'm trusting your knowledge on the subject to get things consistent there :)

**Comment by rpkoller** [comment]
yep found the 1.0.1 branch right before i read your reply. will zip download the branch now and bring the 1.0.1 in place and give it a try. give me a minute please .

**Comment by rpkoller** [comment]
wohoo, both test installs show now the right order i have in the live versions. thanks! looks fixed. ;)) 

and about the localization. I start now before i am off to bed. But uncertain if i will be able to finish today. might take a day or two possibly.

**Comment by tw2113** [comment]
No rush on the internationalization. I can slip that in in a point release as necessary.

**Comment by rpkoller** [comment]
uh one last question regarding the localization. Is the master i've downloaded as a zip file really the latest version? Cuz one string shows: 
```
The leading book on WordPress design and development!<br /><strong>Brand new second edition!
```
But the active plugin of the 1.0.1 branch is showing off the third edition?

**Comment by tw2113** [comment]
If it somehow wasn't updated before, try again, I just pushed an refreshed copy inside the 1.0.1 branch.

Not sure how the "second edition" slipped through.

**Comment by rpkoller** [comment]
ok i'll redownload the 1.0.1 branch and start.

**Comment by rpkoller** [comment]
hmmm that's really odd. i've redownloaded the recent version of the 1.0.1 branch but as you can see still the second edition there???

![secondedition](https://cloud.githubusercontent.com/assets/1665422/6139183/00d3be42-b189-11e4-82cc-c1f6f8c9caa0.png)

**Comment by rpkoller** [comment]
hm it seems that the german pot file is a bit outdated inside the languages folder:

![bildschirmfoto 2015-02-11 um 01 04 38](https://cloud.githubusercontent.com/assets/1665422/6139292/0b77c18a-b18a-11e4-9467-aac72b8426d3.png)


the german version has 204 strings to translate while the base pot file version has 267

**Comment by tw2113** [comment]
Yeah, that's how big of an upgrade this was. There should be some way to update the catalog and preserve the existing translations, at least the best it can.

**Comment by rpkoller** [comment]
hm i am rather new to the localization thing. It's more or less the first time i play around with poedit. I've used the command "update from sources" inside the catalogue menu point -  at least the string count shows 267 now. ;) just uncertain if anything might get broken ;)))

**Comment by tw2113** [comment]
Just in case, I updated the catalog myself and pushed up the changes. Lots left to actually translate from what I can see, but it's there.

**Comment by rpkoller** [comment]
hmmm i download the 1.0.1 branch again and compare things. But maybe probably better go with your version.

**Comment by rpkoller** [comment]
mh by the way. -ja (72 strings), -tr_TR (204 strings) and zh_CN (72 strings) are also quite outdated. guess the pot files should be updated from the source too.

**Comment by tw2113** [comment]
Most likely. I just haven't bothered quite yet with those since no one is touching them yet :D You're focusing on german so I went with that for now.
