### ISSUE TITLE
Latest update wiped out all the Custom Post Types

### ISSUE THREAD

**Issue by jlebkowsky** [WebDevStudios/custom-post-type-ui#216]
Ran update today, and all the Custom Post Types on our site are missing now.

**Comment by jlebkowsky** [comment]
Okay, I found the Custom Post Types. None of the links to various posts were working, but after going into the plugin and attempting to work with it, the links seem to have returned. Mysterious.

**Comment by tw2113** [comment]
Hi @jlebkowsky Sounds like things are working again. I wager part of it was a case of the permalinks needed flushed after the conversion, which I haven't managed to figure out how to do automatically.

The posts in the post types were never lost, for what it's worth, the post types were just temporarily not registered thus the menu items weren't shown for a moment.

If things were going to be mission critical to get back going asap, the previous plugin settings were preserved and you'd be able to revert back to the previous version of the plugin.

Closing as things look to be a-okay again.

**Comment by chrisblakley** [comment]
Just ran into the same issue and wanted to mention to anyone that finds this thread- to flush your permalinks, simply go to Settings > Permalinks and re-save.

@tw2113 Not having looked into programmatically updating permalink settings, could you do something like the following? (warning: untested pseudo-code)
```php
$initial_option = get_option('permalink_structure');
update_option('permalink_structure', $initial_option);
```

**Comment by tw2113** [comment]
well i have a flush_rewrite_rules() function call after the updating of the option after transition, but it seems to not be working like i would hope.

**Comment by jlebkowsky** [comment]
Thanks! I'm sure that was it.
