### ISSUE TITLE
Troubleshooting CPT UI

### ISSUE THREAD

**Issue by pixldesigns** [WebDevStudios/custom-post-type-ui#217]
The latest 1.0.0 release breaks everything for our location PHP where we overwrote a page path to point to the CPT path instead. Not sure exactly what's happening or if this is a correct way to put in an issue, but wanted to share. I can drop our code in for someone if that helps.

**Comment by tw2113** [comment]
I know it sounds fairly simplistic, but have you flushed the permalink rules since updating? I have found that's helping a good portion of the time for people reporting issues. Another step that has seemed to work for some, is in the new version, just select each post type, and click "edit post type" to re-save, without changing anything, and then re-check the urls.

If that doesn't clear things up, I'll very likely be looking to see what type of code you're using to point to the CPT path and see what I can determine.

**Comment by pixldesigns** [comment]
Thanks for the feedback, just tried that now and none of that worked. The URL itself is correct but it's pulling up the original page URL instead of the Locations URL.

Here's the code I'm using:

<?php

/*
Template Name: Locations
*/

add_action('genesis_before_content', 'center_homepage_featured_image');

function center_homepage_featured_image() {
	
	$center_info = get_center_information();
	
	?>
	
	<?php putRevSlider($center_info['slider_id']) ?>
	
	<div class="medium-red-bg statement-bar">
		<h1 class="white center cell"><?php echo $center_info['location_name'][0]?></h1>
	</div>
	
	<div class="center-info-bar">
	
		<div class="one-fourth first right-border small-padding-top">
			<p>
			<img src="/wp-content/uploads/center/center-icon-hours.svg" class="center-icons" align="left" />
				Today's hours:<br />
				<?php echo $center_info['today_hour'][0]?>
			</p>
		</div>
		
		<div class="one-fourth right-border small-padding-top">
			<p>
			<img src="/wp-content/uploads/center/center-icon-map-marker.svg" class="center-icons"  align="left" />
			<a href="<?php echo $center_info['google_map_link'][0]?>" target="_blank"><?php echo $center_info['address'][0]?><br />
				<?php echo $center_info['city'][0]?>, <?php echo $center_info['state'][0]?> <?php echo $center_info['zip'][0]?></a></p>
		</div>
		
		<div class="one-fourth right-border small-padding-top">
			<img src="/wp-content/uploads/center/center-icon-phone.svg" class="center-icons"  align="left" />
			<p class="small-padding-top"><?php echo $center_info['phone'][0]?></p>
		</div>
		
		<div class="one-fourth small-padding-top">
			<img src="/wp-content/uploads/center/center-icon-facebook.svg" class="center-icons"  align="left" />
			<p class="small-padding-top"><a href="<?php echo $center_info['facebook'][0]?>" target="_blank">Find us on Facebook</a>
			</p>
		</div>
	</div>

	<?php
}


/** Functions - Start **/


add_action( 'genesis_sidebar', 'center_page_sidebar', 1);

function center_page_sidebar() {

	
	?>
		
	<div class="center-page-sidbar-area">
	
		<?php
		
		genesis_structural_wrap( 'center-page-sidebar' );
		
			genesis_widget_area( 'center-page-sidebar', array(
				'before' => '',
				'after'	 => '',
			));
		
		genesis_structural_wrap( 'center-page-sidebar', 'close' );
		
		?>
	
	</div>
	
	<?php 
}

remove_all_actions("genesis_entry_header");
remove_all_actions("genesis_entry_footer");

function get_center_information(){

	$center_info = get_post_custom();
	$the_post = get_post();
	
	$dayofweek = date("N");
	
	switch($dayofweek){
	
		case 1:
			$center_info['today_hour'] = $center_info['monday_hours'];
			break;
		case 2:
			$center_info['today_hour'] = $center_info['tuesday_hours'];
			break;
		case 3:
			$center_info['today_hour'] = $center_info['wednesday_hours'];
			break;
		case 4:
			$center_info['today_hour'] = $center_info['thursday_hours'];
			break;
		case 5:
			$center_info['today_hour'] = $center_info['friday_hours'];
			break;
		case 6:
			$center_info['today_hour'] = $center_info['saturday_hours'];
			break;
		case 7:
			$center_info['today_hour'] = $center_info['sunday_hours'];
			break;
				
	}
	
	$center_info['slider_id'] = 'slider_' . $the_post->post_name;
	
	return $center_info;
	
}





/** Functions - End **/


genesis();

?>

**Comment by pixldesigns** [comment]
And here's the code in my functions.php

* Location pages related - Start */

$locations_slug = "locations";

function flush_custom_rewrite_rules()
{
	global $wp_rewrite;
	$wp_rewrite->flush_rules();
}
add_action('init', 'flush_custom_rewrite_rules');


function add_locations_childpages_rewrites(){
	global $wp_rewrite;
	$new_rules = array();

	$centerpages_slug_list = get_centerpages_slug_list();
	
	foreach ($centerpages_slug_list as $slug=>$page_id){
		$child_pages = get_centerpage_childpages_slug_list($page_id);
		
		foreach($child_pages as $child_page_slug=>$child_page_id){	
			$new_rules["^locations/$slug/$child_page_slug?"] = 'index.php?page_id=' .$child_page_id;
		}
	}
	
	$wp_rewrite->rules = $new_rules + $wp_rewrite->rules;
}
add_action('generate_rewrite_rules', 'add_locations_childpages_rewrites');



function get_centerpages_slug_list(){
	global $locations_slug;
	global $wpdb;
	
	$posts = get_posts(array('posts_per_page'=>1, 'post_type'=>'page', 'name' => $locations_slug));
	
	if (!$posts || count($posts) <= 0) return array();

	$rows = $wpdb->get_results("SELECT ID, post_name FROM wp_posts WHERE post_type='page' AND post_parent='" . $posts[0]->ID . "'");
	
	$results = array();
	
	foreach($rows as $row){
		$results[$row->post_name] = $row->ID;
	}
	
	return $results;
}

function get_centerpage_childpages_slug_list($centerpage_id){
	
	global $wpdb;
	
	if (!$centerpage_id) return array();
	
	$rows = $wpdb->get_results("SELECT ID, post_name FROM wp_posts WHERE post_type='page' AND post_parent='" . $centerpage_id . "'");
	
	$results = array();
	
	foreach($rows as $row){
		$results[$row->post_name] = $row->ID;
	}
	
	return $results;
}

**Comment by pixldesigns** [comment]
Sorry, here's a cleaner version

```php
* Location pages related - Start */

$locations_slug = "locations";

function flush_custom_rewrite_rules()
{
	global $wp_rewrite;
	$wp_rewrite->flush_rules();
}
add_action('init', 'flush_custom_rewrite_rules');


function add_locations_childpages_rewrites(){
	global $wp_rewrite;
	$new_rules = array();

	$centerpages_slug_list = get_centerpages_slug_list();
	
	foreach ($centerpages_slug_list as $slug=>$page_id){
		$child_pages = get_centerpage_childpages_slug_list($page_id);
		
		foreach($child_pages as $child_page_slug=>$child_page_id){	
			$new_rules["^locations/$slug/$child_page_slug?"] = 'index.php?page_id=' .$child_page_id;
		}
	}
	
	$wp_rewrite->rules = $new_rules + $wp_rewrite->rules;
}
add_action('generate_rewrite_rules', 'add_locations_childpages_rewrites');



function get_centerpages_slug_list(){
	global $locations_slug;
	global $wpdb;
	
	$posts = get_posts(array('posts_per_page'=>1, 'post_type'=>'page', 'name' => $locations_slug));
	
	if (!$posts || count($posts) <= 0) return array();

	$rows = $wpdb->get_results("SELECT ID, post_name FROM wp_posts WHERE post_type='page' AND post_parent='" . $posts[0]->ID . "'");
	
	$results = array();
	
	foreach($rows as $row){
		$results[$row->post_name] = $row->ID;
	}
	
	return $results;
}

function get_centerpage_childpages_slug_list($centerpage_id){
	
	global $wpdb;
	
	if (!$centerpage_id) return array();
	
	$rows = $wpdb->get_results("SELECT ID, post_name FROM wp_posts WHERE post_type='page' AND post_parent='" . $centerpage_id . "'");
	
	$results = array();
	
	foreach($rows as $row){
		$results[$row->post_name] = $row->ID;
	}
	
	return $results;
}
```

**Comment by tw2113** [comment]
Just so I'm certain I'm looking at the correct stuff, are both of the comments above accurate for what you're using at the moment?

**Comment by pixldesigns** [comment]
Yep!

**Comment by tw2113** [comment]
Looking things over, it appears that the major part that I'd need to focus on is the add_locations_childpages_rewrites callback. and all it's doing really is adding the new rewrites to match locations hierarchy slugs based on the provided page ID.

My question at the moment is if the returned slugs used for the locations are matching up with what you had with 0.8.5/0.9.5 compared to 1.0.0.

I assume "locations" is the CPT being registered.

In regards to CPTUI, the only thing I could see being hinged on at the moment is if the locations post type is still being registered as hierarchical, based on the $new_rules array you're prepending.

Also not completely sure about this line as a whole: $wp_rewrite->rules = $new_rules + $wp_rewrite->rules; but that's because I'm not exactly familiar offhand what type data is in that $wp_rewrite property. It just looks odd to me to be doing the `+` as opposed to `.` for concatenation.

**Comment by pixldesigns** [comment]
Yes, "locations" is the CPT.

The + symbol is used for merging two arrays, not dot operator so this should be syntactically right.

**Comment by tw2113** [comment]
Have we verified that the slugs are matching up still? Have you tried this with CPTUI 1.0.2 that was released today?

**Comment by pixldesigns** [comment]
Slugs are matching still. Just tried the new one out and still broken for me. I'm having a contract programmer to take a look on Monday to see what needs to change on our end to get this corrected.

**Comment by tw2113** [comment]
If you're fine with accessing the database, delete the cptui_post_types and cptui_taxonomies rows from the options table and let 1.0.2 re-convert the original settings. I think you're probably caught in the middle after some changes I had to make.

**Comment by pixldesigns** [comment]
From my programmer: This solution recommended didn't work. The problem is
that you are having normal pages for each location (with same URL -
/locations/blahblah) and this normal page URL rewrite just takes over the
CPTUI url rewrite (for custom post type) on this new version.

**Comment by tw2113** [comment]
Not sure at this point, to be honest. I'd have at least a somewhat better idea of why it's happening if I at least knew which part of the 1.0.x version is different for this case compared to the old version.

**Comment by pixldesigns** [comment]
Gotcha. Well I appreciate the thoughts/ideas to try out!

On Tue, Feb 17, 2015 at 5:14 PM, Michael Beckwith <notifications@github.com>
wrote:

> Not sure at this point, to be honest. I'd have at least a somewhat better
> idea of why it's happening if I at least knew which part of the 1.0.x
> version is different for this case compared to the old version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebDevStudios/custom-post-type-ui/issues/217#issuecomment-74784693>
> .
>



-- 
Joshua Brown
PIXL Designs
615.682.2012

http://www.pixldesigns.com

**Comment by tw2113** [comment]
Let me know what you find, so that I can determine if it's something I need to change on our end to help alleviate the issue/
