### ISSUE TITLE
Localization: Is string 170 missing one \" 

### ISSUE THREAD

**Issue by rpkoller** [WebDevStudios/custom-post-type-ui#222]
Is it possible that 

```
\"Use the option below to explicitly set \"supports\" to false.
```
 
is missing one closing `\"`. I was unable to find it in the interface so far to cross check. Best regards Ralf

**Comment by tw2113** [comment]
Actually looks like the opening one is the mistake addition.

Removed.

**Comment by rpkoller** [comment]
Ok i remove it in the german pot file too for the english as well as the german version. thanks

**Comment by rpkoller** [comment]
Ups i am unable to change the source text. Only able to change the translation string. So all good i hope if i only change the german one.
