### ISSUE TITLE
Suggestion of a different naming of the sub menu element CPT UI in the sidebar

### ISSUE THREAD

**Issue by rpkoller** [WebDevStudios/custom-post-type-ui#223]
At the moment the main menu point in the sidebar is named CPT UI as well as the child element CPT UI. From a users stand point i am unable to guess what it is hidden behind the child element. At least i wouldn't expect the content which is actually there. 

![bildschirmfoto 2015-02-11 um 16 59 11 2](https://cloud.githubusercontent.com/assets/1665422/6150387/63590c08-b20f-11e4-97a9-16cb5b009c79.png)

how about rename it to "intro" or "about" in the english version?

**Comment by tw2113** [comment]
If you know of a way to separate the two, I'm all ears. If I recall right, changing the parent changes the child.

**Comment by rpkoller** [comment]
hm you might remove the CPT UI submenu item with `remove_submenu_page`. But i don't know how "clean" that approach would be. at least it works as you can see in the screenshot.  

![bildschirmfoto 2015-02-11 um 17 14 52](https://cloud.githubusercontent.com/assets/1665422/6150792/c4e7ec08-b211-11e4-9983-9ed17b361e63.png)

**Comment by rpkoller** [comment]
mh i've taken a brief look again onto that matter. You have your add_submenu_page definitions in separate php files inside the inc folder. if you move those out and bundle all add_menu & sub_menu definition inside the cptui_plugin_menu function you are able to pull the plug on the showing up of CPT UI twice as menu and submenu by just using the remove_submenu_page after all menu and submenu pages are added inside the function. And then you might add a separate submenu for the "about" page which is shown at the CPT UI menu/submenu points?

**Comment by tw2113** [comment]
Rearranged and fixed in 1.1 branch.
