### ISSUE TITLE
Localization: Remove one &middot; from String 18

### ISSUE THREAD

**Issue by rpkoller** [WebDevStudios/custom-post-type-ui#226]
Again a slight cosmetic issue. At the moment you have a middot between Follow on Twitter: and Michael. 

```
%s version %s by %s - %s %s &middot; %s &middot; %s &middot; %s
```

But that kind of separator is only necessary between Michael and Brad as well as Brad and WebDevStudios. So instead

```
%s version %s by %s - %s %s %s &middot; %s &middot; %s
```

**Comment by tw2113** [comment]
removed in 1.0.2 for the moment. Not sure quite yet if there will be an official 1.0.2 release.
