### ISSUE TITLE
Localisation: Would it possible to get seperate "Add new" strings for the Post type and taxonomy tabs

### ISSUE THREAD

**Issue by rpkoller** [WebDevStudios/custom-post-type-ui#227]
At the moment both use the string number 24. But in the german version it isn't be possible to use the same twice like in the english version. If i write just ADD in german as the label for the tab it wouldn't be correct and rather confusing. So i would prefer to be able to use different labels for the add new tab in the post types and taxonomy section.

**Comment by tw2113** [comment]
I'm confused as to why it can't use the same twice, to be honest. It's also not something I think I can control, other than adding more words to it. Poedit matches up the strings and puts the line references next to each translated version in the .po file so that the computer can make the proper .mo file.

**Comment by rpkoller** [comment]
At the moment there is only "add new" and it is used for the tab in the post types section as well as the tab in taxonomy section. In german you can't write something similar to add new. 

post types would be in a brief form " Neuen hinzufügen"
taxonomy would be in a brief form "Neue hinzufügen" 

slightly different. and an indifferent version like just "new" / "neu" or just "add" / "hinzufügen" is so so. I think the best choice would be "Neu" then. Translations are tricky. :/

**Comment by rpkoller** [comment]
oh is it possible that "with front" and "query var" about texts have the same content?

**Comment by tw2113** [comment]
Is the lack of the N in "Neuen" vs "Neue" dependent on context to what's being linguistically related to? Pardon my American ignorance, I'm not trying to debate legitimacy, but I'm still not sure why that difference would be needed when both tabs simply say "Add New" for each.

Honestly all the help text bubbles likely need updated/made more accurate. That may be something I push for in 1.1.0. Not sure if that's going to affect what you're working on.

**Comment by rpkoller** [comment]
Exactly. There is a grammatical differentiation in german based onto what the word "new" refers to. And sure for the english versions it is unnecessary in german for example it would make a difference. ;) But as i said i could just write "Neu" which is a neutral way without any context. only a bit unexplicit.

Possibly it will affect the things i am working on. But at least the german version is up to speed with the english one now. The update would be less work afterwards... hopefully. ;) But i think it would be good to have a refinement in a few days or weeks anyway. If you push the german localization in an update so we could include also feedback to it. Cuz i have to admit in a few cases it is difficult to translate and i am uncertain if everything is clear for everbody. So push the german pot files in an update when i am done ( guess one or two more hours then its up to you when you are ready for an update) and then wait for possible feedback. and then i could include changes based on the feedback and your refinements in a future update if that procedure would be fine with you?

**Comment by tw2113** [comment]
I'm pretty open to this aspect myself. Whatever gets done.

**Comment by tw2113** [comment]
Changing the "Add New" to include either "Post Type" or "Taxonomy". Just so you're prepared. Closing this in the meantime.

**Comment by rpkoller** [comment]
ah cool. just let me know when i should do the new strings for 1.0.3.
