### ISSUE TITLE
Show in menu seems to be broken in  various ways in the localisation

### ISSUE THREAD

**Issue by rpkoller** [WebDevStudios/custom-post-type-ui#228]
Somehow that part isn't behaving well ( add/edit post type -> add new -> settings ->show in menu). First i have localized the string properly (id 140) but as far as you can see it isn't showing the localized version and still the english. 

![bildschirmfoto 2015-02-12 um 01 04 53 2](https://cloud.githubusercontent.com/assets/1665422/6159263/750bf0de-b253-11e4-86f4-d1ff8818854c.png)

Aside that the form field shouldn't there neither and only the boolean select field instead. :/

**Comment by tw2113** [comment]
Try clicking to update the catalog, there's chance that the line numbers are mismatched. Worst case, zip up the po file you're working with at the moment and I can check on things on my end as well.

The second field is for indicating which part to be a submenu of. Not sure if you're thinking it should be hidden until needed, or something else.

**Comment by rpkoller** [comment]
no still not working. chose update from source in poedit. but no luck. no changes where detected. shall i send it to the emailadress in the plugin footer? 

ahhh that is meant with second input! the liner notes were a bit misleading. Now i get it. have to rewrite it afterwards again i guess.

**Comment by tw2113** [comment]
Send the files to michael @ webdevstudios.com and I'll look at it soon.

**Comment by rpkoller** [comment]
ah cool thanks. already sent. Then i go on meanwhile doing the finishing touches of the second revision. ah and you have my email adress now too as a side effect. ;) you asked for in another issue.

**Comment by rpkoller** [comment]
string 170 is also still shown in english :/

**Comment by tw2113** [comment]
Realized I had 2 textdomains that had an extra S on them, so they weren't matching like they should be. Fixed that, and added the po/mo file to the 1.0.2 branch while I was at it. Pulling that should pull down the latest copy of the file with line numbers matching to what will be 1.0.2.

**Comment by rpkoller** [comment]
shall i download the 1.0.2 branch and then copy my two files i am working on right now into the languages folder and then sync with (the new) source? or finish the remaining strings to check first?

**Comment by tw2113** [comment]
Not sure how best to merge the two without just doing manual, to be honest :D 

How much has changed since earlier? Not sure if you've been feverishly typing away or if you just have a few edits to make.

**Comment by rpkoller** [comment]
Since the version i've sent you via mail quite a bit still changed ;) and still a bit to go. Anyway i will finish up and then try out. ;) Will keep you posted. But unsure how much longer i will be on it tonight. Already 3 am over here ;) Bedtime is overdue basically. But wanted to finish it before ;) Well we'll see.

**Comment by tw2113** [comment]
Go to bed. This can wait.

**Comment by rpkoller** [comment]
oh string 204 is also in english only.

**Comment by rpkoller** [comment]
nah. at the moment it's fun and i could sleep more relaxed when it's done ;)

**Comment by rpkoller** [comment]
string 207 needs a questionmark in the end.

**Comment by tw2113** [comment]
updated

**Comment by rpkoller** [comment]
ok done now with the localization. will download 1.0.2 now and try the source update.

**Comment by rpkoller** [comment]
hm update from source seems to work and hasn't broken that much. there were only shown 3 new and 3 outdated fields. Seems the id's remained the same but poedit has just kicked out the three translated strings. i have just to reenter.

**Comment by rpkoller** [comment]
140 and 170 are working now. but 204 is still in english only. in the help section in the advanced part second question

**Comment by rpkoller** [comment]
and in the project preferencs  of the pot file i've update the name to Custom post Type UI 1.0. And regarding translator name and emailadress. Is Pascal Kläres still active?

**Comment by rpkoller** [comment]
But i think i am off to bed now. Leave me a quick note regarding string 204. And i will redownload the 1.0.2 branch and update the pot. Recheck things and then send you the two files via email in a few hours.

**Comment by tw2113** [comment]
Not that I'm aware of, regarding Pascal. If anything, add your name alongside both.

For line 204. I forgot the textdomain completely *facesmack*

**Comment by rpkoller** [comment]
Yeah already did that. ;) Contains now both names and email adresses. 

haha happens ^^
