### ISSUE TITLE
Fix i18n support for labels in "associate ___" sections of post types/taxonomies to not use slugs.

### ISSUE THREAD

**Issue by rpkoller** [WebDevStudios/custom-post-type-ui#229]
I've noticed only in one case but probably there are a few more occassions. e.g. if you hover with the mouse over the red questionmark in the taxonomy section "attach to post type"  

In German it shows :
```
Fügt post Unterstützung hinzu. 
```
thats the string id 174. 

But basically it should show the localized String for %s like Beitrag in that case.

**Comment by rpkoller** [comment]
You have a new mail too btw ;)

**Comment by tw2113** [comment]
master matches 1.0.2 now. May need to let me know the udated ID for that bit above.

**Comment by rpkoller** [comment]
i'll take a look... btw have you included the latest final pot files i've sent you tonight already?

**Comment by rpkoller** [comment]
the id is still 174 in the pot file included in the master. as well as in the version i've sent you yesterday. but the versions included in master differ in size to the one i've sent you. so is that the old version?

**Comment by tw2113** [comment]
I didn't receive any new pot file that I can see via email.

I know it sucks, but when push comes to shove, go based on what's in the repo. I noticed last night that you can update your catalog from a pot file, so that may help with managing merging

**Comment by rpkoller** [comment]
i've sent an email about 6 hours ago. :/

i've compared the version i've sent you with the version from the master. also removed the german master pot file and copied my version into it and used update from source in poedit. nothing outdated or missing. so nothing changed. 

so maybe shall i resend you the two files and you could use the newer version? and note to myself i have to get gittower2 setup again on my machine or at least git in combination with github then i can send pull requests again for the next time.

**Comment by tw2113** [comment]
When all else fails, email again :D

**Comment by rpkoller** [comment]
haha then let's hope for the best dear email gods :D sent.

**Comment by tw2113** [comment]
I took your po file, I updated the catalog from the pot file in master, and saved. Then I committed them to master.

**Comment by rpkoller** [comment]
Yep already downloaded the updated master and replaced in my test install. So about the last thing. If you take a look at string ID 174 ( it hasn't changed):

```
Adds %s support
```

the variable inserted isn't localized. The best place to check is if you go to the taxonomy section. There you see the "attach to post type" section. the one with the many checkboxes. if you hover over the questionsmarks of one checkbox you get about texts showing string number 174. Problem is the inserted snippets aren't localized. 

I've noticed that the project i am trying things has no advanced labels set. But i've rechecked the other project, there i actually have literally each field filled. but the same result. i realized basically for string ID 174 (in the taxonomy tool tip case) is pulling the custom post type slug instead of the post type labels. so i get only the english custom post type name (i've used english custom post type slugs). an example. i've hovered the questionmark for "Kundenlinks" (Customer links in english). the post type slug is called customerlinks. so that is what is filled in in that case. I think a label would be more appropriate. 

![bildschirmfoto 2015-02-12 um 19 20 25 2](https://cloud.githubusercontent.com/assets/1665422/6174011/5be39f32-b2ec-11e4-95e5-0e07444f0e0a.png)

**Comment by tw2113** [comment]
You're going to hate me, but I just merged a separate pull request with more strings to translate. It's in master.

Looking over the last comment above.

**Comment by tw2113** [comment]
Think the Singular name would be more appropriate. It definitely is taking the slug at the moment.

**Comment by rpkoller** [comment]
one quick question the "If left blank, the archive slug will default to the post type slug." line is for a regular field? haven't found it yet in the interface.

**Comment by tw2113** [comment]
Yes, it's for a string field, allowing for someone to provide a custom value, instead of boolean.

**Comment by rpkoller** [comment]
You got mail.

**Comment by rpkoller** [comment]
oh and maybe add to the changelog for the next release an invitation for feedback about the german translation. for further polishing. cuz a few parts are tricky. especially specific wordpress related words like query var, with front, rewrites and alike. where you are uncertain if you better leave it in english or translate it. tough decision. therefor feedback in that particular case would be valuable 

and aside you got a second mail. found a missing character in one string. sent you updated pot files.

**Comment by tw2113** [comment]
updated master.

This will likely be part of a 1.0.3 release, but I am not in a major hurry for it, as I'm hoping the dust settles on the previous 2 point releases.

**Comment by rpkoller** [comment]
No hurry. Then i will get my git setup sorted again meanwhile.

**Comment by tw2113** [comment]
Is there anything lingering in this one for you? It's kind of all over the place at the moment.

**Comment by rpkoller** [comment]
hmmm the main area of trouble is in the add/edit taxonomoy section within the attach to post type part in the form of the tool tips right behind each checkbox. if you hover over them you get none localized %s strings as i initially posted. if this is what you mean by lingering. ;) anywhere else i haven't noticed yet.

**Comment by tw2113** [comment]
Updated the title so that it's more obvious to me :D

**Comment by rpkoller** [comment]
I've rechecked the rest of the ui elements. The described location is the only place where the issue happens.

**Comment by tw2113** [comment]
899dae70e000268cf7bb1cd5ba353dd4a5b68e76

29537c20ace681be8bbe8bfac0c62119cec91d8d
