### ISSUE TITLE
Export > Get Code

### ISSUE THREAD

**Issue by simonseddon** [WebDevStudios/custom-post-type-ui#243]
When exporting PHP code, the resulting code block doesn't work. I'm using latest WP and PHP 5.6.1. Fixed the problem by changing the 1's to true and 0's to false.

**Comment by tw2113** [comment]
I'll double check the get code area and look into making sure we're not doing numeral boolean values. Thanks for the report for me to look into.

**Comment by tw2113** [comment]
Out of curiosity, what version of CPTUI are you on for this @simonseddon

**Comment by tw2113** [comment]
I believe we should be good here. Feel free to re-open if still an issue on the latest version of the plugin.
