### ISSUE TITLE
Taxonomy Slug - special characters bug

### ISSUE THREAD

**Issue by tommyno** [WebDevStudios/custom-post-type-ui#244]
How to reproduce:

Add a new Taxonomy. In the "Taxonomy Slug" field enter "Formål" (with special character "å"). 

The new taxonomy is created, but on the edit-list it stands as an blank space. I'm able to select it, but unable to delete or change it.

I know it's a bad idea to use a special character in the slug, but now I'm unable to remove it...

**Comment by tw2113** [comment]
does it appear still in the content on the right for the import/export area for taxonomies? You should be able to copy/paste that over to the left, change the one character, and click import. You'd retain all of the same settings and the character display would be fixed.

Gonna leave this open as a reminder to myself to look into special character checking on slugs.

**Comment by tommyno** [comment]
I tried exporting, change the character and then importing. The taxonomy slug is now correct, but it is still listed as an empty line in the select-list.

"fagområde" was saved as "fagomr\u00e5de".

**Comment by tw2113** [comment]
good ole unicode characters

**Comment by tw2113** [comment]
See response at https://github.com/WebDevStudios/custom-post-type-ui/issues/298#issuecomment-113863252

**Comment by tw2113** [comment]
Same reasoning as in #298 

I don't want to break existing setups, I do want to prevent new taxonomies with them.

**Comment by tw2113** [comment]
See #373 as well

**Comment by tw2113** [comment]
Ongoing, bumping for another release as we continue to improve on this.

**Comment by tw2113** [comment]
"Merging" into #373 since we'll be taking care of both slug types anyway. Makes this a duplicate.
