### ISSUE TITLE
First CPT in Edit page should be pre-selected

### ISSUE THREAD

**Issue by Alhadis** [WebDevStudios/custom-post-type-ui#245]
When navigating to the "Edit Post Types" page, the post-types dropdown should be pre-selected to the first value (or possibly the most-recently edited). Having to manually select a custom post type is rather bothersome - especially when there's only one that has to be edited. There's also no reason for the menu to use a null default value, either.

Also, colossal thanks for this beautiful plugin. It forms the spine of virtually every WordPress site I build these days, and it's naturally complemented by the Advanced Custom Fields plugin (which go together like Coke and pizza). Keep up the damn good work! :)

**Comment by tw2113** [comment]
Valid point here, and something I'll look into for 1.1. It would remove some clicking that others have raised issue with as well, which I want to improve on.

You're welcome. It's refreshing to get positive feedback alongside the not as positive that I've received with 1.0.x. From the sounds of it, you haven't had as many issues with it as others have, especially anyone coming from 0.9.x. Not sure how long you've been using it, but sounds like it's been awhile.

Anyways, thank you for the feedback and I'll look into getting it changed.

**Comment by tw2113** [comment]
Check 1.1-autoselected-type-tax for views of future support for this. Also added support for passing slugs via $_GET which will help out in other possible areas I have in mind.

**Comment by tw2113** [comment]
Merged this into 1.1 branch. Closing.
