### ISSUE TITLE
Notice: Undefined index: show_admin_column in [...]custom-post-type-ui.php on line 286

### ISSUE THREAD

**Issue by mgibbs189** [WebDevStudios/custom-post-type-ui#246]
Cheers

**Comment by tw2113** [comment]
If you're adventurous, it'd be awesome if you could help confirm the notice going away in the 1.0.4 branch.

**Comment by mgibbs189** [comment]
I already resolved the issue (by re-saving all my taxonomies). but your commit looks fine.

**Comment by tw2113** [comment]
Awesome. Thanks.
