### ISSUE TITLE
Missing Rewrite Rules

### ISSUE THREAD

**Issue by vankaiser** [WebDevStudios/custom-post-type-ui#251]
After I updated the custom post type ui plugin, the custom posts are now inaccessible and displays a not found error even though rewrite is set to true.

**Comment by tw2113** [comment]
Have you tried flushing the permalink rules yet? You can do so by visiting your permalinks settings page.

**Comment by vankaiser** [comment]
Thanks tw2113, that solved the problem.

**Comment by tw2113** [comment]
Welcome
