### ISSUE TITLE
Delete post type does not delete

### ISSUE THREAD

**Issue by vincentclark22** [WebDevStudios/custom-post-type-ui#252]
Custom Post Type UI version 1.0.4, WordPress Version 4.1.1
When I attempt to delete the selected custom post type, I get the pop up warning and select OK after which the entry fields return to blank, but the post type remains, both in the selecter of the Edit Tab and in the Admin sidebar menu.

**Comment by tw2113** [comment]
Hi Vincent, I'm not able to recreate with some of the CPTs I had in my dev install. While the side menu item persisted for a moment, until the browser loaded a new page, the menu item did get removed for me.

Not sure if you're wanting to record a quick screencast to show what you're seeing, or perhaps send me the settings from the import/export tab for your post types.

**Comment by vincentclark22** [comment]
Sorry, I also was unable to recreate the issue this time when I was recording for you.  Must be a glitch in local memory.  
  
  
   On March 9, 2015 at 11:04 AM Michael Beckwith <notifications@github.com> wrote:
   
   
   Hi Vincent, I'm not able to recreate with some of the CPTs I had in my dev install. While the side menu item persisted for a moment, until the browser loaded a new page, the menu item did get removed for me.
   Not sure if you're wanting to record a quick screencast to show what you're seeing, or perhaps send me the settings from the import/export tab for your post types.

**Comment by tw2113** [comment]
No worries, good to hear things are working as expected now :)
