### ISSUE TITLE
Separate the typo styling of the settings name and its label in the custom post types and taxonomies

### ISSUE THREAD

**Issue by rpkoller** [WebDevStudios/custom-post-type-ui#257]
At the moment you have the name of the setting and the lable underneath both in font-weight 600. Basically the text underneath is more or less a label/explanation; there for it would make sense to separate it typographically. maybe a lighter font-weight and maybe a font-style italic? 

![bildschirmfoto 2015-03-17 um 23 29 03](https://cloud.githubusercontent.com/assets/1665422/6698994/16653714-ccfe-11e4-8b18-b8bde9594107.png)

Cheers r.

**Comment by tw2113** [comment]
removing the bold and lowering the font size by 2px

**Comment by tw2113** [comment]
7548660
