### ISSUE TITLE
hierarchical issue with get code and taxonomies

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#261]
https://wordpress.org/support/topic/export-error-12?replies=2#post-6708680

**Comment by chriscoyier** [comment]
Do you happen to have a hotfix for this?

Our http://blog.codepen.io/meetups page went down because of this change I think.

**Comment by tw2113** [comment]
Hi Chris,
 if you upgraded from 0.8.x or 0.9.x (they're the same), for the quickest fix, I recommend just reverting https://downloads.wordpress.org/plugin/custom-post-type-ui.0.9.5.zip.

However, sometimes just flushing rewrite rules has fixed things as well. If things aren't coming back quickly, and you need it back up asap, the old settings are preserved and you can roll back.

The issue you're commenting on is regarding the exporting functionality for when trying to migrate away from CPTUI.

**Comment by chriscoyier** [comment]
Flushing rewrite rules did the trick, thanks!

**Comment by tw2113** [comment]
Welcome, Chris!

**Comment by tw2113** [comment]
Fixed in 1.0.5
