### ISSUE TITLE
Problems with ACF qTranslate & Custom Post Type UI 1.0.5

### ISSUE THREAD

**Issue by brunogdesign** [WebDevStudios/custom-post-type-ui#264]
Hi!

I'm having some issues with this plugin and Custom Post Type when Wordpress debug mode is active. I'm getting this error when accessing any of the CPT menus on Wordpress:
"Trying to get property of non-object in /Applications/MAMP/htdocs/wp_tourism360/wp-content/plugins/acf-qtranslate/src/acf_4/acf.php on line 152"

I don't really know if this is a problem with ACF or with CPT...

![screen shot 2015-04-02 at 11 17 34](https://cloud.githubusercontent.com/assets/1450050/6962162/e6b6cf7c-d929-11e4-9cc8-1dd38c6fc23e.png)

Am I the only one? Can anyone help me?

Best regards,
Bruno Garcia

**Comment by tw2113** [comment]
Those are issues with ACF-QTranslate, and not our plugin. Not sure why it may only show up on our screen though. Still best to report to them so that they can better check for available variables before acting.

**Comment by brunogdesign** [comment]
Thank you anyway ;)
