### ISSUE TITLE
Help text link (?) not showing up in some special settings

### ISSUE THREAD

**Issue by pedro-mendonca** [WebDevStudios/custom-post-type-ui#265]
In Add/Edit Post Types page, in the right side Settings, the entries with both dropdown select plus text field like **Has Archive** and **Show in Menu** don't have help text.

I've checked that what differs from other entries is the `'wrap' => false` in *inc/post-types.php*, but when I change them to `true` it unformats the whole entry. Something here is not showing the whole `<a>` help link and even the entry label don´t even have the html `<label>` (p.ex. "Has Archive").

**Comment by pedro-mendonca** [comment]
In these most complex entries that have both dropdown and text field, there is also a helptext from the text field that don't show up in a "(?)".

**Comment by tw2113** [comment]
Good catch. I'll have to determine best way to handle this a bit later, but I can squeeze it in in the 1.0.6 release.

Thanks Pedro.

**Comment by pedro-mendonca** [comment]
I found that you use `echo $ui->get_help(...)` below the title in some entries that solve the problem. It still wont use the ´<label>´ html tag for entry title, but that is something that mechanism that don't allow you to handle more complex entries, wich probably made you use the the simple __(´Field´) in the first place.

I'm preparing a PR to solve the basic issue of lack of (?) help texts, I'll leave to you the `<label>` issue. :)

**Comment by pedro-mendonca** [comment]
Hi

I found a cleaner way.
The problem is that in some cases like the *get_text_input* the (?) help text is after the `'labeltext'`. If the `wrap` is set to false, then the `$value .= $this->get_help( $args['helptext'] );` isn't loaded.

One could move this help text to the right of the box instead of following the `'labeltext'`, but I made it work with an exception where you place the `$value .= $this->get_help( $args['helptext'] );` after the text box in case of `wrap` being false, in the end of *get_text_input*:

```
		$value .= ' />';
		
		if ( $args['wrap'] == false ) {
			$value .= $this->get_help( $args['helptext'] );
		}
		$value .= '<br/>';
```

I think that with this it solves most of the problems.

I'll clean it a bit tomorrow and also add the html `<label>` to labels that have `<p>` below by using `echo $ui->get_label( 'has_archive', __( 'Has Archive', 'cpt-plugin' ) );`

**Comment by tw2113** [comment]
In short, I need to figure out the best way to still echo the help text when wrap is false, while not breaking layout. It's a change that will be made in class.cptui_admin_ui.php

**Comment by pedro-mendonca** [comment]
I see two options.

**1)** You keep the help text showing up before the </br> IF wrap is false
**2)** You use another string to check help text position, because you might want to put it in before the </br> even if the wrap is true.

As far as I see the help text is loaded ONLY if wrap is true and is loaded after field label.
You could have it optionally positioned before the </br>, independently of the wrap being true or false.

Of course that If the only situation where you'll put the help text before </br> is when you don't want to wrap it, and you code the table row from the outside as in these complex inputs, then using just the option 1) might be just good and simple.

**Comment by pedro-mendonca** [comment]
**Option 1**

```
	public function get_text_input( $args = array() ) {
		$defaults = $this->get_default_input_parameters(
			array(
				'maxlength'     => '',
				'onblur'        => '',
			)
		);
		$args = wp_parse_args( $args, $defaults );

		$value = '';
		if ( $args['wrap'] ) {
			$value .= $this->get_tr_start();
			$value .= $this->get_th_start();
			$value .= $this->get_label( $args['name'], $args['labeltext'] );
			if ( $args['required'] ) { $value .= $this->get_required(); }
			$value .= $this->get_th_end();
			$value .= $this->get_td_start();
		}

		$value .= '<input type="text" id="' . $args['name'] . '" name="' . $args['namearray'] . '[' . $args['name'] . ']" value="' . $args['textvalue'] . '"';

		if ( $args['maxlength'] ) {
			$value .= ' ' . $this->get_maxlength( $args['maxlength'] );
		}

		if ( $args['onblur'] ) {
			$value .= ' ' . $this->get_onblur( $args['onblur'] );
		}

		$value .= ' />';
		
		if ( !$args['wrap'] ) {
			$value .= $this->get_help( $args['helptext'] ).'HELP';
		}
		$value .= '<br/>';

		if ( !empty( $args['aftertext'] ) )
			$value .= $args['aftertext'];

		if ( $args['wrap'] ) {
			$value .= $this->get_td_end();
			$value .= $this->get_tr_end();
		}

		return $value;
	}
```

**Comment by pedro-mendonca** [comment]
**Option 2** - Using an aditional option *helptext_pos* to put help text after the text input, even if the text is wrapped.

```
	public function get_text_input( $args = array() ) {
		$defaults = $this->get_default_input_parameters(
			array(
				'maxlength'     => '',
				'onblur'        => '',
			)
		);
		$args = wp_parse_args( $args, $defaults );

		$value = '';
		if ( $args['wrap'] ) {
			$value .= $this->get_tr_start();
			$value .= $this->get_th_start();
			$value .= $this->get_label( $args['name'], $args['labeltext'] );
			if ( $args['required'] ) { $value .= $this->get_required(); }
			if ( $args['helptext_pos'] <> 'after_input' ) {
				$value .= $this->get_help( $args['helptext'] );
			}
			$value .= $this->get_th_end();
			$value .= $this->get_td_start();
		}

		$value .= '<input type="text" id="' . $args['name'] . '" name="' . $args['namearray'] . '[' . $args['name'] . ']" value="' . $args['textvalue'] . '"';

		if ( $args['maxlength'] ) {
			$value .= ' ' . $this->get_maxlength( $args['maxlength'] );
		}

		if ( $args['onblur'] ) {
			$value .= ' ' . $this->get_onblur( $args['onblur'] );
		}

		$value .= ' />';
		
		if ( $args['helptext_pos'] == 'after_input' ) {
			$value .= $this->get_help( $args['helptext'] );
		}
		$value .= '<br/>';

		if ( !empty( $args['aftertext'] ) )
			$value .= $args['aftertext'];

		if ( $args['wrap'] ) {
			$value .= $this->get_td_end();
			$value .= $this->get_tr_end();
		}

		return $value;
	}
```

**Comment by pedro-mendonca** [comment]
I'me testing **Option 2** and it works great, check it here:
https://github.com/WebDevStudios/custom-post-type-ui/compare/master...pedro-mendonca:master

Please ignore the diffs in *custom-post-type-ui.php* as they are from another issue.

**Comment by tw2113** [comment]
Marking as closed as it's in Master at this point.
