### ISSUE TITLE
1.0.6 causing 404 errors on CPT

### ISSUE THREAD

**Issue by petebarr** [WebDevStudios/custom-post-type-ui#276]
When I updated to 1.0.6 and flushed the permalinks one of my custom post types only shows 404s for the taxonomy-[name].php page. The built-in taxonomy even appeared to be deselected too.

**Comment by tw2113** [comment]
hmm. Sounds like a taxonomy term archive issues. Are you able to provide links or more information at all? or is it a private site still?

**Comment by petebarr** [comment]
The site is murphymulhall.ie but I had to roll back to the previous version of the plugin.

**Comment by petebarr** [comment]
Is there any particular information I can pass on to you?

**Comment by petebarr** [comment]
I just updated the plugin on another big site I'm developing and I'm getting exactly the same issue with the taxonomy archive page taxonomy-news-categories.php.

**Comment by tw2113** [comment]
Haven't had a chance to test things out locally yet due to some travel.

Can you use https://wordpress.org/plugins/show-template/ to see what template is getting chosen instead?

Ignore the "2 years old" bit, I know it's still valid and working as expected.

**Comment by tw2113** [comment]
What are the registered post types and taxonomies for the site linked above? Or perhaps the other site you mentioned 5 hours ago 

Also note that WordPress doesn't do an archive for all terms in a taxonomy, it sticks to just archives for each term.

**Comment by tw2113** [comment]
Push comes to shove, if you could send an export of your settings via the Import/Export page, I could try with your setup. I am not recreating on my own.

**Comment by petebarr** [comment]
Sorry, been under a lot of pressure. Just to let you know the same thing happened to a site a colleague was working on when the client updated the plugin to 1.0.7. He had to delete the Custom Rewrite Slug in the settings to get the taxonomies template to work again, but of course the URLs changed from optimal. I can send you an export of one of the sites if you'd prefer, a full export I presume? How would you like me to send that to you? Thanks :-)

**Comment by tw2113** [comment]
I'd prefer settings from the latest version available, because that's ultimately the version I want to get everyone onto.

Side questions. Did they try re-adding the custom rewrite slug after the initial deletion to see if it automagically worked afterwards?

The main things from 1.0.6 is the priority change for the registration of the post types and a removal of an empty check that was affecting old settings and returning false inaccurately. 1.0.7 had just some escaping of add_query_arg() results.

**Comment by petebarr** [comment]
Sorry I never got back to you with that. Mayhem here! Anyway, that update 1.0.8 fixed the issue so thanks very much indeed!!! :-)

**Comment by tw2113** [comment]
Awesome
