### ISSUE TITLE
wp-admin pagination bug

### ISSUE THREAD

**Issue by mihdan** [WebDevStudios/custom-post-type-ui#279]
If in custom post type set Hierarchical = true -> paginator not show

WP 4.1.2
CPT UI 1.0.7

**Comment by tw2113** [comment]
Pagination where? Admin? Frontend in your templates?

Not sure how pagination would be affected by the hierarchical topic either, but I'm willing to hear things out.

**Comment by mihdan** [comment]
In admin

**Comment by tw2113** [comment]
Where in the admin, the list of posts for the post type? Are you able to disable all other plugins and possibly activate one of the default themes to see if it's not an issue coming from somewhere else?

**Comment by mihdan** [comment]
http://c2n.me/3gDiPHk

**Comment by mihdan** [comment]
I use theme Twenty Fifteen

**Comment by tw2113** [comment]
Ah, switching between something like published posts vs drafts.

I'm not managing to recreate myself, using 1.0.7. I've tried with two different post types and both are set to hierarchical true

**Comment by mihdan** [comment]
My config:

```php
add_action( 'init', 'cptui_register_my_cpts' );
function cptui_register_my_cpts() {

	$labels = array(
		"name" => "Меню",
		"singular_name" => "Меню",
		"all_items" => "Все пункты",
		"add_new" => "Добавить пункт",
		"not_found" => "Пунктов меню не найдено",
	);

	$args = array(
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"show_ui" => true,
		"has_archive" => true,
		"show_in_menu" => true,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => true,
		"rewrite" => array( "slug" => "categories", "with_front" => true ),
		"query_var" => true,
		"menu_icon" => "dashicons-menu",		
                "supports" => array( "title", "thumbnail", "page-attributes" ),
		"taxonomies" => array( "product_cat" )	);
	register_post_type( "product_categories", $args );

// End of cptui_register_my_cpts()
}
```

**Comment by tw2113** [comment]
Still not managing to recreate even with your example above.

The only way I was able to get a difference in those 2 numbers is if I did a search in the post listing. The number on the right being different would be expected for me. It's only showing the 1 result for my search, but there's still X amount of overall posts.

**Comment by tw2113** [comment]
Any update on this one @mihdan ?
