### ISSUE TITLE
404 Errors

### ISSUE THREAD

**Issue by blwoosky** [WebDevStudios/custom-post-type-ui#282]
HI ,tw2113
 I updated to  WordPress 4.2,when i go to a custom taxonomy page,it appeared 404 errors,here is the page:http://digcss.com/snippets/tag/javascript/

you can visit http://digcss.com/snippets ,then click the " 按标签查看"

**Comment by tw2113** [comment]
Have you tried refreshed your permalinks yet?

**Comment by blwoosky** [comment]
yeah ,i did that ,but it does'nt work.

**Comment by tw2113** [comment]
Just to confirm, you went to version 1.0.7, correct?

As a second option, can you try editing and saving the taxonomies without changing any of the settings. See if that helps at all.

**Comment by blwoosky** [comment]
yes ,my CPT UI is version 1.0.7，
sorry ,my english i s not ok,but I probably understand what you mean ,you mean that i will do is to modify the functions.php file?i did this yesterday,but it does'nt work too,
maybe this is issue is caused by the wordpress 4.2

**Comment by tw2113** [comment]
No editing of a functions.php file. Using our plugin to edit each taxonomy you have registered. Click to edit each one, and hit save right away. Don't edit the settings previously set, just hit save.

I don't believe there's anything from 4.2 that would affect this, but I'd need to try todo my own testing to absolutely confirm. I think it's more "woes" that I've seen from upgrading CPTUI from 0.9.x to 1.0.x, and not from WP core.

**Comment by blwoosky** [comment]
ok,thanks a lot ,you do a great job!

**Comment by tw2113** [comment]
Did your issue get solved? or are you still trying to work out the issue?

**Comment by blwoosky** [comment]
I haven't solved the problem yet .

**Comment by blwoosky** [comment]
tw2113,thanks!!,i updated my CPT ,and it works!,you are so good!
