### ISSUE TITLE
Edit post types select box does not allow selection of post type

### ISSUE THREAD

**Issue by tomcowle** [WebDevStudios/custom-post-type-ui#305]
Just updated to 1.1.0. When I go to Edit a post type the form is pre-loaded with the values of my first CPT. When I use the 'Select:' box and change the post type, the form does not update - there is no way therefore to edit any CPT other than the first one.
![1](https://cloud.githubusercontent.com/assets/767368/8156770/4364682c-1347-11e5-9d55-b38decf773ef.PNG)
![2](https://cloud.githubusercontent.com/assets/767368/8156771/43652b40-1347-11e5-9c64-b3aa08c19d61.PNG)

**Comment by tomcowle** [comment]
Ooops - I guess this was to do with a cached JS file - a hard refresh sorted this out - my bad.

**Comment by tw2113** [comment]
Good to know the fix was that simple :)

Any issues other than that with 1.1.0 or has it been a pretty seamless upgrade?

**Comment by tomcowle** [comment]
Seamless :)

Thanks,

Tom
