### ISSUE TITLE
Bug: Can't select taxonomy to edit

### ISSUE THREAD

**Issue by zerodburn** [WebDevStudios/custom-post-type-ui#306]
Hi,

I upgraded to 1.1.0 today and now I don't have a `select` button after the dropdown menu when editing a taxonomy. Rolling back to 1.0.8 fixed it for me. I use a Win 8.1 touchscreen laptop, maybe something to do with it?

**Comment by tw2113** [comment]
Are you not getting switched automatically after selecting the taxonomy you want to edit? It's one of the changes I made where it auto-triggers the submit action to edit the newly selected dropdown item, which I figured made the select button extra and not needed. However, from your experiences, that may not be the case in certain situations.

**Comment by zerodburn** [comment]
Apparently not, I'm using Windows 8.1 and Chrome latest - Version 43.0.2357.124 m. I didn't see any console errors.

I'm happy to help debug another time but right now I need to finish this project so need to work on v1.0.8.

**Comment by tw2113** [comment]
There's nothing critical that I can recall in 1.1.0, other than if you absolutely loathed the original 1.0.x UI revamp.

Definitely leaving this thread open though. Thanks Patrick.

**Comment by zerodburn** [comment]
No problems, I like this plugin and I actually think the UI revamp has been great, less clicks make sense. However, if I can't edit a taxonomy then I can't really use it. Perhaps a temporary solution would be just to leave the select button there for now, in case other users on other browsers experience the same problem.

**Comment by tw2113** [comment]
My question, upon a bit more reflection, is if perhaps the old js is still cached and doesn't have the new js code to auto-switch.

May be something to try on a different install if you have time.

**Comment by tomcowle** [comment]
Yes, please see my closed issue here: https://github.com/WebDevStudios/custom-post-type-ui/issues/305 - pretty sure this is the same 'issue' - hard refresh and go guys :)

**Comment by zerodburn** [comment]
It seems to work now! Cheers.

**Comment by tw2113** [comment]
Still proved worth opening @zerodburn as it did make me realize that we weren't no-js friendly, so that's what 1.1.1 will be about. Re-adding the button and hiding for js-ready people, and providing it when not
