### ISSUE TITLE
Add meta_box_cb support for taxonomies

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#311]
4.2+

```
show_in_quick_edit
    (boolean) (optional) Whether to show the taxonomy in the quick/bulk edit panel. (Available since 4.2)

        Default: if not set, defaults to value of show_ui argument 
```

3.8+

```
meta_box_cb
    (callback) (optional) Provide a callback function name for the meta box display. (Available since 3.8)

        Default: null 

Note: Defaults to the categories meta box (post_categories_meta_box() in meta-boxes.php) for hierarchical taxonomies and the tags meta box (post_tags_meta_box()) for non-hierarchical taxonomies. No meta box is shown if set to false.
```

**Comment by tw2113** [comment]
Need to make sure to test how the meta_box_cb field works. Needs both a bool select input as well as a text field to provide the callback function name.

**Comment by ejwarden** [comment]
+1

**Comment by tw2113** [comment]
Going to bump to 1.3.0. I want 1.2.0 out the door.

**Comment by tw2113** [comment]
Hold until we've migrated the taxonomy UI to v2

**Comment by tw2113** [comment]
Good to work on.

**Comment by tw2113** [comment]
Show in Quick Edit added. meta_box_cb pending.

**Comment by tw2113** [comment]
Going to halt at the Quick Edit parameter. If someone is getting to the point of providing their own metabox, they aren't likely needing our plugin, and if they are, then we can help with the edge case and with the filters already in place.

**Comment by mrgnou** [comment]
Setting meta_box_cb to false could be very useful using ACF, allowing to keep the taxonomy in the main menu, but removing it from the post for a better control.

**Comment by tw2113** [comment]
Valid point. At least for the time being, this filter should get you far enough: https://github.com/WebDevStudios/custom-post-type-ui/blob/master/custom-post-type-ui.php#L580-L590 It'd be the same structure as the array you create when manually registering, just need to set the key and set the value to false, before returning.

**Comment by mrgnou** [comment]
Indeed. that works for me.

**Comment by tw2113** [comment]
More requests.

https://wordpress.org/support/topic/feature-request-546/

**Comment by garrett-eclipse** [comment]
I second @mrgnou it's very handy as a way to disable the default GUI for ACF. Right now using the filter. *Commented mainly to follow this issue

**Comment by tw2113** [comment]
Added in ba91084

**Comment by garrett-eclipse** [comment]
Thanks @tw2113

**Comment by robwent** [comment]
What is this option labelled as?

I can't find an option to not show the meta box on the edit screen.

**Comment by tw2113** [comment]
Correct, it's for 1.6.0 which we haven't finished up yet.

**Comment by robwent** [comment]
Yep, got it installed and working great for me. I just added `false` to the callback field.

**Comment by tw2113** [comment]
Related, I appreciate the help testing 1.6.0 ahead of time :D

**Comment by robwent** [comment]
It seems like this doesn't work when using gutenberg.
Related issue here: https://github.com/WordPress/gutenberg/issues/13816

**Comment by tw2113** [comment]
Yep, it'll be fine still for classic editor based cases, but until Gutenberg becomes default for everything, everyone, and consumes the WP Admin, this is the best we can do.
