### ISSUE TITLE
custom post type vanished after plugin update

### ISSUE THREAD

**Issue by RealDavidoff** [WebDevStudios/custom-post-type-ui#321]
Hi Michael, 
first thanks so much for the plugin which works great when it works!
Now, at the moment unfortunately it doesn't work anymore, and precisely since the update to your latest release.

To be frank, in all past years I've not dared to update this plugin as "no-worries" as I do with other plugins, because everytime I do update it, I run into trouble.

Normally, your two rules did help:
Items that have worked with varying success:
    Flush your permalink rewrite rules by visiting your Permalinks page.
    Edit each post type/taxonomy settings after the version update and save without making any changes.

I never knew what you mean with "flush permalinks" (there is no such function in my wp), but I usually just saved a different permalink structure and then back to my original.
Likewise, I usually just re-saved the one custom post type we use, and then it was working again.

Not so this time. :-(
I've done all that, yet I still can't get to see the post type in the admin menu (hence I cannot see how to access and edit such pages!!) and when I view one such page, there isn't the typical "edit" button anymore at the top of the browser window.

Would you be able to pinpoint me what to do to get it work again?

If not, I will try to revert to backup files of an earlier version of your plugin. That would still work, right?

**Comment by tw2113** [comment]
Can you check the settings for the post types and make sure things like "show in menu" and "public" are still set to true?

Do you have a dev copy of the site where you could disable plugins? Some rare times, menu position ends up being the same somehow and possibly other things are occupying the same spot.

Worst case, would you be willing to let me in to the website via a new temporary admin user so that I could check things myself?

**Comment by tw2113** [comment]
Also, are they all still showing on the frontend like expected? leaving it to be just an admin-area issue?

**Comment by RealDavidoff** [comment]
Hoh you are quick, thank you SO MUCH!!
Well, the issue is bigger than initially visible: I found a trick to get to the "invisible" custom post type edit screen, and while excerpt, seo, publish, page attributes and all that crap shows up, the needed EDIT part is missing, so now we can't even EDIT our "Periodical" custom post type posts anymore :-(
Urgent help much appreciated!

Yeah, you are right the error seems to be restricted to wp admin, because the published Periodicals (pages) can still be reached. Very strange.

I checked again the settings you mention, and it's all correct. But in wp admin I cannot get to see the post type anymore! :-(

As it's mega urgent now, I would love to give you admin access despite company policy, but I can't post the login here!! Would you have an email address, or do you have an idea how I can fix the issue myself?

Oh note: I DID try the old version (ftp-ed it onto server), but odd enough with that one I now can't see the post type either! So then I deactivated recent plugins, but still no luck. Now I am at my wits end (but I am no programmer anyway)...

**Comment by RealDavidoff** [comment]
Michael, hold on, THIS MOMENT I got them back!!!!!!
Before I had deactivated plugins individually (because it's a productive memberhsip site), but being at wits end I briefly(!) deactivated all, started with yours again, now I see them!!

Then I even updated again to your newest version to see it, and yeah now the show with that version as well!

I have no idea why we had such trouble, and am sorry to bother you, but at least it's working again, right? :-))

So let's make this helpful to you: I have a suggestion to improve it, minimalst work for you, promise: 
Under LABELS, the help texts 2 to 13 all show the same. That is of no help. ;-) To be frank, to this day, I haven't understood the right side much, it ended up in "hit and miss", trial and error, for us.
Eg under LABELS we never had anything in there, but your plugin worked nonetheless! And "show in menu" has always been false (we don't want to show this post type in the site menu as it's for subscribers only), and again, your plugin worked nonetheless! :-)

**Comment by RealDavidoff** [comment]
Well, now I am going mad here! Suddenly the post type is missing again!!
This is crazy. Any idea what I need to do to ALWAYS keep in visible in the wp admin menu (and the top bar) ??

**Comment by tw2113** [comment]
I don't have an answer because this is very erratic behavior that I haven't seen before, so I don't have a great "do this and this and this" bit.

michael @ webdevstudios dot com will reach me. I wouldn't request you post the credentials here regardless. I'd have you simply create a new user for me.

**Comment by RealDavidoff** [comment]
Yes very erratic indeed. I got it back visible now (although I wouldn't be able to explain how!), but I'd like to suggest this: With every site change I will now look whether the post type diappears in admin menu, and if it does again, I'll have a record upon what action, and will tell you here.

I wouldn't want to waste your time further at this moment where the post type IS visible (you couldn't make it MORE visible now), rather when/ if it is NOT visible. 

Hope you agree with my suggestion.
Thanks again for a GREAT plugin, when it works it works brilliant Michael!

**Comment by tw2113** [comment]
Up to you. I'm willing to still take a peak if you're willing to let me. However, I won't force you.

**Comment by RealDavidoff** [comment]
Thanks Michael. There's nothing to fix at this moment it works :-)

**Comment by tw2113** [comment]
Alrighty.
