### ISSUE TITLE
Will not delete post type

### ISSUE THREAD

**Issue by agstew** [WebDevStudios/custom-post-type-ui#327]
Will not delete post type. After clicking delete it ask you to choose a post type to delete . Even if you have chosen a post type to delete already.

**Comment by tw2113** [comment]
does your post type slug have accents or a space in them?

**Comment by agstew** [comment]
A space

**Comment by agstew** [comment]
Now I have three on them

**Comment by tw2113** [comment]
I'd use the import/export functionality to grab the settings, and replace the spaces with either an underscore, or a dash, and then re-import. This will overwrite the setting with the spaces removed, which is what's throwing things awry.

If you have post type posts that have the space in them, I recommend using http://wordpress.org/plugins/post-type-switcher to switch them to the new version without.

Post type and taxonomy slugs aren't supposed to have spaces. This comes from WordPress core and not just our plugin.

Hope that all helps.

**Comment by agstew** [comment]
Still unable to delete

**Comment by tw2113** [comment]
make a gist of the export content and let me know which ones you want removed

**Comment by agstew** [comment]
I'm so new I don't know what that is a "gist". Is that a copy?

**Comment by agstew** [comment]
And by the way Thank you for your help

**Comment by tw2113** [comment]
https://gist.github.com/

Copy/paste the export contents into the textarea above, click one of the two create buttons at the bottom, and then share the URL with me.

Gists are a github thing.

**Comment by agstew** [comment]
Thank You for your help, I saw a few more places where the name was wrong and I replace it like you said, then I was able to remove the extra one from the dashboard thank you.

**Comment by tw2113** [comment]
Awesome, sounds like you're good to go now.

**Comment by agstew** [comment]
Worked like a charm
