### ISSUE TITLE
Import/Export - Get Code outputs three html block notices in the cpt ui taxonomy pane 

### ISSUE THREAD

**Issue by rpkoller** [WebDevStudios/custom-post-type-ui#332]
Hi. Today i wanted to export my post types and taxonomies. So i went to import/export and the get code pane. there in the cpt ui taxonomy pane before each label and argument block a block of html notices shows up: 

```html
<br />
<b>Notice</b>:  Undefined index: object_types in <b>/Applications/MAMP/htdocs/mypage/wp-content/plugins/custom-post-type-ui/inc/import_export.php</b> on line <b>158</b><br />
<br />
<b>Notice</b>:  Undefined index: rewrite_withfront in <b>/Applications/MAMP/htdocs/mypage/wp-content/plugins/custom-post-type-ui/inc/import_export.php</b> on line <b>171</b><br />
<br />
<b>Notice</b>:  Undefined index: rewrite_withfront in <b>/Applications/MAMP/htdocs/mypage/wp-content/plugins/custom-post-type-ui/inc/import_export.php</b> on line <b>182</b><br />
```

Happened with CPT UI 1.1.2 and WordPress 4.3. Best regards r.

**Comment by tw2113** [comment]
Can you test with 1.2 branch? I'm not seeing it occur, though I also don't have the same data. The rewrite ones likely stem from #275

**Comment by tw2113** [comment]
Gonna close. We can address later in a bug fix if necessary.
