### ISSUE TITLE
Pages missing from admin 

### ISSUE THREAD

**Issue by myrafletcher** [WebDevStudios/custom-post-type-ui#334]
There are now pages missing from my All Pages admin area so I cannot edit them, the page names show under the pages type menu. How do I fix this?

**Comment by tw2113** [comment]
hi @myrafletcher. Could you please start a support thread over at https://wordpress.org/support/plugin/custom-post-type-ui for this? We aim to keep the GitHub issue tracker for confirmed bugs and enhancement ideas.

To help start you off with the initial thread, if you could determine if the edit abilities return when you don't have any post types registered via our plugin, as well as provide the value found in the import/export area for the post types, that would help get things started. We'll be able to begin debugging at that point.
