### ISSUE TITLE
Missing show_in_nav_menus field.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#341]

**Comment by oskarrough** [comment]
also `show_in_rest` and `rest_base` would be great as they are used with WP-API.

**Comment by tw2113** [comment]
At least one of those is in the 1.2.0 branch already, but will check to
make sure both are

**Comment by tw2113** [comment]
Need to add rest_base to post types, need to add both to taxonomies.

**Comment by tw2113** [comment]
All are added in the 1.2 branch.
