### ISSUE TITLE
Add field for taxonomy description

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#347]

**Comment by tw2113** [comment]
Added in 1.2 branch

**Comment by brandondurham** [comment]
Great! I came here to ask if I could help add this feature. Really needing it.

How do I use the 1.2 branch today?

**Comment by brandondurham** [comment]
Ha! I JUST went to the plugin section of my install and saw this: http://cloud.smallparade.com/em4H

**Comment by tw2113** [comment]
as a FYI @brandondurham there are also filters on the arguments right before the registration of both post types and taxonomies, in case you need to add something that isn't provided yet by the UI aspect of our plugin.
