### ISSUE TITLE
CMB2 Support

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#351]
We have two awesome plugins that are very powerful. How can we intertwine them?

FAQ section if not already mentioned.

Other ideas.

Discuss.

**Comment by modemlooper** [comment]
Include cmb and create ui for adding meta fields

**Comment by tw2113** [comment]
CPTUIExtended has this available in itself for its own options/setup.

**Comment by tw2113** [comment]
CMB2-based plugin that integrates with CPTUI?

**Comment by tw2113** [comment]
I'm going to nix this one. If someone comes up with a killer idea, we can create an issue for that specific one at that time.
