### ISSUE TITLE
adding taxonomy tag when editing post dispalyed twice

### ISSUE THREAD

**Issue by flexphperia** [WebDevStudios/custom-post-type-ui#362]
When I add taxonomy tag on post edition screen all tags it's displayed twice.
After page refresh duplicate entries dissapears.
It's only happens when used with WPML plugin.

**Comment by tw2113** [comment]
Honestly sounds like something that should be taken up with WPML people. We're not doing anything special that would cause this type of thing. Nor are we doing anything specific on any post editor screen other than making sure the taxonomy is registered for your use.

Wish I could be more help.
