### ISSUE TITLE
Custom post type appears only super admin role.

### ISSUE THREAD

**Issue by eminarslan** [WebDevStudios/custom-post-type-ui#363]
I'am using this plugin in multisite. I've created **Ürünler** (*Produts*) custom post type. But appears only super admin page.

**Super Admin** Role | **Admin** Role
------------ | -------------
<img width="198" alt="screen shot 2015-11-17 at 14 43 19" src="https://cloud.githubusercontent.com/assets/1017435/11211703/ffa284a8-8d39-11e5-98ab-4ce42d03c6a5.png"> | <img width="171" alt="screen shot 2015-11-17 at 14 44 51" src="https://cloud.githubusercontent.com/assets/1017435/11211707/029b95f0-8d3a-11e5-9e26-82295a808bca.png">

<img width="301" alt="screen shot 2015-11-17 at 14 57 27" src="https://cloud.githubusercontent.com/assets/1017435/11211937/94ec1be0-8d3b-11e5-952d-bf51636755f8.png">

Wordpress version 4.3.1

Active plugins on the site: Advanced Custom Fields Pro 5.3.2.2, Multisite Language Switcher 1.0.4, Contact Form 7 4.3

**Comment by tw2113** [comment]
By super admin page, you're referring to the Network area for a multisite?

Are you accessing the CPTUI menu from the network area instead of through one of the subsites?

Just trying to gather some information to help me look into what's going on.

**Comment by tw2113** [comment]
Not managing to recreate with a pretty bare network setup. Can you confirm if it happens with all other plugins disabled?

**Comment by eminarslan** [comment]
**1 -** My bad. Actually it was to be **Role**, not **Page**.

![superadmin](https://cloud.githubusercontent.com/assets/1017435/11219972/18854cd6-8d66-11e5-9889-68006bcf4de0.jpg)

**2 -** In both subsites, I (and all admins) can access CPTUI options page.

![users](https://cloud.githubusercontent.com/assets/1017435/11220151/2b1d91a4-8d67-11e5-88b8-e5f8a47deb03.png)

**3 -** All plugins were inactivated except CPTUI. Still same.

**Comment by tw2113** [comment]
So essentially it's a case of only super admins are able to see and create posts in the created post types? Like mentioned before, trying to nail down the specifics so I can best look into it.

**Comment by eminarslan** [comment]
If you wish, I can setup test wordpress multisite network on digitalocean, and I can send you access information right now (via email).

**Comment by tw2113** [comment]
Sure, if you're willing. Set up an account for michael@webdevstudios.com

**Comment by eminarslan** [comment]
E-mail has been sent.

**Comment by tw2113** [comment]
Finally tracked it down. The custom capability type that you're setting. It's working fine for the Super admin, but it is not a capability available to admins. Once I changed that back to the default "post" the menu item showed up just fine for the regular admin.

Is that something you're purposely setting for what you have in mind for the site? or just something you thought you needed to edit? When in doubt, best to leave that setting alone, and I believe I have a ticket open to help customize when specifying new capabilities.

Feel free to comment more, but I'm going to close as it's not a bug in the end.
