### ISSUE TITLE
Problems deleting post types

### ISSUE THREAD

**Issue by HoneyR** [WebDevStudios/custom-post-type-ui#367]
Hi, 

I'm having a hard time deleting post types. I select the post type from the dropdown and hit the delete button, but it doesn't delete. I think it may have to do with the fact that when creating the slugs for the post types I added a space between words. The single word slugs have all been deleted successfully. 

Could you please help me out?

**Comment by tw2113** [comment]
Use the import/export section to grab the data and replace the spaces with an underscore, and then re-import with those changes. Once that's done, you should be able to delete them fine.
