### ISSUE TITLE
#excerpt styles are overwritten by load-styles.php

### ISSUE THREAD

**Issue by RichyVN** [WebDevStudios/custom-post-type-ui#386]
The style for the input with the id #excerpt in the backend file: /wp-admin/admin.php?page=cptui_manage_post_types.php is being overwritten by a file called load-styles.php and therefor the label floating to the right of this element is not being displayed correctly.
I have edited the following rule in the cptui.css file as follows:

.cptui-table #excerpt { 
	display: inline-block!important;
	height: 16px!important; 	
	margin: 0 4px 0 0!important; 
	width: auto!important;
}

That solved it for me. 
Not sure if its just my theme but just noticed it!!

Regards
Richard

**Comment by tw2113** [comment]
Can you screenshot what you saw for it before you applied your !important css fixes?

**Comment by RichyVN** [comment]
Hi Michael,

Here’s a screenshot including Firebug console screen open.

[cid:image002.png@01D1574D.887E1E40]

Best regards,
Richard van Naamen


Van: Michael Beckwith [mailto:notifications@github.com]
Verzonden: vrijdag 22 januari 2016 17:10
Aan: WebDevStudios/custom-post-type-ui <custom-post-type-ui@noreply.github.com>
CC: vanmen <vanmen1@gmail.com>
Onderwerp: Re: [custom-post-type-ui] #excerpt styles are overwritten by load-styles.php (#386)


Can you screenshot what you saw for it before you applied your !important css fixes?

—
Reply to this email directly or view it on GitHub<https://github.com/WebDevStudios/custom-post-type-ui/issues/386#issuecomment-173963941>.


Click here<https://www.mailcontrol.com/sr/MZbqvYs5QwJvpeaetUwhCQ==> to report this email as spam.

________________________________

Append the message with the disclaimer 'Rotterdam Short Sea Terminals B.V. (further: “RST B.V.”) is established in Rotterdam and registered at the Rotterdam Chamber of Commerce under Nr. 24116222. Where we are a provider of services or goods, to all our quotations, to all contracts concluded with us and to all services rendered and goods provided by us exclusively the Rotterdam Stevedore Conditions 1976 (in Dutch: de Algemene Voorwaarden van de Vereniging van Rotterdamse Stuwadoors) apply as deposited with the Registrar of the Rotterdam court on 12 August 1976, which conditions contain an arbitration clause providing for arbitration in Rotterdam, Dutch law to apply and limitation of liability clauses. Where we purchase services or goods solely our General Purchase Conditions shall apply. Copies of the Rotterdam Stevedore Conditions 1976 (“RSC 1976”) and of our General Purchase Conditions (“GPC”) are available at our office and will be sent to you free of charge upon your first request. Also, the RSC 1976 and our GPC can be downloaded from our website www.rstshortsea.nl. In case of doubt or uncertainty whether the RSC 1976 or our GPC apply, RST B.V. can decide which of those general terms and conditions apply. We explicitly reject any and all general terms and conditions (“GTC”) used by our contractual counterparties, unless we have explicitly agreed in writing with the applicability of such other GTC of our contractual counterparties. This email is strictly confidential and may also be legally privileged. If you are not the intended addressee please do not read, print, re-transmit, store or act in reliance on it or any attachments. Instead, please email it back to the sender and then immediately permanently delete it.'. If the disclaimer can't be applied, attach the message to a new disclaimer message.


This message has been scanned for malware by Websense. www.websense.com

**Comment by RichyVN** [comment]
Not sure if the screenshot I uploaded worked because its not showing up in previous comment.

![Uploading 2016-01-25_8-49-10.jpg…]()

regards.

**Comment by RichyVN** [comment]
Oops. Clicked the wrong button ;-)

**Comment by tw2113** [comment]
Not showing in any of the replies. Perhaps add it via the GitHub issue itself, and not via an email reply attempt.

**Comment by RichyVN** [comment]
Wierd... I have tried that as well. didn't work. The application says its uploading a file but then it hangs up... ?? I have put up an image in my dropbox shared folder:
https://www.dropbox.com/s/yet820zcb9wnc6r/2016-01-25_8-49-10.jpg?dl=0

Hope this will work!
Regards

**Comment by tw2113** [comment]
![screen shot 2016-01-26 at 10 52 15 am](https://cloud.githubusercontent.com/assets/484075/12587659/e62f74d2-c41a-11e5-9c45-5f6b5cdd700c.png)
Screenshot for posterity

**Comment by tw2113** [comment]
Ah yeah, I recall seeing this in the past, but fairly insignificant of a bug too. Not going to close this one, but not in any immediate rush to fix. I need to find a way to better specify my selector, as I like to avoid !important.

**Comment by tw2113** [comment]
Added some extra styles in 1.3.0 branch that should help resolve this one overall.
