### ISSUE TITLE
dashicons-before is wrong size

### ISSUE THREAD

**Issue by clernoc** [WebDevStudios/custom-post-type-ui#394]
Hello, I have updated plug-in and it replaced default CPT UI icon in left WP admin menu. As I understand, you have tried to use modern svg style to make an icon, but you set wrong dimensions to SVG. As a result users have monstrous 48*48 icon in menu. Please convert 16*16 icon of add style which reduce height to 16px in default WP admin style.

**Comment by tw2113** [comment]
Its a paste typo with spaces in the css properties. Busy with family this
afternoon and planning to push out a fix this evening.

On Saturday, January 30, 2016, clernoc <notifications@github.com> wrote:

> Hello, I have updated plug-in and it replaced default CPT UI icon in left
> WP admin menu to that:
>
> As I understand, you have tried to use modern svg style of iconing, but
> set wrong dimensions to SVG As a result users have monstrous 48*48 icon
> in menu Please convert 16*16 icon
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebDevStudios/custom-post-type-ui/issues/394>.
>


-- 
~Michael
http://michaelbox.net

**Comment by tw2113** [comment]
Issue is fixed in 1.2.3
