### ISSUE TITLE
1.2.3 causes wp-admin pages to fail loading

### ISSUE THREAD

**Issue by cdharrison** [WebDevStudios/custom-post-type-ui#396]
No specific errors to report, but after updating to CPT-UI 1.2.3 wp-admin pages no longer fully load. I'm running WordPress 4.4.1; PHP version 5.3.29. (Is it possible recent changes to the plugin require a newer version of PHP?)

**Comment by tw2113** [comment]
No, we still aim for a minimum of PHP 5.2.x

Since the release of 1.2.0, all the changes have been related to undefined index notices, or css/admin icons, so not really much to do with PHP itself other than some extra empty() checks.

Could you provide more details about "no longer fully loading" ? Stylesheets not loading and most of the page is white except for the content for the page being loaded?

**Comment by cdharrison** [comment]
div#adminmenumain is the last and only viewable element to render. Specifically Settings > Discussion is the last menu item to render and then it chokes.

**Comment by tw2113** [comment]
Have you enabled WP_DEBUG to see if that provides any good information about what's going on and encountered errors? Nothing like that should be occurring with the point releases from CPTUI.

**Comment by cdharrison** [comment]
Yes, and it's only showing me errors about WP_Widget being deprecated since 4.3.0. (I've got to update some calls in my theme.)

`[02-Feb-2016 17:34:45 UTC] PHP Notice:  The called constructor method for WP_Widget is <strong>deprecated</strong> since version 4.3.0! Use <pre>__construct()</pre> instead. in /home/hcity/public_html/wp-includes/functions.php on line 3624`

**Comment by tw2113** [comment]
Willing to install a previous version to see if it clears up?

https://downloads.wordpress.org/plugin/custom-post-type-ui.1.2.1.zip

**Comment by cdharrison** [comment]
1.2.1 definitely works. And I tried the 1.30 svg fix you posted on wp.org within the past day or so, and it's causing the same issue.

**Comment by tw2113** [comment]
Can you also provide some screenshots? What browser? OSX or Windows?

**Comment by tw2113** [comment]
That 1.3.0 svg fix was a mixup in me branching from the future version. The same changes were made in the point release, relevant to the bugs trying to be fixed.

**Comment by cdharrison** [comment]
(For what it's worth, the issue happens in 1.2.2 as well.) I'm using OS X 10.10.5. Latest Chrome stable (48.0.2564.97) and Safari 9.0.3. Same issue happens in both.

![screen shot 2016-02-02 at 1 22 56 pm](https://cloud.githubusercontent.com/assets/210943/12759632/3038ccb4-c9b0-11e5-9482-dc21a1f36cea.png)

**Comment by tw2113** [comment]
Are you willing to temporarily let me into the site, if possible? Curious why it's going on, when I have the same versions and not getting the same results.

**Comment by cdharrison** [comment]
@tw2113 If I could give you access, I absolutely would. What's bizarre is it's not generating any discernable errors at all. I just tried installing the plugin on a site/server I have more control over and it seems to be working fine. Going to chalk this up to something potentially misconfigured server-side. Will escalate to our server admin and see what/if anything they can narrow down.

I really appreciate your help.

**Comment by tw2113** [comment]
See if the last change in https://github.com/WebDevStudios/custom-post-type-ui/commit/158beae70eb89de9214935e57889170597872aa6 fixes it in your case.

Disregard the css change at the top.

Note that it was a case of changing:
```
return 'data:image/svg+xml;base64,
```
to
```
return 'data:image/svg;base64,
```
So I'm curious if that +xml removal is causing the issue somehow. Also wonder if somehow the base64 encoding/decoding for the site in question is giving silent fatal errors or something.

**Comment by cdharrison** [comment]
Yep. I manually added +xml and pages will now fully load with 1.2.3 but the icon doesn't display. Odd.

**Comment by tw2113** [comment]
Good to know it has the potential to happen. May make for some interesting debugging situations.

**Comment by tw2113** [comment]
Going to close this one until we have any new reports of issues. It feels like an extreme edge case.
