### ISSUE TITLE
Wordpress Menu Icon Over Sized

### ISSUE THREAD

**Issue by craigpryde** [WebDevStudios/custom-post-type-ui#397]
The Wordpress Menu Icon Has Become Oversized Since The Last Update
![screenshot at feb 03 21-38-49](https://cloud.githubusercontent.com/assets/8403372/12797934/8d0674d2-cabe-11e5-947e-4601c2e0a07e.png)

**Comment by tw2113** [comment]
Should be fixed already in 1.2.3. It was introduced in 1.2.2. Clear your browser cache for the admin to help ensure that you get the latest copy of the CSS.
