### ISSUE TITLE
Break after Update

### ISSUE THREAD

**Issue by Horan93** [WebDevStudios/custom-post-type-ui#398]
The issue I am having is a weird one, before the update I could write content for these custom posts but now as you can see in the screenshot, this option has disappeared 
![openapp_cui_bug](https://cloud.githubusercontent.com/assets/11921653/12842808/01e84d0a-cbed-11e5-92f0-78f58682a900.png)

**Comment by Horan93** [comment]
Issue Resolved

**Comment by tw2113** [comment]
What was the issue? Shouldn't have been anything with our plugin, as we don't do anything with meta boxes.
