### ISSUE TITLE
Sidebar icon on retina screens display glitch

### ISSUE THREAD

**Issue by FourTeeTwo** [WebDevStudios/custom-post-type-ui#402]
Since upgrading to 1.2.3, when viewed on retina screens, the icon seems to be too big compared to other sidebar nav icons.

<img width="184" alt="screen shot 2016-02-12 at 08 18 46" src="https://cloud.githubusercontent.com/assets/7370800/13001860/d3f00f58-d161-11e5-8b9b-4e3b42fddb4a.png">

**Comment by tw2113** [comment]
Need to clear your CSS cache for the admin. 1.2.3 had the fix for the large icon that 1.2.2 introduced.

**Comment by tw2113** [comment]
Let me know if/when you confirm it going back down in size.

**Comment by FourTeeTwo** [comment]
Yep - all sorted now. Thanks!

Toby Pestridge
Creative Director
 <http://www.createful.com/>
toby@createful.com <mailto:toby@createful.com> • 01202 551667 • www.createful.com <http://www.createful.com/>
 <http://www.fb.com/createful/> <http://www.linkedin.com/company/826996> <http://www.twitter.com/createful/>

**Comment by tw2113** [comment]
Excellent
