### ISSUE TITLE
Isssue with custom post type posts

### ISSUE THREAD

**Issue by yourshadow909** [WebDevStudios/custom-post-type-ui#410]
Hi guys
Looks like I have an issue with… let me explain
I have 2 different(separate) post types:
events (created by EventON plugin)
news (created by me with “Custom Post Type UI” plugin)

when Im trying to share "news" post
http://www.webdonsk.ru/news/kalyan-na-fruktovoj-chashe/
it adds pictures from "events" to post! I dont know how!
![screenshot_10](https://cloud.githubusercontent.com/assets/17303109/13126036/f3e51a98-d5d9-11e5-9272-fff329707fff.png)

guys from EventOn cant help me, they said this is not their fault

**Comment by yourshadow909** [comment]
ok but I can't attach screenshots there

**Comment by yourshadow909** [comment]
done, you can close this ticket here

**Comment by tw2113** [comment]
Thank you. I'll keep the screenshots in mind above, but often I'll request them either shared via various image services, or direct email at the time, which I provide an address for.
