### ISSUE TITLE
Cannot delete a post type when there are spaces in slug, e.g. 'men fashion', 'my cute house'...

### ISSUE THREAD

**Issue by phannam1412** [WebDevStudios/custom-post-type-ui#431]
Steps to reproduce:
1. Add a new post type with slug = 'men fashion'
2. Go to the post type edit page /wp-admin/admin.php?page=cptui_manage_post_types&action=edit
3. Select and delete the post type 'men fashion'
4. Error: Please provide a post type to delete

**Comment by tw2113** [comment]
Use the import/export post types tab to fix this.

1. Copy the right side data.
2. Paste it into the left side.
3. Fill in the space with an underscore or dash
4. click the import button.
5. Return to Edit Post Type tab.
6. Select "Men Fashion" from the dropdown
7. Delete like expected.

Post types aren't supposed to have spaces in their slugs, and 1.3.0 is going to be forcing no spaces as well. I tried making this clear in the starter notes, but people still kept putting them in, so we're going to take a more proactive approach going forward. The "bug" comes from index keys not matching like they should in the settings.
