### ISSUE TITLE
WP Rest API issue with getting the category post data

### ISSUE THREAD

**Issue by tottaz** [WebDevStudios/custom-post-type-ui#435]
Hi,

Great plugin, really like the functionality. I'm using ACF to create a new custom post type for recipes, I have set it up and configured all working fine in WP-ADMIN. I also building a Mobile APP that uses the WP API v2 to get data from the WP backend.

I can get all the entries I have created with 
http://thelonelycyclist.org/wp-json/wp/v2/recipes?recipes

No problems I also can get a list of all the categories I created for the recipes post type
http://thelonelycyclist.org/wp-json/wp/v2/recipe_categories

In the categories output I get details on 

```
"_links": {
"self": [1]
0:  {
"href": "http://thelonelycyclist.org/wp-json/wp/v2/recipe_categories/335"
}-
-
"collection": [1]
0:  {
"href": "http://thelonelycyclist.org/wp-json/wp/v2/recipe_categories"
}-
-
"about": [1]
0:  {
"href": "http://thelonelycyclist.org/wp-json/wp/v2/taxonomies/recipe_category"
}-
-
"http://api.w.org/v2/post_type": [1]
0:  {
"href": "http://thelonelycyclist.org/wp-json/wp/v2/recipes?recipe_categories=335"
}
```

My requirement is to get all the recipes for a specific category - I used this API url call
http://thelonelycyclist.org/wp-json/wp/v2/recipes?recipe_categories=335

The problem is that it do not work, it does not matter what recipe_categories= <id> I put it always shows the same data. 

SO, I'm held up in my project due to this, I wonder how would you query only post in a custom post type by a category?

**Comment by tw2113** [comment]
This is really more a WP REST API question than one related directly to our CPTUI question, honestly. As long as you're able to successfully query for post type data from post types registered with CPTUI, then our job is done. After that, CPTUI is hands off with everything regarding usage.

I don't have very much hands on experience with using the WP REST API either, or else I'd try to help a bit more. Wish I could.
