### ISSUE TITLE
Clicking Get Code does not create working URLs on a remote server

### ISSUE THREAD

**Issue by beshur** [WebDevStudios/custom-post-type-ui#445]
Hi.

I am developing a Wordpress site locally and have its remote location.
So I created a new plugin using Custom Post Type UI. To make it work on a remote location I clicked 'Get Code' and pasted it in my plugin file.
```
add_action('init', 'cptui_register_tm_story');
function cptui_register_tm_story() {
    register_post_type('story', array(
    'label' => 'Истории',
    'description' => '',
    'public' => true,
    'show_ui' => true,
    'show_in_menu' => true,
    'capability_type' => 'post',
    'map_meta_cap' => true,
    'hierarchical' => false,
    'rewrite' => array('slug' => 'story', 'with_front' => true),
    'query_var' => true,
    'supports' => array('title','editor','excerpt','trackbacks','custom-fields','comments','revisions','thumbnail','author','page-attributes','post-formats'),
    'taxonomies' => array('category','post_tag'),
    'labels' => array( ... )
); }
```
Also I've added this flush section:
```
register_deactivation_hook( __FILE__, 'flush_rewrite_rules' );
register_activation_hook( __FILE__, 'tmStory_flush_rewrites' );
function tmStory_flush_rewrites() {
    flush_rewrite_rules();
}
```
The problem is that I get a 404 error when I go to /story/story-name on a remote server (locally everything is okay).
Should I explicitly define my slug rewrite for the plugin?

**Comment by tw2113** [comment]
Since you don't appear to be using CPTUI on the remote site, the two flush
callbacks won't apply unless you're adding it all to a custom plugin for
the remote site and activating. If it already had permalinks set, it's
worth visiting the permalinks settings page just to be sure things get
flushed.

On Sunday, March 20, 2016, Alex Buznik <notifications@github.com> wrote:

> Hi.
>
> I am developing a Wordpress site locally and have its remote location.
> So I created a new plugin using Custom Post Type UI. To make it work on a
> remote location I clicked 'Get Code' and pasted it in my plugin file.
>
> add_action('init', 'cptui_register_tm_story');
> function cptui_register_tm_story() {
>     register_post_type('story', array(
>     'label' => 'Истории',
>     'description' => '',
>     'public' => true,
>     'show_ui' => true,
>     'show_in_menu' => true,
>     'capability_type' => 'post',
>     'map_meta_cap' => true,
>     'hierarchical' => false,
>     'rewrite' => array('slug' => 'story', 'with_front' => true),
>     'query_var' => true,
>     'supports' => array('title','editor','excerpt','trackbacks','custom-fields','comments','revisions','thumbnail','author','page-attributes','post-formats'),
>     'taxonomies' => array('category','post_tag'),
>     'labels' => array( ... )
> ); }
>
> Also I've added this flush section:
>
> register_deactivation_hook( __FILE__, 'flush_rewrite_rules' );
> register_activation_hook( __FILE__, 'tmStory_flush_rewrites' );
> function tmStory_flush_rewrites() {
>     flush_rewrite_rules();
> }
>
> The problem is that I get a 404 error when I go to /story/story-name on a
> remote server (locally everything is okay).
> Should I explicitly define my slug rewrite for the plugin?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/WebDevStudios/custom-post-type-ui/issues/445>
>


-- 
~Michael
http://michaelbox.net

**Comment by beshur** [comment]
Thank you for reply, @tw2113.
Actually I have CPT UI on a remote site, but I didn't try to recreate the custom post type I needed in it.

Fixed by clicking 'Save' on Settings/Permalinks page without changing anything.

**Comment by tw2113** [comment]
Awesome to hear.

1.3.0 should have better support without having to manually hit save on the permalinks, for what it's worth.
