### ISSUE TITLE
Clicking a question mark returns you to top of screen

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#447]
If I'm on the Add CPT screen and scroll down to the supports section and click the ? next to "Title" (for example), I'm transported back to the top of the screen.

This happens for all question marks, not just the example given above.

**Comment by tw2113** [comment]
```
<a href="#"></a>
```
Would do that. Not a show stopper if we hold off till later, but it'd be easy enough to get some quick js in to prevent the click action.

**Comment by tw2113** [comment]
Fixed in 1.3.0 branch
