### ISSUE TITLE
Weird layout issue after edit

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#448]
When I'm on the edit CPT screen and click save, the appresser and maintainn ads don't display properly. See attached screenshot.
![weird-layout-after-save](https://cloud.githubusercontent.com/assets/367562/13935270/b4063ce6-ef73-11e5-9f26-c601d410a422.png)

**Comment by vegasgeek** [comment]
Sorry, quick update... I'm seeing that layout issue happening on the Add new post page as well.

**Comment by tw2113** [comment]
Clear your cache. First time upgraders will get the new cache because of version # changes on the URL, but you've had 1.3.0 installed for awhile and won't have that happen.

**Comment by tw2113** [comment]
Re-read above, but still not managing to recreate.

**Comment by tw2113** [comment]
Actually...probably minified version issues.

**Comment by tw2113** [comment]
@vegasgeek when you get a moment, pull the 1.3.0 branch again and confirm if this is fixed.

**Comment by vegasgeek** [comment]
I did a pull and it fixed the issue. Thanks!
