### ISSUE TITLE
Add CPTUI to packagist.org

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#456]
We already have a WDS account there for CMB2 stuff. May as well utilize for CPTUI as well.

**Comment by thaiphan** [comment]
Hey @tw2113,

How is this coming along? It's a five minute job but I would very much appreciate your effort when this package is available on Packagist.

Regards,

Thai

**Comment by tw2113** [comment]
Haven't touched it yet, as other duties have taken precedence. It's not forgotten by any means, so don't worry. Just other stuff needs taken care of first.

**Comment by GaryJones** [comment]
Still only a five-minute task :-)

**Comment by tw2113** [comment]
I feel like getting this done.

**Comment by tw2113** [comment]
Is there any reason why https://wpackagist.org/search?q=custom+post+type+ui would not do and cover this? Especially with it being a WordPress plugin for what I have to assume is going to be WordPress projects.

**Comment by tw2113** [comment]
I'm going to veto packagist.org in favor of wpackagist.org's version.
