### ISSUE TITLE
Prevent need to refresh or make extra click to see new post types and taxonomies in menu

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#457]

**Comment by modemlooper** [comment]
I think this can be accomplished as easy as having the form submit action have a redirect param and then when it redirects without param.

**Comment by tw2113** [comment]
Upon hitting submit, the post type/taxonomy screens begin to load the page/fields again. Right before it loads the new div.wrap to encapsulate the page content, it passes the raw $_POST superglobal into our save/delete functions, based on selected action. Those functions do their thing, process the option(s), and return results. At that point, the page continues to render like not much happened. Since it has no selected post type, it just renders empty fields again. Essentially the same thing occurs on the edit tab, except it will have a selected post type to query for and fill in fields for. There's no real point where a redirect and/or $_GET param can be added to trigger the redirect. Doing a wp_redirect at that point will cause "headers already sent" errors, and checking for a $_GET param on admin_init will prevent the saving/deleting from processing.

Because of this, if we're for sure going to do this, I feel it's best to do all the processing of new/updated/deleted $things to the init hook. This will require me to extract the $_POST handling from out of the page rendering callbacks and into their own admin_init, no ajax, callbacks. If my head is working everything out properly, this will also make sure that the new/updated/removed items are already ready for the registering functions, allowing these to show up right away, without need for any extra redirects.

I just want to make sure we don't break BC and things will continue to run smoothly, as I know you both want as well.

**Comment by modemlooper** [comment]
what if you hook the redirect to an action after page loaded. So basically populate two params, a redirect param and a param for current to populate fields after redirect

**Comment by tw2113** [comment]
It'd still redirect before data can be saved/deleted. That's the biggest problem. I'm not processing data on init, it's well after and after when a redirect would take effect. Going with what I put in last night, there'd be zero need for a redirect if my logic is accurate.

**Comment by tw2113** [comment]
Began work in 457-norefresh

Trying to work around a potential plate of $_GET param pasta or some other solution for setting what notice to display and whether or not something was deleted.

**Comment by tw2113** [comment]
Done:
Saving/deleting now happens on init hook, at priority 8, instead of at the top of our page. This is allowing things to be registered and in the admin menu right away.

Todo:

1. Figure out why can't delete post types on this branch.
2. Pass along the fact that a $thing was deleted.
3. Somehow post admin notice that our cptui_process_$thing() returns.

**Comment by tw2113** [comment]
post type deletion figured out. We were trying to check if post type existed, before we registered it. Thus "not exists" turned true and we returned early.

**Comment by tw2113** [comment]
Ideas for bullet point 2 and 3:

wp_redirect and $_GET params: deleted = 1, notice=#.

Treat the 1 as boolean true/false,
notice references an index in an array that holds the corresponding error? Use string to indicate error/error type?

**Comment by tw2113** [comment]
Look into using the admin_notices hook over return values and echo'ing ourselves.

**Comment by tw2113** [comment]
See freshly pulled **457-norefresh** branch OR **ui-no-refresh** to see in action.

Had to redo how we did admin notices in many places, including using the proper hook for them, multiple new callbacks, amended return values to fill in callback references dynamically, and some clever filtering.

Pending no issues, ready to merge.

**Comment by tw2113** [comment]
Merged into alpha.
