### ISSUE TITLE
Add basic Installation instructions to WP.org readme

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/custom-post-type-ui#461]
[WP.org "Installation" tab](https://wordpress.org/plugins/custom-post-type-ui/installation/) -  This tab just shows a one sentence description on WP.org. Would be simple enhancement to show even boilerplate WP.org instructions, e.g. copy/pasting from BuddyPress plugin:

**From your WordPress dashboard**

1. Visit 'Plugins > Add New'
2. Search for 'BuddyPress'
3. Activate BuddyPress from your Plugins page. (You will be greeted with a Welcome page.)

**From WordPress.org**

1. Download BuddyPress.
2. Upload the 'buddypress' directory to your '/wp-content/plugins/' directory, using your favorite method (ftp, sftp, scp, etc...)
3. Activate BuddyPress from your Plugins page. (You will be greeted with a Welcome page.)

This would give a more consistent experience for new, and old WP.org users.

**Comment by tw2113** [comment]
Seems I lost my installation notes. Will need to check the readme.txt file on .org

**Comment by colorful-tones** [comment]
I wonder if it is just a matter of the order of contents in the Readme.txt that is borking the output on WP.org? I have not written a Readme.txt for .org plugin in awhile, and can't remember all the nuances, and just an idea. https://github.com/WebDevStudios/custom-post-type-ui/blob/master/readme.txt#L389

**Comment by tw2113** [comment]
Fixed
