### ISSUE TITLE
Add "hide ads" text and link to sidebar

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#462]
Note: This feature should not go out until after Extended 1.1 gets release which will have the ability to remove the sidebar ads

In the sidebar, under the banner ads, let's add the following text:

Remove these ads?
[Upgrade to CPTUI Extended](https://pluginize.com/product/custom-post-type-ui-extended/?utm_source=cptui-dashboard&utm_medium=text&utm_campaign=remove_ads)

Using this as the link:
https://pluginize.com/product/custom-post-type-ui-extended/?utm_source=cptui-dashboard&utm_medium=text&utm_campaign=remove_ads

**Comment by tw2113** [comment]
See 462-ad-removal

**Comment by vegasgeek** [comment]
Please update the link for this to be:
https://pluginize.com/product/custom-post-type-ui-extended/?utm_source=remove_ads&utm_medium=text&utm_campaign=cptui

**Comment by tw2113** [comment]
Updated in the branch.

MICHAEL! REBASE THE AD REDO BEFORE MERGING THIS IN WHEREVER.

**Comment by tw2113** [comment]
Bumping to later release to make sure Extended can handle removing it.

**Comment by tw2113** [comment]
I think just manually adding to the release branch at the time will save time and confusion.

**Comment by tw2113** [comment]
Merged into alpha.
