### ISSUE TITLE
Update footer of About CPT UI page

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#464]
On the About CPT UI page, we want to remove the section that currently reads "Help Support This Plugin" and replace it with the banner ads for pluginize products.

I've attached a mockup.
![cptui-about](https://cloud.githubusercontent.com/assets/367562/14504174/8032e778-0168-11e6-957f-9916cb382695.png)

**Comment by tw2113** [comment]
Pull and QA `464-about-page-ads` branch. It doesn't replace, it simply adds to the top of the the "extras" area, below the changelog.

**Comment by tw2113** [comment]
Merged into alpha branch. Closing.
