### ISSUE TITLE
Add "The Latest From Pluginize" section to bottom of help/support page

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#465]
On the Help/Support tab, add a section similar to what's being added in ticket #464 using the same layout.

**Comment by tw2113** [comment]
At this point, we're getting to the point of having ads on every page. Do we REALLY need it on this page as well? It's already arguably debate-able how often users visit this page. The "ads" are on our most prominent pages as is.

You already know I'm hesitant to overdo it on the topic.

**Comment by tw2113** [comment]
Closing in favor of #471
