### ISSUE TITLE
Update FAQ regarding post type display to mention Extended

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#466]

**Comment by tw2113** [comment]
How does this sound:

**We encourage checking out Custom Post Type UI Extended for easily displaying post type content wherever you can utilize a shortcode. If you prefer to handle on your own, you will need to utilize the WP_Query class to handle display in custom locations. If you have set the post type to have archives, the archive url should be something like "http://www.mysite.com/post-type-slug"**

**Comment by vegasgeek** [comment]
This is good. I updated the line to include a link to CPTUI Extended.
