### ISSUE TITLE
Undefined index notifications for publicly_queryable showing up for 1.4.x future release

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#467]
line 358 of root file.

**Comment by williamsba** [comment]
Let's try to get this in 1.3.4

**Comment by tw2113** [comment]
Actually, this isn't publicly released yet and in the 1.3.x branch. It IS here in trunk, since I mixed up what branch I was committing to at the time. It would be a 1.4.0 enhancement feature

**Comment by tw2113** [comment]
Fixed in alpha, or at least should be.
