### ISSUE TITLE
Add newsletter signup form to sidebar above ads

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#469]
On the right had sidebar, above the other pluginize ads, I want to add a form to let people sign up for the newsletter. It should be a single text field for email address and then under it should read "Get email updates from pluginize.com about Custom Post Type UI". Under that would be a submit button that reads "Sign Up"

Here's the form details:

[mailchimp-form.txt](https://github.com/WebDevStudios/custom-post-type-ui/files/235530/mailchimp-form.txt)

**Comment by modemlooper** [comment]
well this is using cmb so its stuck in one for and probably not possible to move the input over there

**Comment by tw2113** [comment]
See 1.3.4 branch

![screen shot 2016-04-26 at 1 20 22 am](https://cloud.githubusercontent.com/assets/484075/14808701/2b12b39c-0b4d-11e6-932c-a55ac48332d4.png)

**Comment by tw2113** [comment]
Should probably test and make sure it signs people up, though I suspect it will

**Comment by vegasgeek** [comment]
I updated the text. This is good to go.
