### ISSUE TITLE
Internationalize text in CPTUI newsletter output.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#470]

**Comment by vegasgeek** [comment]
Since I was in there, I went ahead and did this as well.

FYI, I'm not sure how to add i18n to the responses that come back from mailchimp.

**Comment by tw2113** [comment]
As mentioned on the commit, overruled in favor of esc_html_e() and esc_attr_e(); The idea was valid though :D 

We'll have to accept Mailchimp not providing internationalized text.
