### ISSUE TITLE
Extensions tab

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#471]
Add a sub-menu item under CPTUI called "Extensions"
- Force the extensions menu item to be orange. #fdac5f

I've attached a mockup of how the extensions will be displayed.

![cptui-extensions-tab](https://cloud.githubusercontent.com/assets/367562/14836995/79c74f6c-0bc9-11e6-9ec3-1cf08ac462fd.png)

**Comment by vegasgeek** [comment]
I'm working on getting an exact design for the individual extension boxes. I'll let you know as soon as that's solidified. I will also provide a tracking link for the Get the Extension button.

**Comment by tw2113** [comment]
Pushed up an initial version to the 471-extentions-page branch.

Tabs and menu are in place. Menu is colored ala WP SEO.

Hooks are in place for some initial ones.

Need to figure out the best way to handle the listing output, depending on selected tab. Would like to try and avoid over-engineering while not repeating myself.

Note to self: review how handling the 4 different tab sections in the Import/Export file.

**Comment by tw2113** [comment]
![screen shot 2016-04-27 at 1 58 29 am](https://cloud.githubusercontent.com/assets/484075/14844248/9716ce4c-0c1b-11e6-897a-a50025c2a26d.png)

**Comment by tw2113** [comment]
along with what we have above, let's add the "Add "The Latest From Pluginize" section to bottom of help/support page" idea from #465 to this page.

**Comment by tw2113** [comment]
Starting fresh with this one. New branch as well 471-extentions-page-2022

**Comment by tw2113** [comment]
Closing this one in favor of a CPTUI-only focused task, minus long history of this issue.
