### ISSUE TITLE
When json fails, text ads don't line up well

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#472]
Currently when the json file isn't reached and the sidebar ads are going to just show the text ads, they all run together with no formatting, like so:

![image](https://cloud.githubusercontent.com/assets/367562/14842419/e71d4ac6-0bfb-11e6-95c4-dced93b8203a.png)

If possible, add them to a bullet point list, or at least add a line break after each.

**Comment by tw2113** [comment]
472-no-image-ads branch

**Comment by tw2113** [comment]
Merged into 1.3.4 branch
