### ISSUE TITLE
Return of Undefined index: rewrite_withfront warnings

### ISSUE THREAD

**Issue by djmtype** [WebDevStudios/custom-post-type-ui#473]
Looks like this issue is back, but now affecting different lines from a previous closed issue. 
[https://github.com/WebDevStudios/custom-post-type-ui/issues/275](https://github.com/WebDevStudios/custom-post-type-ui/issues/275)

```
Notice: Undefined index: rewrite_withfront in /Users/me/Sites/sage/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 471

Notice: Undefined index: rewrite_hierarchical in /Users/me/Sites/sage/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 472
```

**Comment by tw2113** [comment]
Will check on and see what I can deduce

**Comment by tw2113** [comment]
Looks like that's my "wontfix" issue, which was never properly and permanently fixed. Best I can suggest is hitting save on all of your post types to get the index filled in. This one would be able to be fixed once we get everyone off the old settings values from before 1.0.x, but that's still 24% away from being true.

**Comment by MichaelCropper** [comment]
Note on the above, this worked for me. I had to save the Custom Taxonomies too as well as the Custom Post Types and the errors disappeared.

**Comment by pstonier** [comment]
This worked for me, as well. It was my custom taxonomies that had the issue.
