### ISSUE TITLE
Update product area on dashboard widget

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#474]
Currently the dashboard widget's "Pluginize Shop" section is pulling in the featured image for the products, and it's not very effective. Here's what I'd like to do:

1. On pluginize.com's products, create a metabox that will let us add a new image to be used solely for the dashboard widget.
2. On a daily basis, pick a random product from pluginize.com that has been marked with the "show product on pluginize dashboard widget"
3. The URL structure for the link to the product should be like this:
https://pluginize.com/product/[product_name]/?utm_source=dashboard-widget&utm_medium=banner&utm_campaign=cptui
4. The new image size will be 695x205, but should fit 100% width and scale appropriately.

I've attached a mockup as well
![image](https://cloud.githubusercontent.com/assets/367562/14930502/2ec86044-0e19-11e6-8ca6-b9f9d044f9c7.png)

**Comment by tw2113** [comment]
Doesn't this go on the extended repo?

On Friday, April 29, 2016, John Hawkins <notifications@github.com> wrote:

> Currently the dashboard widget's "Pluginize Shop" section is pulling in
> the featured image for the products, and it's not very effective. Here's
> what I'd like to do:
>
>    1. On pluginize.com's products, create a metabox that will let us add
>    a new image to be used solely for the dashboard widget.
>    2. On a daily basis, pick a random product from pluginize.com that has
>    been marked with the "show product on pluginize dashboard widget"
>    3. The URL structure for the link to the product should be like this:
>    https://pluginize.com/product/[product_name]/?utm_source=dashboard-widget&utm_medium=banner&utm_campaign=cptui
>    4. The new image size will be 695x205, but should fit 100% width and
>    scale appropriately.
>
> I've attached a mockup as well
> [image: image]
> <https://cloud.githubusercontent.com/assets/367562/14930502/2ec86044-0e19-11e6-8ca6-b9f9d044f9c7.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/WebDevStudios/custom-post-type-ui/issues/474>
>


-- 
~Michael
http://michaelbox.net

**Comment by vegasgeek** [comment]
Derp
