### ISSUE TITLE
Update to sidebar graphics

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#477]
On the Add/Edit Post Types & Add/Edit Taxonomies pages, in the sidebar we need to make a couple changes to the banner ads:

1. Remove the call to the remote .json file
2. Include the 3 banner ads as part of the plugin
3. Update the images to call from the local server

Please use the same links that are currently being used for each of the 3 graphics.

**Comment by tw2113** [comment]
Should all be in 1.3.4 branch
