### ISSUE TITLE
Update text on help/support page

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#479]
Just under the page title, update the text to read as follows:

Please note that **this plugin will not handle display** of registered post types or taxonomies in your current theme. It simply registers them for you. To display your data, check out CPTUI Extended. If all else fails, visit us on the Support Forums

Support Forums should keep the same link.

CPTUI Extended should link to:
https://pluginize.com/product/custom-post-type-ui-extended/?utm_source=faq&utm_medium=text&utm_campaign=cptui

**Comment by tw2113** [comment]
Fixed in 9e120a852d
