### ISSUE TITLE
Filter fields of custom taxonomy using CPT & REST API v2

### ISSUE THREAD

**Issue by mnguye08** [WebDevStudios/custom-post-type-ui#488]
Hi,
I've created a new taxonomy with CPT named "custom_tag" and opened it to REST API.
I would like to unset some "useless" fields in the rest api response ("link", "parent", "_links" for example).

I've tried 2 plugins for filter fields in REST API (https://github.com/svrooij/rest-api-filter-fields and https://github.com/nCrafts/json-rest-api-filter-fields) but both don't work in this case.

Is there a way to do that?

Thanks for your help!

**Comment by tw2113** [comment]
Nothing that our plugin is going to be involved with as far as I can tell. We focus on getting the types and taxes registered. All this content querying and JSON response construction comes way after that. I'd talk with those two developers and see if they have any idea why things aren't working.
