### ISSUE TITLE
Add custom updated messages for CPTs

### ISSUE THREAD

**Issue by modemlooper** [WebDevStudios/custom-post-type-ui#492]
When you save and publish etc, it adds messages to above CPT "Post Updated". Lets add custom messages so it says "{CPT} Updated". 

Example:

```
function custom_post_type_post_updated_messages($messages) {
  $messages['custom_post_type_key'] = array(
    0 => '', // Unused. Messages start at index 1.
    1 => sprintf( __('CPT updated. <a href="%s">View page</a>'), esc_url( get_permalink($post_ID) ) ),
    2 => __('Custom field updated.'),
    3 => __('Custom field deleted.'),
    4 => __('CPT updated.'),
    5 => isset($_GET['revision']) ? sprintf( __('CPT restored to revision from %s'), wp_post_revision_title( (int) $_GET['revision'], false ) ) : false,
    6 => sprintf( __('CPT published. <a href="%s">View page</a>'), esc_url( get_permalink($post_ID) ) ),
    7 => __('CPT saved.'),
    8 => sprintf( __('CPT submitted. <a target="_blank" href="%s">Preview page</a>'), esc_url( add_query_arg( 'preview', 'true', get_permalink($post_ID) ) ) ),
    9 => sprintf( __('CPT scheduled for: <strong>%1$s</strong>. <a target="_blank" href="%2$s">Preview page</a>'), date_i18n( __( 'M j, Y @ G:i' ), strtotime( $post->post_date ) ), esc_url( get_permalink($post_ID) ) ),
    10 => sprintf( __('CPT draft updated. <a target="_blank" href="%s">Preview page</a>'), esc_url( add_query_arg( 'preview', 'true', get_permalink($post_ID) ) ) ),
  );

  return $messages;
}
add_filter( 'post_updated_messages',  'custom_post_type_post_updated_messages'  );
```

**Comment by modemlooper** [comment]
![message](https://cloud.githubusercontent.com/assets/867885/15826245/a8711b38-2bbb-11e6-8d8d-e610ddd8d6e6.png)

**Comment by tw2113** [comment]
I'm split on this one. I can definitely understand the appeal and reasoning to, from a user standpoint. However I also feel like it starts extending a limb outside what we've been doing thus far, which is focus on the registration aspect only. This inches us more towards customization beyond register_* functions.

That filter also offers no great way to conditionally do anything, just passes in this massive array. We'd need to either do it for all post types, offer a new input to select which ones to do it for, or some other solution not yet thought of.

**Comment by tw2113** [comment]
@vegasgeek What do you think about this one for Extended?

**Comment by tw2113** [comment]
Closing as wontfix for CPTUI free.
