### ISSUE TITLE
Dismiss update message reappears on every page load

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#493]
![image](https://cloud.githubusercontent.com/assets/367562/15846888/e779ea74-2c35-11e6-8085-ea17c8a0032e.png)

I'm using the Master branch and no matter how many times I click the dismiss button, the message above comes back to remind me that an upgrade is available.

**Comment by tw2113** [comment]
Is this from Extended? I don't recall any sort of notice of this type of message in Free.

**Comment by vegasgeek** [comment]
derp. yes. closing (already added a ticket on extended)
