### ISSUE TITLE
CSS / Scripts load on every admin page

### ISSUE THREAD

**Issue by modemlooper** [WebDevStudios/custom-post-type-ui#496]
Prolly should enqueue these only on cptui pages. The id / classes are a bit generic and I notice some style bleed into other areas of admin.

**Comment by tw2113** [comment]
Will check on but should already be limited to our pages. Also should be
prefixed for new stuff, but may have overlooked old

On Monday, June 13, 2016, modemlooper <notifications@github.com> wrote:

> Prolly should enqueue these only on cptui pages. The id / classes are a
> bit generic and I notice some style bleed into other areas of admin.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/WebDevStudios/custom-post-type-ui/issues/496>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAdi62b92iZVjpf4CilecKGbKPbQdzoFks5qLdk5gaJpZM4I0y7v>
> .
>


-- 
~Michael
http://michaelbox.net

**Comment by tw2113** [comment]
Did some more prefixing and we should be pretty well covered at the moment.
