### ISSUE TITLE
Add newsletter signup form to About page

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#498]
I'd like to add a signup for the pluginize newsletter form to the about page. Here's a mockup of how I'd like it to look.

![cptui-about-page](https://cloud.githubusercontent.com/assets/367562/16094532/7c216cc2-32f5-11e6-988e-12e52bd6a4a9.png)

**Comment by vegasgeek** [comment]
The actual wording in the newsletter section would be:

**Stay Informed**
Wanna make the most of WordPress? Sign up for the Pluginize newsletter and get access to discounts, plugin announcements, and more!

**Comment by tw2113** [comment]
Check 498-about-page-newsletter branch

**Comment by tw2113** [comment]
Merged and pushed into alpha.
