### ISSUE TITLE
Change link on help/support page

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#499]
I'd like to update the link found in the screenshot below to this new link for better tracking:

https://pluginize.com/product/custom-post-type-ui-extended/?utm_source=faq-remove&utm_medium=text&utm_campaign=cptui

![image](https://cloud.githubusercontent.com/assets/367562/16100363/b509771a-3312-11e6-87a1-e2dc3e5f9712.png)

**Comment by tw2113** [comment]
8922cd1.

Also pushed it in release.
