### ISSUE TITLE
Update About page to display to users upon activation

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#502]
I'd like to update the About page to perform like the WordPress activation notice. This means we'll need to update the header section to include the logo on the right hand side, and I've got some updated text to replace the top section:

Thank you for choosing Custom Post Type UI! We hope that your experience with our plugin makes creating post types and taxonomies and organizing your content quick and easy.

**Comment by tw2113** [comment]
text has been updated. Will need to investigate how to make the redirect to the landing page.

**Comment by tw2113** [comment]
Check out 502-about-redirect branch for this.

**Comment by vegasgeek** [comment]
when I check out the 502 branch, I get the following error message:
Fatal error: Cannot redeclare cptui_add_activation_redirect() (previously declared in /Applications/MAMP/htdocs/wds/wp-content/plugins/cptui-extended/loader.php:710) in /Applications/MAMP/htdocs/wds/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 58

**Comment by tw2113** [comment]
Fixed and pushed up

**Comment by tw2113** [comment]
Merged into alpha
