### ISSUE TITLE
Multi-delete capabilities

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#515]
How can we allow to delete many at once.

**Comment by tw2113** [comment]
Delete from listings page? Checkboxes + button + confirmation? AJAX deletion?

**Comment by garrett-eclipse** [comment]
Thanks for linking the two @tw2113 I think this would be a nice to have allowing for multi-delete but also reducing the steps to deletion.

**Comment by tw2113** [comment]
I think our setup and UI is more ready for #687 than it is this one, so I'm going to close this task in favor of that one, and say we are going to add that one in a future release.
