### ISSUE TITLE
Menu position description displaying HTML

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#520]
In the ui-no-refresh branch, on the add/edit post types screen, the description for Menu Position is displaying the HTML for a link rather than displaying it as a link.

![image](https://cloud.githubusercontent.com/assets/367562/17405566/dacb1bec-5a14-11e6-98df-57cd7fb8a2e0.png)

**Comment by tw2113** [comment]
Will be taken care of once merged in with alpha, thanks to #509

**Comment by tw2113** [comment]
Michael. Rebase, may be getting wiped out due to how things were applied in ui-no-refresh branch.
