### ISSUE TITLE
Make "Extended Options" its own box 

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#521]
On the ui-no-refresh branch, on the Add/Edit post types screen, now that we're using the beautiful new UI, I think we should have the Extended options show up in their own box rather than being part of Settings. 

Let's rename the new box to read "Extended Options"

**Comment by tw2113** [comment]
https://github.com/WebDevStudios/CPTUI-Extended/issues/132
https://github.com/WebDevStudios/custom-post-type-ui/issues/519
