### ISSUE TITLE
 Problem get taxonomy code

### ISSUE THREAD

**Issue by oliveiraivan** [WebDevStudios/custom-post-type-ui#522]
The code missing include the comma after the value of 'with_front'.

`"rewrite" => array( 'slug' => 'legislacao/categoria', 'with_front' => true  'hierarchical' => true ),`

**Comment by tw2113** [comment]
Will fix, thanks for pointing it out @oliveiraivan

**Comment by oliveiraivan** [comment]
You're welcome

**Comment by tw2113** [comment]
Fixed in alpha.
