### ISSUE TITLE
Notice:  Undefined index: show_in_quick_edit

### ISSUE THREAD

**Issue by MarcGuay** [WebDevStudios/custom-post-type-ui#523]
Hi, 
I'm getting this notice when exporting taxonomies with v1.3.5.

**Comment by MarcGuay** [comment]
Nevermind, I just had to re-save taxonomies that were created with an old version...

**Comment by tw2113** [comment]
Going to re-open so I can double check on it.

**Comment by tw2113** [comment]
Should be fixed in alpha branch
