### ISSUE TITLE
Filter that allows overriding of CPTUI data to be registered

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#525]
In the same vein as we now have a tutorial about saving our data to a file, at https://secure.helpscout.net/docs/56e8271cc697911471461e7c/article/57a8ea7b90336059d4edd6fd, we could also allow, via filter, a way to inject CPTUI settings data dynamically, without overwriting our settings in the database.

Useful for temporary loading of post types/taxonomies.

```
function pluginize_hotwire_cptui( $original_data = array() ) {
    $theme_dir = get_stylesheet_directory();

    $file_data = file_get_contents( $theme_dir . '/cptui_post_type_data.json' );
    $decoded = json_decode( $file_data );

    if ( is_array( $decoded ) ) {
        return $decoded;
    }

    return $original_data;
}
add_filter( 'some_non_existant_filter', 'pluginize_hotwire_cptui' );
```

Add extra section for "Registered Types/Taxes" section that shows in a nicely formatted way. May need to create functions that handle output of the list table, and accepts data to parse out.

Would also be handy for debugging purposes.

**Comment by tw2113** [comment]
Closing due to not a huge amount of usefulness at this point.

**Comment by natedunn** [comment]
I mean, shit I would use this.

**Comment by tw2113** [comment]
i think technically it could be done via a filter inside the get_option() call, but i could see a more obvious filter being more useful and upfront. I can re-open for reconsideration.

**Comment by tw2113** [comment]
https://gist.github.com/tw2113/967a4d387d0629b4d92609ac9a2e0497

**Comment by tw2113** [comment]
We...have that?

Post types:
https://github.com/WebDevStudios/custom-post-type-ui/blob/1.11.2/custom-post-type-ui.php#L258-L265
Taxonomies:
https://github.com/WebDevStudios/custom-post-type-ui/blob/1.11.2/custom-post-type-ui.php#L553-L561

**Comment by tw2113** [comment]
Closing because by all metrics I believe I ended up adding this via other tickets, in the long run.
