### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by pedro-mendonca** [WebDevStudios/custom-post-type-ui#543]
**trhough** on https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/support.php#L105

**Comment by tw2113** [comment]
Thanks Pedro. May not pull in your PR specifically, but I'll give credit in the changelog for it.

**Comment by tw2113** [comment]
Fixed in 553f0a1 with you given props there in the commit message as well.
