### ISSUE TITLE
Rename "Get Code"

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#556]
It's always been a bit odd to say/type to someone and hope it makes sense.

Paste-ables?
Code snippet?
Snippets?

**Comment by GaryJones** [comment]
I think "Get code" is far more obvious as to **the intent of what the user can do**, vs **a label of what the feature is**. It implicitly describes the benefit (they'll have gotten some code).

We typically live in an action-driven world (_buy now_, _subscribe_, _submit_, _donate_, _update_, _add new_, etc.), so "get code" is a good call to action to push someone to something that will solve their immediate goal.

**Comment by tw2113** [comment]
Nearing 2 years later, and 5 months after Gary's thoughts, going to close as wontfix. It's what our users are familiar with, and it does sound like an action to be taken, etc.
