### ISSUE TITLE
class.cptui_admin_ui.php does not allow selects with integers

### ISSUE THREAD

**Issue by wpexplorer** [WebDevStudios/custom-post-type-ui#566]
Working on extending the plugin for my Total theme I noticed that in class.cptui_admin_ui.php it sanitizes numeric fields via disp_boolean as well as it prevents the selected attribute from being added due to the ! is_numeric( $args['selections']['selected'] ) check.

I see why the checks are there (for checkboxes/true,false). But it also causes issues when trying to create a dropdown for a user to select a numeric value. Example:

![screen shot 2016-09-24 at 9 07 12 pm](https://cloud.githubusercontent.com/assets/1128841/18812954/e2254fe4-829a-11e6-964b-a31da94e7a68.png)

Could we add in an extra parameter for the select type to conditionally prevent sanitization? I can submit a pull request if you'd like.

Please let me know your thoughts! Thank you ;)
- AJ

**Comment by tw2113** [comment]
I'd be open to the idea and curious what solution you have in mind for this.

**Comment by tw2113** [comment]
@wpexplorer wanted to check and see if you had any followup for this one.

**Comment by wpexplorer** [comment]
@tw2113 I actually ended up doing something a bit different that works with your core functions ;)

**Comment by tw2113** [comment]
Curious what that is, to be honest. Worth documenting just in case, and it may be something I find value with adding to CPTUI anyway.

**Comment by wpexplorer** [comment]
@tw2113 Oh, I just used a standard textfield with some extra sanitization to make sure only integers between a certain range were entered. So quick solution for now as I didn't have the time to really dig deeper at the moment. But I may re-visit this sometime in the future if I get questions from customers - none so far ;)

**Comment by tw2113** [comment]
Gonna close in the meantime. Thanks.
