### ISSUE TITLE
Responsive issue on the add/edit pages

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#568]
![fireshot capture 15 - add_edit post types my word_ - http___reactordev com_apv3_wp-admin_admin php](https://cloud.githubusercontent.com/assets/367562/18962835/34522942-8627-11e6-8c3f-8a180e06a48e.png)

**Comment by tw2113** [comment]
What device/dimensions?

**Comment by tw2113** [comment]
See release-142 branch.
BEWARE: Changelog is showing publicly_queryable being removed compared to master. Branch was made from "release" branch, so may need to fix.

**Comment by tw2113** [comment]
Released monday.
