### ISSUE TITLE
get_terms when registered?

### ISSUE THREAD

**Issue by JoeDawson** [WebDevStudios/custom-post-type-ui#572]
Hello,

Thanks for this plugin. I've found it extremely useful recently.

In my theme's `functions.php` and I want to `get_terms` after they're registered with this plugin.

How could I achieve this? As currently in my `functions.php` I'm using this;

```
$terms = get_terms(array(
	'taxonomy' => 'vacancy_type',
	'hide_empty' => false
));
```

But it always returns an "Invalid Taxonomy" error, only for taxonomies created with this plugin though. I imagine there's a way I can only use `get_terms` for this taxonomy after they're registered?

I hope I'm making sense!

Thanks.

**Comment by tw2113** [comment]
What priority are you running this function on? We're registering the taxonomies on priority 9 on init, so anything before that would be too early. Anything after should be good.

**Comment by JoeDawson** [comment]
Hey @tw2113, thanks for reply. I've been using Wordpress briefly for years, just haven't learnt much with regards to hooks etc lol. I got it working with a priority of 10 as you suggested, thanks man.

```
add_action('init', 'map_vacancies_element', 10);

function map_vacancies_element() {

	$terms = get_terms(array(
		'taxonomy' => 'vacancy_type',
		'hide_empty' => false
	));

	var_dump($terms);

	vc_map(array(
		'name'		=> __('IMDMS Vacancies'),
		'base'		=> 'imdms_vacancies',
		'category'	=> __('IMDMS'),
		'icon'		=> get_stylesheet_directory_uri() . '/assets/img/icons/vc.png',
		'params'	=> array(
			array(
				'type' 			=> 'checkbox',
				'heading' 		=> __('Vacancy Types', 'imdms'),
				'param_name' 	=> 'types',
				'value'			=> $terms,
				'description' 	=> __('Select the type of vacancies to be displayed.', 'imdms')
			),
			array(
				'type' 			=> 'textfield',
				'heading' 		=> __('Class', 'imdms'),
				'param_name' 	=> 'class',
				'description' 	=> __('Add a custom class for the element.', 'imdms')
			)
		)
	));

}
```

**Comment by tw2113** [comment]
Awesome to hear. Have a good one.
