### ISSUE TITLE
Add "action" as a reserved taxonomy name

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#573]
https://wordpress.org/support/topic/cant-search-posts-on-quickbulk-edit-page/

**Comment by tw2113** [comment]
Added in alpha branch d0fa236

**Comment by elvismdev** [comment]
Would be this related to why I cannot register a new CPT called Action with `action` as it's slug? I don't have any CPT like this one and I keep getting this error message from the screenshot below. PD: this is a fresh new WP installation.

![image](https://cloud.githubusercontent.com/assets/3847077/20374043/b2e35546-ac2a-11e6-9cea-0a0b67616fec.png)

**Comment by tw2113** [comment]
@elvismdev Not this issue specifically, but "action" is a reserved slug for post types as well. Preventing usage of "action" as a taxonomy may actually stem from it being a listed reserved slug from post types.

See https://codex.wordpress.org/Function_Reference/register_post_type#Reserved_Post_Types

"action" isn't listed at https://codex.wordpress.org/Function_Reference/register_taxonomy#Reserved_Terms but since it caused problems, we decided to reserve it anyway.

**Comment by tw2113** [comment]
That said, it's worth trying doing the slug with some sort of prefix/suffix, and for the sake of URLs, use the rewrite_slug field.

**Comment by elvismdev** [comment]
Thank you for the references! Now all makes sense, yeah I should go with prefix or suffix approach.
