### ISSUE TITLE
Weird post type name bug

### ISSUE THREAD

**Issue by modemlooper** [WebDevStudios/custom-post-type-ui#585]
If you have a post type with the slug "field"

The pages loop in admin on all pages /wp-admin/edit.php?post_type=page returns 0 pages.

**Comment by tw2113** [comment]
given how wonky WP and WP_Query can be, probably a slug that should be blacklisted more than anything.

**Comment by tw2113** [comment]
Upon quick testing, the slug "field" is fine, but once you pluralize it to "fields", then I'm able to recreate the issue.
