### ISSUE TITLE
Undefined index utility.php line 670

### ISSUE THREAD

**Issue by Brugman** [WebDevStudios/custom-post-type-ui#588]
I got this when updating a bunch of stuff through the wp-admin. Not sure if I updated CPTUI to 1.5 or if I already had 1.5 and I updated other plugins/themes. (Should have paid attention, my bad.) It only showed once, during the updating progress list thing: X has updated. Y has updated. etc. Should be an easy if isset fix, unless this situation should have never happened in the first place. *plays spooky audio sample*

```
Notice: Undefined index: plugins in D:\webdev\site\public_html\wp-content\plugins\custom-post-type-ui\inc\utility.php on line 670
Warning: in_array() expects parameter 2 to be array, null given in D:\webdev\site\public_html\wp-content\plugins\custom-post-type-ui\inc\utility.php on line 670
```

**Comment by tw2113** [comment]
I'll be going with the isset() checks likely. It's a new thing we added to allow better customization between existing users and brand new ones. We're going to be "marking" them as such via another option in the db. This line in question is run during the upgrade process and the `upgrader_process_complete` hook.

Thanks for pointing this out.
