### ISSUE TITLE
Chrome forces cursor to end of slug field due to triggering "change" when using arrow keys in the input.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#591]
https://wordpress.org/support/topic/glitch-with-taxonomy-slug-making-it-hard-to-edit/

Fixed in alpha. Look into 1.5.2

4743f00
77b7b59

**Comment by tw2113** [comment]
Does so with any sort of change, it appears.

https://stackoverflow.com/questions/8219639/stop-cursor-from-jumping-to-end-of-input-field-in-javascript-replace

https://stackoverflow.com/questions/14508707/updating-an-inputs-value-without-losing-cursor-position

https://stackoverflow.com/questions/3286595/update-textarea-value-but-keep-cursor-position/3288215#3288215

**Comment by tw2113** [comment]
Pending fixed in release152 branch

**Comment by garrett-eclipse** [comment]
Thanks Michael, release152 is much nicer, doesn't reset the cursor unless I enter an invalid character.
