### ISSUE TITLE
Looks like a typo on function cptui_not_new_install

### ISSUE THREAD

**Issue by Luc45** [WebDevStudios/custom-post-type-ui#601]
So, I have CPT UI installed in a website, and received this message when trying to install another plugin:
![chrome_2017-02-06_11-41-05](https://cloud.githubusercontent.com/assets/9341686/22649499/55cf1156-ec62-11e6-9682-27f5328be6db.jpg)

I went to that line and saw this:

```
	// Was CPTUI updated?
	if ( ! in_array( 'custom-post-type-ui/custom-post-type-ui.php', $extras['plugins'] ) ) {
		return;
	}
```

Then I var_dumped $extras and got this:

```
array(2) {
  ["type"]=>
  string(6) "plugin"
  ["action"]=>
  string(7) "install"
}
```

It seems it might be a typo, where it should be plugin instead of plugins on $extra?

-- Edit --

Actually I changed it to "plugin" and kept receiving this error:

PHP Warning: in_array() expects parameter 2 to be array, null given in E:\home\biovisao\Web\wp-content\plugins\custom-post-type-ui\inc\utility.php on line 670

So I just added a little check:

```
	// Was CPTUI updated?
	if (!empty($extras['plugin'])) {
		if ( ! in_array( 'custom-post-type-ui/custom-post-type-ui.php', $extras['plugin'] ) ) {
			return;
		}
	}
```

Not receiving any warnings now.

**Comment by tw2113** [comment]
Can you confirm you're still getting this error with version 1.5.2? Part of the fixes in that release are meant to address this topic. 

You can see the hardening I did in 1.5.2 at https://github.com/WebDevStudios/custom-post-type-ui/blob/1.5.2/inc/utility.php#L670-L681

**Comment by tw2113** [comment]
Closing as "works for me" at the moment. If anything comes up again, we can re-address at that point.
