### ISSUE TITLE
JS errors are preventing plugin from working

### ISSUE THREAD

**Issue by markpopkes** [WebDevStudios/custom-post-type-ui#606]
I love this plugin. Use it all the time. This is the first I've seen this. 

When trying to access any part of the plugins admin pages (like editing a post_type or taxomony), it takes forever to load. Thought it was the server but after looking at the Web Console, I'm seeing tons of javascript errors.

Tried to upload a screenshot but it didn't work, so here's a link: 
http://oi66.tinypic.com/23m955k.jpg

I've disabled other plugins to see if there is a conflict. No results. 

Any thoughts?

**Comment by tw2113** [comment]
My first guess is that it's coming from an AmazonS3 outage going on at the moment. Checking the source file for the errors, along the right side of the console, will tell a broader story for this as well.

**Comment by tw2113** [comment]
@markpopkes did this clear itself up?
