### ISSUE TITLE
Enhance UI some more via user profile colors.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#610]
```
<?php
    global $_wp_admin_css_colors;

    $admin_color = get_user_option( 'admin_color' );
    $colors      = $_wp_admin_css_colors[$admin_color]->colors;
?>
```

**Comment by tw2113** [comment]
Possible just continue to utilize `wp-ui-highlight` class.

**Comment by GaryJones** [comment]
Can you give examples of the CPTUI interface where adding more colour would be beneficial to the UX? 

Mockups may be beneficial, but then you'd also need to test with all colour profiles to check for a11y clashes.

**Comment by tw2113** [comment]
I assume the color schemes themselves from core are already checked for a11y, but definitely worth doing our own extra checks just to be sure.

**Comment by tw2113** [comment]
I'm going to close as wontfix. While a nice idea, it's not essential
