### ISSUE TITLE
A/B testing for ads

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#615]
I'd like the ability for each ad spot to have the ability to have multiple ad graphics and URLs that displayed at random so that we can A/B test ad graphics and text.

So, for example, we will have 3 or 4 ad spots... In spot #2 we want to display an ad for Instago. For instago we have 2 different ad graphics and each ad graphic has a corresponding tracking URL. Pick one of the ad graphics to display and link it to the corresponding URL.

**Comment by tw2113** [comment]
Sorry John, closing until told to do something otherwise.
