### ISSUE TITLE
Randomize order of ad placements

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#616]
On the sidebar, we currently have 3 ad spots. That's likely going to move to 4 spots. Ad spot #1 should always be for CPTUI Extended. But, the other 3 ad spots can be picked at random from our remaining ads.

We may get to the point where we have more ads than we have ad spots. And that's totally fine. If we have 6 ads and only 3 spots to fill, we pick the 3 to display at random, without there ever being the chance of a duplicate, and display them and leave the other 3 unshown.

**Comment by tw2113** [comment]
See 9cabefa
