### ISSUE TITLE
Update sidebar ads

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#619]
Below are the new URLs to use for the new sidebar graphics. This is also the order in which they should show up on the sidebar:

CPTUI Extended
https://pluginize.com/plugins/custom-post-type-ui-extended/ref/pluginizeaff/?campaign=cptui-sidebar-extended

InstaGo
https://pluginize.com/plugins/instago/ref/pluginizeaff/?campaign=cptui-sidebar-ig

BuddyPages
https://pluginize.com/plugins/buddypages/ref/pluginizeaff/?campaign=cptui-sidebar-buddypages

Maintainn
https://maintainn.com/?utm_source=Pluginize-v2&utm_medium=Plugin-Sidebar&utm_campaign=CPTUI

![image](https://cloud.githubusercontent.com/assets/367562/24460251/9d5b277c-1452-11e7-84c4-6307a93ebc1e.png)

![image](https://cloud.githubusercontent.com/assets/367562/24460257/a1c8b77a-1452-11e7-8b64-b8aa051597f6.png)

![image](https://cloud.githubusercontent.com/assets/367562/24460262/a6239416-1452-11e7-9d0b-26dbd3bc87ad.png)

![image](https://cloud.githubusercontent.com/assets/367562/24460267/a9fdcc8c-1452-11e7-858f-b66e2ff92cb9.png)

**Comment by vegasgeek** [comment]
Also, please update the URL for the "Remove These Ads?" link to be:
https://pluginize.com/plugins/custom-post-type-ui-extended/ref/pluginizeaff/?campaign=cptui-sidebar-remove

**Comment by tw2113** [comment]
Pending a completed InstaGo ad. Everything else is ready.

**Comment by vegasgeek** [comment]
![ad-instago](https://cloud.githubusercontent.com/assets/367562/24469561/b68d164c-1470-11e7-9aa9-bebb4abdf6ec.png)

New graphic.
