### ISSUE TITLE
Update post_type Field When Post Type Name is Changed

### ISSUE THREAD

**Issue by johndugan** [WebDevStudios/custom-post-type-ui#62]
Currently, if the _Post Type Name_ is changed in the Custom Post Types UI editor, all previous posts created within the custom post type remain at their original `post_type` values in the database. Because of this, it appears that all posts have been removed when a _Post Type Name_ is changed/updated. The current fix is to manually update the `post_type` value within the `wp_posts` table of the database. It would be nice if the `post_type` value were updated when the _Post Type Name_ is changed.

**Comment by tw2113** [comment]
Ended up adding this one anyway :D

**Comment by johndugan** [comment]
:-)

**Comment by tw2113** [comment]
@johndugan would love 1.1.0 feedback from you, even with it being officially released already. Help make sure that there aren't bugs with the upgrade from 1.0.x I'd have some time to fix and patch this weekend if necessary..
