### ISSUE TITLE
Remove usage of alert() and confirm()

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#620]
As per https://developers.google.com/web/updates/2017/03/dialogs-policy

**Comment by tw2113** [comment]
We'll already have jQuery UI available, may as well utilize, as a new alternative.

https://jqueryui.com/dialog/#modal-confirmation

**Comment by movingSone** [comment]
HI, is this enhancement being implemented?

**Comment by tw2113** [comment]
No, not at this point.

**Comment by movingSone** [comment]
Would it be ok if I manage this one? I kinda want to help :)

**Comment by tw2113** [comment]
I would happily accept pull requests for this one.

**Comment by movingSone** [comment]
Great, will prepare the change. And do it. Talk soon ...

**Comment by absolutelynotjames** [comment]
Hey! I know this is a minor one but if  it' still open I'm happy to take a swing at it.

**Comment by tw2113** [comment]
@absolutelynotjames I'm fine with that
