### ISSUE TITLE
Add some responsiveness to ads on about page

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#623]
On the about page, if the screen is shrunk down, the 4 ads at the bottom continue to shrink in size and eventually become unreadable. 

As the screen gets smaller, have those ads stack 2x2, and at the smallest screen size, the ads should probably be stacked 4x1

![2017-04-18_21-21-55](https://cloud.githubusercontent.com/assets/367562/25184613/ccbec0d6-24cf-11e7-96de-5a6023cf9b05.png)

**Comment by tw2113** [comment]
Pushed up into master for testing.
