### ISSUE TITLE
The Jetpack markdown doesn't work

### ISSUE THREAD

**Issue by NoahDragon** [WebDevStudios/custom-post-type-ui#630]
I followed the instruction on the post http://docs.pluginize.com/article/28-third-party-support-upon-registration , but I still could get the markdown works on CPT UI posts.

Any suggestions are really appreciated.

**Comment by tw2113** [comment]
Not sure I'm able to consistently recreate. There is part of WordPress core that handles markdown-like syntax, which may be contributing to inability to recreate.

As far as I can see, we're still properly registering the support for Jetpack's markdown, via the custom "supports" spot.

**Comment by NoahDragon** [comment]
Sorry, My bad, the setting doesn't turn on in the Jetpack. I really don't remember when I turn it off, really weird.
