### ISSUE TITLE
After theme setup create some post type and taxonimes

### ISSUE THREAD

**Issue by Ninetheme** [WebDevStudios/custom-post-type-ui#633]
Hi All

Is it possible to complete it after_theme_setup() function, because theme check plugin and envato are give notice to fix this register problem.

Thank you in patience!

All the best
faruk

**Comment by tw2113** [comment]
The codex has long recommended registering post types and taxonomies on the `init` hook, which is what we do. The `after_setup_theme` hook is run before `init` which is too early.

Can you provide more detail about what Theme Check and Envato are telling you, so that I can hopefully help address things?

**Comment by tw2113** [comment]
Any more information for me @Ninetheme  ?

**Comment by Ninetheme** [comment]
Hi

Check please : https://box.everhelper.me/attachment/1040190/84b66643-70f7-406c-9818-b0ac79dbb85e/231881-TJzcWXznz5mw40It/screen.png

There are 2 warning about tax and post_type and we can't add this in the theme files. Also when you add in any plugin not showing in CPTUI post type and taxes.

This is my code : 

`


function nt_forester_cptui_register_my_cpts() {

	/**
	 * Post Type: Portfolio.
	 */

	$labels = array(
		"name" => __( 'Portfolio', 'nt-forester' ),
		"singular_name" => __( 'Portfolio', 'nt-forester' ),
		"menu_name" => __( 'Portfolio', 'nt-forester' ),
		"all_items" => __( 'All Portfolio', 'nt-forester' ),
		"add_new" => __( 'Add Portfolio', 'nt-forester' ),
		"add_new_item" => __( 'Add New Portfolio', 'nt-forester' ),
		"edit_item" => __( 'Edit Portfolio', 'nt-forester' ),
	);

	$args = array(
		"label" => __( 'Portfolio', 'nt-forester' ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => false,
		"rest_base" => "",
		"has_archive" => true,
		"show_in_menu" => true,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => array( "slug" => "portfolio", "with_front" => true ),
		"query_var" => true,
		"supports" => array( "title", "editor", "thumbnail" ),
	);

	register_post_type( "portfolio", $args );

	/**
	 * Post Type: Team.
	 */

	$labels = array(
		"name" => __( 'Team', 'nt-forester' ),
		"singular_name" => __( 'Team', 'nt-forester' ),
		"menu_name" => __( 'Team', 'nt-forester' ),
		"all_items" => __( 'All Team', 'nt-forester' ),
		"add_new" => __( 'Add Team', 'nt-forester' ),
		"add_new_item" => __( 'Add New Team', 'nt-forester' ),
		"edit_item" => __( 'Edit Team', 'nt-forester' ),
	);

	$args = array(
		"label" => __( 'Team', 'nt-forester' ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => false,
		"rest_base" => "",
		"has_archive" => false,
		"show_in_menu" => true,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => array( "slug" => "team", "with_front" => true ),
		"query_var" => true,
		"supports" => array( "title", "editor", "thumbnail", "excerpt" ),
		"taxonomies" => array( "team" ),
	);

	register_post_type( "team", $args );

	/**
	 * Post Type: Price Table.
	 */

	$labels = array(
		"name" => __( 'Price Table', 'nt-forester' ),
		"singular_name" => __( 'Price Table', 'nt-forester' ),
		"menu_name" => __( 'Price Table', 'nt-forester' ),
		"all_items" => __( 'All Price', 'nt-forester' ),
		"add_new" => __( 'Add Price', 'nt-forester' ),
		"add_new_item" => __( 'Add New Price', 'nt-forester' ),
		"edit_item" => __( 'Edit Price', 'nt-forester' ),
	);

	$args = array(
		"label" => __( 'Price Table', 'nt-forester' ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => false,
		"rest_base" => "",
		"has_archive" => false,
		"show_in_menu" => true,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => array( "slug" => "price", "with_front" => true ),
		"query_var" => true,
		"supports" => array( "title", "editor", "thumbnail", "excerpt" ),
	);

	register_post_type( "price", $args );
}

add_action( 'init', 'nt_forester_cptui_register_my_cpts' );


function nt_forester_cptui_register_my_taxes() {

	/**
	 * Taxonomy: Portfolio Tags.
	 */

	$labels = array(
		"name" => __( 'Portfolio Tags', 'nt-forester' ),
		"singular_name" => __( 'Portfolio Tags', 'nt-forester' ),
	);

	$args = array(
		"label" => __( 'Portfolio Tags', 'nt-forester' ),
		"labels" => $labels,
		"public" => true,
		"hierarchical" => false,
		"label" => "Portfolio Tags",
		"show_ui" => true,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"query_var" => true,
		"rewrite" => array( 'slug' => 'portfolio', 'with_front' => true, ),
		"show_admin_column" => false,
		"show_in_rest" => false,
		"rest_base" => "",
		"show_in_quick_edit" => false,
	);
	register_taxonomy( "portfolio", array( "portfolio" ), $args );

	/**
	 * Taxonomy: Team Tags.
	 */

	$labels = array(
		"name" => __( 'Team Tags', 'nt-forester' ),
		"singular_name" => __( 'Team Tags', 'nt-forester' ),
	);

	$args = array(
		"label" => __( 'Team Tags', 'nt-forester' ),
		"labels" => $labels,
		"public" => true,
		"hierarchical" => false,
		"label" => "Team Tags",
		"show_ui" => true,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"query_var" => true,
		"rewrite" => array( 'slug' => 'team', 'with_front' => true, ),
		"show_admin_column" => false,
		"show_in_rest" => false,
		"rest_base" => "",
		"show_in_quick_edit" => true,
	);
	register_taxonomy( "team", array( "team" ), $args );
}

add_action( 'init', 'nt_forester_cptui_register_my_taxes' );
`

**Comment by tw2113** [comment]
This should work as a plugin as a whole: https://gist.githubusercontent.com/tw2113/4348390fd391c70de7f4d48bf865adbe/raw/3ccc48b19321c59eeac1e70173d5cdc904cfe010/gistfile1.txt

Just download as a php file and save in to your plugins folder. It'll then appear as an activateable plugin in your site. It worked for me when I tested this out.

**Comment by Ninetheme** [comment]
Yes working but after add this plugin please check CPTUI post and tax edit pages, it does not save/appear there.  Did you tested CPTUI edit post page after activate plugin?

**Comment by tw2113** [comment]
The export functionality is meant to take over from using CPTUI, so it's not a case of drop this version in a separate plugin file and CPTUI will still be able to update that area. Possibly that it was thought export was a way to change where things get saved, which isn't the case. It's more a "we're moving on, but want to retain the settings" tool

**Comment by tw2113** [comment]
If I'm still not quite right with what you were aiming for or thinking, let me know so I can try and answer best I can.
