### ISSUE TITLE
Conflict with WP Job Manager Add-on 'Applications'

### ISSUE THREAD

**Issue by mynameiskyle** [WebDevStudios/custom-post-type-ui#636]
Hey guys!

Whenever both the Custom Post Type UI and the WP Job Manager - Applications plugin are both activated, links to job listings break. Deactivating CPTUI and saving the Permalinks page for a fresh .htaccess file fixes the issue.

If I deactivate the Applications plugin, but leave the core WP Job Manager plugin active, the links work as intended.  

I'm not sure if there is anything that can be done about it, or what is causing the issue exactly but I thought I would post about it here.

**Comment by tw2113** [comment]
What post type slugs and/or taxonomy slugs do you have? I'm having a hard time imagining that just having CPTUI active would cause any issue with it, but beyond that, I can't control what users may create.

**Comment by mynameiskyle** [comment]
Thanks for the reply, Michael. 

Full disclosure, this CPTUI was added before I got a hold of the site. Im not familiar with CPTUI or really how it's useful to us currently.

Are you asking which slugs and/or taxonomy I have in the CPTUI plugin, or in Permalinks?

**Comment by mynameiskyle** [comment]
I think I figured it out. I changed the slug that WP Job Manager is using and all links are working with CPTUI activated. There appears to be a post type of 'job' in the CPTUI registered types.

**Comment by tw2113** [comment]
you should be able to see a relatively condensed overview of all the registered post types and taxonomies when you visit https://www.MYDOMAIN.com/wp-admin/admin.php?page=cptui_listings and the "Registered Types/Taxes" menu item. The "name" value in the settings column is the post type slug I was referring to earlier, with each registered type.

That said, it does sound like there was potentially a slug conflict from the site owner. Feel free to comment as needed here, but I am going to close as a non-issue.
