### ISSUE TITLE
Adding to existing top-level not working on export code.

### ISSUE THREAD

**Issue by WebVerder** [WebDevStudios/custom-post-type-ui#637]
Hi,

First of all great plugin, absolutely love it 👍 

I've got a minor problem when exporting some posttypes to code, in the outputted code there are 2 array elements "show_in_menu" & "show_in_menu_string".

The element "show_in_menu_string" contains the existing top level page set in the CPTUI settings such as "options-general.php" and the "show_in_menu" element only contains true if it was set to true in the CPTUI settings.

But whenever I set a top-level page and export it to code it doesn't get added under the top-level page but as an new top level page itself.

I checked the "register_post_type" docs and read that the "show_in_menu" element should contain this top-level slug string not the "show_in_menu_string" element, this doesn't do anything for as far as I can see.

Can you please adjust the output code so the "show_in_menu" contains the top-level slug string ?

Thanks in advance,

King regards,

Lennart

**Comment by tw2113** [comment]
Can confirm I'm doing this wrong with post types. Basically if there is a "show in menu string" value, that needs to take place of the boolean value. Will get this fixed for the 1.6.0 release. Thanks for spotting this.

**Comment by WebVerder** [comment]
> Will get this fixed for the 1.6.0 release. Thanks for spotting this.
Great stuff, glad I could help :)

**Comment by tw2113** [comment]
Re-opening as it's not quite fixed yet :)

**Comment by tw2113** [comment]
Fixed in ba20605.

Thank you for your patience as I know it's been since last summer since this was opened.
