### ISSUE TITLE
Custom-Post-Type-UI taxonomy has discontinued displaying metatagged posts

### ISSUE THREAD

**Issue by onewholistens** [WebDevStudios/custom-post-type-ui#645]
INITIAL INFO: We developed a WordPress website for our online music catalog using plugins including MDTF for our music metadata taxonomies and CPT UI in order to be able to filter through our “tracks” (post type=music). We currently need to add a new taxonomy (usages) and are having trouble getting all of our metatagged tracks to display on our site while using the search filter on the live site. All other metadata taxonomies such as genres, moods & instruments are all working fine. This newly added “usages” taxonomy isn’t fully working for some reason. We added new .php files where needed modeling the code after a corresponding taxonomy such as “moods”. We also updated all of the .php and css code where necessary for this taxonomy. It appeared that we had the new taxonomy working, but then it stopped recognizing newly metatagged tracks suddenly.

BUG DESCRIPTION: Although we appear to have correctly set up a new taxonomy using Custom Post Types UI (CPT UI) as well as Metadata Taxonomy Filter (MDTF), some of the “music tracks” (type of post) that are metatagged (using our taxonomies) are not populating on our live site. The “Track Music” (posts) for our “usages” taxonomy metatags shows that we have the correct number of tracks that were actually metatagged using our “Track Music” posts in wordpress. When looking under the taxonomy/music type “usages” and the same numbers of tracks per child category in the usage taxonomy is also properly displayed in the usages taxonomy in the MDTF widget. Here’s the catch: on our website however, we are not seeing the same number of metatagged tracks being displayed.

What could be causing our “usage” taxonomy not to display the properly metatagged tracks?

![cpt_ui-usagestaxonomy01](https://user-images.githubusercontent.com/14135090/30305247-a75a5d9a-9726-11e7-9132-ffc4ecba5612.JPG)
![dg_metadatasearchfilter](https://user-images.githubusercontent.com/14135090/30305245-a7599716-9726-11e7-8fe2-10d14022d80f.jpg)
![dg_wp-trackmusic-usages01](https://user-images.githubusercontent.com/14135090/30305246-a75a307c-9726-11e7-847c-cf028366a07c.JPG)
![mdtf_taxonomies_usages01](https://user-images.githubusercontent.com/14135090/30305244-a75927ae-9726-11e7-8ac3-4d0e0127ef13.JPG)

**Comment by tw2113** [comment]
This is all for the term archive, when viewing from the front end, correct? Perhaps an archive combination of many post types that all share common taxonomy terms? Asking because I'm curious if somewhere in the site, the post types to query for, for the taxonomy in question are being specifically set, and this new setup missed a detail like this.

Since the post types and taxonomies are being registered and able to be used, I can't really call this a bug in CPTUI itself. The issue is more from elsewhere that is trying to use that created content. Not to say I won't try to help where possible, just letting it be known.

**Comment by onewholistens** [comment]
Awesome--I figured it out. So you were right, it was the MDTF advanced setting "clear cache" that must've gotten "stuck". I have it set to clear cache daily, despite the fact it wasn't clearing. Manually clearing it just fixed the problem--thanks again!

**Comment by tw2113** [comment]
Good to hear you found a solution for this. Let us know if anything else comes up.
