### ISSUE TITLE
Сompatibility with WP 4.8.2

### ISSUE THREAD

**Issue by Xalupec** [WebDevStudios/custom-post-type-ui#649]
Hello, can you release compatibility with WP 4.8.2. My site don't work on it with your Plugin, bur I use posts and faders from it :(

**Comment by tw2113** [comment]
Hi @Xalupec 

Nothing from what I've seen in version 4.8.2 should be affecting CPTUI, especially as it was a security release only. I also haven't seen anything else come in regarding issues with this release. Not saying it's not possible, but right now it doesn't feel likely.

Perhaps going into better detail and providing screenshots of what you're seeing will help me provide some ideas and guidance for what's actually going on.

**Comment by Xalupec** [comment]
https://imgur.com/a/EQbZ2

Screen 2 is from Google(2 october), today I update WP to 4.8.2 and now my screen is like on screen 1. If I deactivate CPT my screen is like on screen 3. I'm not developer :(

**Comment by tw2113** [comment]
Looks like it's mostly an issue with Flexslider than anything else. What post types did you register with CPTUI? Possible that Flexslider is using the same slug and thus a conflict is showing up.

**Comment by Xalupec** [comment]
https://imgur.com/a/skOee

I think they are here.

**Comment by tw2113** [comment]
Yeah, those would be the ones from our plugin, but neither look like they'd be likely post types from Flexslider. Not sure what's going on otherwise, truth be told, but it's not a WP 4.8.2 compatibility issue.
