### ISSUE TITLE
PHP Warning (5.6) Invalid argument supplied for foreach() (WP 4.8.2)

### ISSUE THREAD

**Issue by joeblackburn** [WebDevStudios/custom-post-type-ui#651]
I'm getting the following PHP warning:

_[05-Oct-2017 16:24:02 UTC] PHP Warning:  Invalid argument supplied for foreach() in /home/clickitupanotch/public_html/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 342_

I tried re-saving the CPTs and Taxonomies per this thread: https://github.com/WebDevStudios/custom-post-type-ui/issues/642

but didn't help the issue. Running WP 4.8.2 and PHP 5.6.

Let me know what additional info you want from me.

**Comment by tw2113** [comment]
Line 342 is the labels foreach loop, found at https://github.com/WebDevStudios/custom-post-type-ui/blob/1.5.5/custom-post-type-ui.php#L342

Can you fill in any of the labels and hit save and see if that takes care of things?

**Comment by joeblackburn** [comment]
For all 4 custom post types I have running? I assume all labels?

**Comment by tw2113** [comment]
Any of the labels on them. Could be one each. For some reason, the passed in values aren't receiving even an empty array, once getting to line 342. Saving a single value to all 4 post types should trigger some amount of data saved and thus an array to use.

**Comment by joeblackburn** [comment]
Filling in a previously blank additional label field in each of the CPTs fixed the issue.

**Comment by tw2113** [comment]
Wish I knew how the non-existent array got through, but I'm glad to see this resolved the issue for the time being :D

**Comment by joeblackburn** [comment]
If there is any sort of plugin error log you'd like me to send, or other information, I'd be glad to.

**Comment by tw2113** [comment]
Probably not, but I appreciate the offer. :)
