### ISSUE TITLE
Issue with one of my specific taxonomy

### ISSUE THREAD

**Issue by jpmurray** [WebDevStudios/custom-post-type-ui#654]
_I'm on PHP7, WP 4.8.2. CPTUI is updated to the very last version._

So, I have a taxonomy, called `universite`.

When editing a post, I can set it, as intended, save the post and there is stays.

![screen shot 2017-10-10 at 10 04 24 am](https://user-images.githubusercontent.com/1550428/31390652-796e460c-ada2-11e7-97ce-a3a44ed0573e.png)

Problem is, as much as I save/update the post, it seems that other part of WordPress won't catch the taxonomy. For example, the post list looks like so:

![screen shot 2017-10-10 at 10 05 38 am](https://user-images.githubusercontent.com/1550428/31390732-a07a5c86-ada2-11e7-8c0b-6d2661a5d67f.png)

I didn't really cared about that, but I need to get thos taxonomy on my theme, and getting them (`$terms = get_the_terms(get_the_ID(), 'universites');`) results in an empty array.

Now I have other taxonomies and they just work perfectly fine. So I tried to add a new one, called `universite_2` and... The problem is the same! I can add to the post, but it won't show anything in the post list and getting the terms results in an empty array.

Anyone can help me shine a light on this?

**Comment by tw2113** [comment]
Can you send the Tools > Debug Info content over to me? I'm curious about slugs and values passed for some details.

**Comment by jpmurray** [comment]
@tw2113 any specific email to send it to?

**Comment by tw2113** [comment]
michael@webdevstudios would work, or just pasting the textarea contents into a reply here on GH would work too. Whichever you prefer.

**Comment by jpmurray** [comment]
Here it is then! :)

```
			
		### Begin Custom Post Type UI Debug Info ###

		Multisite:                No

		SITE_URL:                 https://phdreligion.ca
		HOME_URL:                 https://phdreligion.ca

		WordPress Version:        4.8.2
		Permalink Structure:      /%postname%/
		Active Theme:             Academy 2.6

		Registered Post Types:    post, page, attachment, revision, nav_menu_item, custom_css, customize_changeset, cours, professeur, plan, course, lesson, quiz, testimonial, slide

		PHP Version:              7.1.8-2+ubuntu16.04.1+deb.sury.org+4
		MySQL Version:            5.7.19
		Web Server Info:          nginx/1.13.3

		Show On Front:            page
		Page On Front:            Accueil (#2129)
		Page For Posts:            (#0)

		WordPress Memory Limit:   40MB

		TOTAL PLUGINS: 13


		ACTIVE PLUGINS: (11)

		Admin Menu Editor: 1.8
		Akismet Anti-Spam: 4.0
		Custom Post Type UI: 1.5.5
		Google Analyticator: 6.5.4
		Really Simple SSL: 2.5.21
		Revolution Slider: 4.6.5
		Solid Code Theme Editor: 1.1.0
		WPML Multilingual CMS: 3.1.5
		WPML Translation Management: 1.9.4
		WP Sync DB: 1.5
		WP Sync DB Media Files: 1.1.4b1

		INACTIVE PLUGINS: (2)

		Post Duplicator: 2.14
		WordPress Importer: 0.6.3

		Post Types: 
		{"cours":{"name":"cours","label":"Cours","singular_label":"Cours","description":"Ajout de cours offerts dans le cadre du doctorat","public":"1","show_ui":"1","has_archive":"1","exclude_from_search":"0","capability_type":"post","hierarchical":"0","rewrite":"1","rewrite_slug":"","rewrite_withfront":"1","query_var":"1","menu_position":"","show_in_menu":"1","show_in_menu_string":"","menu_icon":"http:\/\/phdreligion.ca\/wp-content\/themes\/academy\/images\/icons\/study.png","supports":["title","editor"],"taxonomies":["universites","session"],"labels":{"menu_name":"","add_new":"","add_new_item":"","edit":"","edit_item":"","new_item":"","view":"","view_item":"","search_items":"","not_found":"","not_found_in_trash":"","parent":""}},"professeur":{"name":"professeur","label":"Professeurs","singular_label":"Professeur","description":"","public":"1","show_ui":"1","has_archive":"0","exclude_from_search":"0","capability_type":"post","hierarchical":"0","rewrite":"1","rewrite_slug":"","rewrite_withfront":"1","query_var":"1","menu_position":"","show_in_menu":"1","show_in_menu_string":"","menu_icon":"http:\/\/phdreligion.ca\/wp-content\/themes\/academy\/images\/icons\/user.png","supports":["title","editor","custom-fields","revisions","thumbnail","page-attributes","post-formats"],"taxonomies":["universites","sujets"],"labels":{"menu_name":"","add_new":"","add_new_item":"","edit":"","edit_item":"","new_item":"","view":"","view_item":"","search_items":"","not_found":"","not_found_in_trash":"","parent":""}}}


		Taxonomies: 
		{"universites":{"name":"universites","label":"Universit\u00e9s","singular_label":"Universit\u00e9","description":"","public":"true","hierarchical":"true","show_ui":"true","show_in_menu":"true","show_in_nav_menus":"true","query_var":"true","query_var_slug":"","rewrite":"true","rewrite_slug":"","rewrite_withfront":"1","rewrite_hierarchical":"0","show_admin_column":"true","show_in_rest":"false","show_in_quick_edit":"","rest_base":"","labels":{"menu_name":"","all_items":"","edit_item":"","view_item":"","update_item":"","add_new_item":"","new_item_name":"","parent_item":"","parent_item_colon":"","search_items":"","popular_items":"","separate_items_with_commas":"","add_or_remove_items":"","choose_from_most_used":"","not_found":"","no_terms":"","items_list_navigation":"","items_list":""},"object_types":["cours","professeur"]},"session":{"name":"session","label":"Sessions","singular_label":"Session","hierarchical":"1","show_ui":"1","query_var":"1","rewrite":"1","rewrite_slug":"","show_admin_column":"1","labels":{"search_items":"","popular_items":"","all_items":"","parent_item":"","parent_item_colon":"","edit_item":"","update_item":"","add_new_item":"","new_item_name":"","separate_items_with_commas":"","add_or_remove_items":"","choose_from_most_used":""},"object_types":["cours"]},"sujets":{"name":"sujets","label":"Sujets","singular_label":"Sujet","hierarchical":"0","show_ui":"1","query_var":"1","rewrite":"1","rewrite_slug":"","show_admin_column":"1","labels":{"search_items":"","popular_items":"","all_items":"","parent_item":"","parent_item_colon":"","edit_item":"","update_item":"","add_new_item":"","new_item_name":"","separate_items_with_commas":"","add_or_remove_items":"","choose_from_most_used":""},"object_types":["cours","professeurs"]},"profs":{"name":"profs","label":"Professeurs","singular_label":"Professeur","hierarchical":"0","show_ui":"1","query_var":"1","rewrite":"1","rewrite_slug":"","show_admin_column":"1","labels":{"search_items":"","popular_items":"","all_items":"","parent_item":"","parent_item_colon":"","edit_item":"","update_item":"","add_new_item":"","new_item_name":"","separate_items_with_commas":"","add_or_remove_items":"","choose_from_most_used":""},"object_types":["professeurs","cours"]},"domaines":{"name":"domaines","label":"Domaines","singular_label":"Domaine","hierarchical":"1","show_ui":"1","query_var":"1","rewrite":"1","rewrite_slug":"","show_admin_column":"1","labels":{"search_items":"","popular_items":"","all_items":"","parent_item":"","parent_item_colon":"","edit_item":"","update_item":"","add_new_item":"","new_item_name":"","separate_items_with_commas":"","add_or_remove_items":"","choose_from_most_used":""},"object_types":["professeur"]}}


		### End Debug Info ###
```

**Comment by tw2113** [comment]
Acknowledging seeing this, and will try to get to it soon.

**Comment by tw2113** [comment]
Hmm. I have imported the settings for both the post types as well as the taxonomies. I have published a post within both, but I do see only "cours" has an archive available. I added the `$terms = get_the_terms(get_the_ID(), 'universites');` snippet to the archive.php file and WordPress loop, and it did find the term I was expecting. It's also showing the term properly within the posts list table.

Not quite sure what's going on for your specific install or why, with that said. I am using stock TwentySeventeen for my local dev site's theme, which may be detail worth considering. It's definitely possible that something in the theme is interfering, or possibly a plugin.

Is this a site still in development, or is it a live site? Curious if you can disable plugins one by one until the issue hopefully clears up. It'd help narrow down probably conflict sources.

**Comment by jpmurray** [comment]
It is a live site, and it used to work perfectly fine for the past... 3 years! The only thing that changed in the past months was an upgrade to PHP7. Then somebody noticed the problem a few days after. I upgraded my plugins to see if it wouldn't be coming from that, but no.

That being said, I'll try in the coming days to revert plugins and theme, who knows!

**Comment by tw2113** [comment]
Extremely odd. Nothing from PHP7, that I can think of, would be affecting this. Also, for what it's worth, the version I was on when I was trying things out earlier was on 7.0.3. Curious what may or may not show up in error logs.

**Comment by jpmurray** [comment]
Sadly, nothing shows up in the logs.

I'll try to recreate the site in a local environment, so I can play more with it and find what exactly is going wrong. I'll keep you posted!

**Comment by tw2113** [comment]
Thanks.

**Comment by jpmurray** [comment]
Sorry for late reply, been busy!

So I replicated everything in a local environment, and I still get the same weird behavior. I've also discovered that via the `edit-tags.php` page for the taxonomy, the counts for each of them is _not_ zero, meaning something is associated somewhere, but not showing? Puzzles me a lot!

I'm not entirely sure what we could do from here, I should probably contact you via email and give you some access so you can check for yourself, right?

**Comment by tw2113** [comment]
If you want to send some access information over, I can give it a go. The email listed above will still reach me, and could be used for an admin user as well. We can talk private details there in the email itself, instead of publicly here on GH.
