### ISSUE TITLE
how to show post type filter

### ISSUE THREAD

**Issue by kankan0082** [WebDevStudios/custom-post-type-ui#656]
how to show post type filter by taxonomies

![2b00ed63-266b-4a42-b105-1f95215adc96](https://user-images.githubusercontent.com/30918848/32593412-c588e6f0-c562-11e7-8594-8fb117bb3714.png)

**Comment by tw2113** [comment]
Hi @kankan0082 

While absolutely possible, this isn't a feature we have as part of CPTUI itself. That said, the following links may prove to be helpful in getting that type of thing set up. Note that I haven't tried them out specifically, so mileage may vary. Also one has more info than just this specific filter, so you won't need the whole article.

https://pippinsplugins.com/post-list-filters-for-custom-taxonomies-in-manage-posts/
https://en.bainternet.info/add-taxonomy-filter-to-custom-post-type/#!
https://code.tutsplus.com/tutorials/wordpress-custom-post-types-taxonomies-admin-columns-filters--wp-27898
