### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by GaryJones** [WebDevStudios/custom-post-type-ui#658]
## Currently
It appears that `changelog.txt` is used as the backup location for older release changes, while latest releases changes are kept in `readme.txt`, and duplicated in `README.md`.

## Issue
No single file contains the full list of changes. Latest changes are forgotten to be updated in `README.md` (see #657).

## Suggestions
- Have the full list of changes be documented in `CHANGELOG.md` (standard filename format). Use [Keep A Changelog](http://keepachangelog.com/en/1.0.0/) format for more standardisation.
- Have the `README.md` simply link to that document instead of including any list of changes directly.
- Copy the latest changes into `readme.txt` for the benefit of those updating from within WP admin. 
- Have it documented somewhere about how many of the latest releases i.e. "For release x.y.z, only include x.y.0 through to x.y.z in readme.txt."

It's a change of mindset, but it treats the list of changes as it should be for the _project_, and just does what's needed to cater for the fact at least some of the latest changes can also be shown for the _plugin_ inside WP admin.

**Comment by tw2113** [comment]
Related changes in b0dae7f and 95578fb
