### ISSUE TITLE
Add .gitignore for some vendor/* directories

### ISSUE THREAD

**Issue by GaryJones** [WebDevStudios/custom-post-type-ui#663]
The directories inside `vendor/` that are needed for the plugin to install / run successfully should obviously stay committed.

However, for those that are `require-dev`, like the docs check, or dependencies for PHPCS (#661) or unit tests (#662) don't need to be committed - and certainly don't need to be pushed into a zip or wordpress.org SVN. 

This will make the repo smaller, and mean not having to keep other packages code committed and up to date unnecessarily.

(`.gitattributes` may also help here so that the vendor directories are only pulled down when `--prefer-source` is used with Composer.)

**Comment by tw2113** [comment]
We very actively don't commit EVERYTHING in the github repo to the .org copy.

https://cloudup.com/c-QULyFki0R

Only ship what's needed.

**Comment by tw2113** [comment]
I think this is covered, as is. We presently ignore the entire vendor directory and don't store anything in there needed to run as a Joe User with their first time using CPTs. Anyone wanting to develop for CPTUI can run the appropriate code and have their local vendor folder.

I also added the gitattributes suggestion from #660 and that'll also help with this as a whole.
