### ISSUE TITLE
Define PHP as dependency in composer.json

### ISSUE THREAD

**Issue by GaryJones** [WebDevStudios/custom-post-type-ui#664]
It's possible to define which version of PHP is required in `composer.json`. I'm not expecting it to be the [latest](https://github.com/GaryJones/plugin-boilerplate/blob/bd9ca02455f5fc2f3b57ade0459d672b9472d392/composer.json#L25), but allowing `"php": "^5.2|^7"` does at least help specify that the plugin supports down to PHP 5.2.

If the plugin only supports later, then this can be bumped as necessary.

**Comment by tw2113** [comment]
Added as part of 7fc6611
