### ISSUE TITLE
Add .github directory with templates

### ISSUE THREAD

**Issue by GaryJones** [WebDevStudios/custom-post-type-ui#666]
See my [`.github`](https://github.com/GaryJones/plugin-boilerplate/tree/master/.github) is an example that has several GitHub-specific templates in. Having them in one place makes it even easier to exclude them via `.gitattributes`, or when pushing to wordpress.org SVN.

The templates make it easier to suggest what info is needed for Issues / PRs.

**Comment by tw2113** [comment]
Got this started with a moved CONTRIBUTING file and a new SUPPORT file. We can do further templates later as deemed necessary.
