### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by GaryJones** [WebDevStudios/custom-post-type-ui#667]
While the licence is defined in the plugin file headers and `readme.txt`, it is common to also have a specific `LICENSE` file in a project.

As can be seen [here](https://github.com/GaryJones/plugin-boilerplate/blob/master/LICENSE), GitHub handles this file in a special way, to clarify to users what exactly it can do.

This file can then be linked to from the `README.md`, like [here](https://github.com/GaryJones/plugin-boilerplate/blob/master/README.md#licensing).

**Comment by tw2113** [comment]
Fixed in bfd83a49af8a40b7586df31dd9af64b900120e4f and bff513131a7029638188cadf845f555711b59104
