### ISSUE TITLE
Add `@license` tag to file-level DocBlocks

### ISSUE THREAD

**Issue by GaryJones** [WebDevStudios/custom-post-type-ui#668]
If someone jumps straight to a file in the repo, or opens it directly from a local source, they may not know under what license the code has been provided.

Adding a `@license` tag to each file (like [here](https://github.com/GaryJones/plugin-boilerplate/blob/bd9ca02455f5fc2f3b57ade0459d672b9472d392/src/Foo.php#L8)) helps show what license is applicable.

----

For the main plugin file, you can use a format like [this](https://github.com/GaryJones/plugin-boilerplate/blob/master/plugin-slug.php#L2-L25) which allows a combination of the file-level DocBlock (including `@license`) that documentation generators want, as well as the plugin file headers that WordPress wants.

**Comment by tw2113** [comment]
added in a55906a
