### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by GaryJones** [WebDevStudios/custom-post-type-ui#669]
Here's an [example](https://github.com/GaryJones/plugin-boilerplate/blob/master/CODE_OF_CONDUCT.md) of a code of conduct, which gives contributors a bit of confidence about how the project is run.

Obviously, just adding a file means nothing, if all parties don't adhere to what's written in it, but it's a good starting point to encouraging contributors.

**Comment by tw2113** [comment]
Added via 322b9d1

Props will be granted in the readme changelogs :)
