### ISSUE TITLE
Use GPL-2.0+ instead of GPL-2.0

### ISSUE THREAD

**Issue by GaryJones** [WebDevStudios/custom-post-type-ui#671]
WordPress Core is [licensed](https://core.trac.wordpress.org/browser/trunk/src/license.txt#L8) under "GPL 2 or later" ([SPDX License](https://spdx.org/licenses/) code `GPL-2.0+`).

Now, it could be that someone wants to have a site that only uses GPLv3 plugins and themes, which means that right now, they can't use this plugin, as it is only [licensed](https://github.com/WebDevStudios/custom-post-type-ui/blob/86f99e6644d32b641158ad246cd984295b836ae3/custom-post-type-ui.php#L22) under exactly v2.

Suggestion: License this plugin the same as WP core does - GPL v2 or later.

**Comment by tw2113** [comment]
Fixed in 1b8c715
