### ISSUE TITLE
PHP Fatal error: Cannot unset string offsets

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#672]
Utilities.php file with unsetting "edit" link stuff for plugins list.

Possibly getting a string passed in instead of an array like expected.

Check for if is_array()

**Comment by officeninjas** [comment]
I also have this problem, but only on live site when logged in as admin and going to an admin page. I don't see this fatal error on my local dev site. The only difference I see is that Jetpack is in Safe Mode on my local machine. Hope this helps.

**Comment by tw2113** [comment]
Probably a similar check that I'll get added. Thanks for the feedback.

**Comment by tw2113** [comment]
c682ec2
