### ISSUE TITLE
Enhance DashIcon section to allow for dropdown list of available icons.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#678]
https://wordpress.org/support/topic/feature-requests-103/page/6/#post-9783232

If possible at all, also do a preview of the icon in being potentially selected.

**Comment by cfoellmann** [comment]
I would love to see this implemented. If one of the maintainers would give a thumbs up or something I would love to send a PR.
Opening a modal with all the icons would be the best UI, right?

**Comment by tw2113** [comment]
Part of me is curious if it could be done via jQuery/js as a whole, without fully removing/changing what we have now. Basically an addon plugin.

**Comment by cfoellmann** [comment]
I like it how the `Types` plugin does.
![2018-08-20](https://user-images.githubusercontent.com/1256090/44336035-6c9b1880-a476-11e8-9fa1-2ecefe589526.png)
![2018-08-20 1](https://user-images.githubusercontent.com/1256090/44336034-6c028200-a476-11e8-9ff6-1a30bb4dbe2b.png)

But I would keep the simple field to not remove the option to choose an icon from a custom location

**Comment by clarkewd** [comment]
I'm looking for the same thing. You're right that types has a really nice UX. You may want to check out [this codepen](https://codepen.io/laviperchik/pen/GvZZyj), and also [Hasty's dropdown](https://www.wp-hasty.com/tools/wordpress-custom-post-type-generator/) is not bad although it doesn't have the search feature:

![Screen Region 2020-04-21 at 10 16 29](https://user-images.githubusercontent.com/156377/79876565-359ea800-83b9-11ea-9534-5c6f402aba6b.png)

**Comment by tw2113** [comment]
While it doesn't look like it's going away necessarily, it looks like there's an interesting future for Dashicons.

https://make.wordpress.org/design/2020/04/20/next-steps-for-dashicons/

**Comment by arshidkv12** [comment]
Please check #821

**Comment by tw2113** [comment]
Closing as addressed in #821 above.
