### ISSUE TITLE
Custom Post Status for Custom Post Types

### ISSUE THREAD

**Issue by johndugan** [WebDevStudios/custom-post-type-ui#68]
It would be cool if this plugin would allow you to create custom post statuses for your custom post types. I understand there is currently an [issue in the WP core](https://core.trac.wordpress.org/ticket/12706) with the register_post_status function. Just curious if this is something that you plan to implement?

**Comment by GaryJones** [comment]
FTR, the core issues have still not yet been addressed.

**Comment by tw2113** [comment]
Which is why the issue remains open, and "future release"

**Comment by tw2113** [comment]
Should I leave or should I close now?

https://www.youtube.com/watch?v=xMaE6toi4mk

**Comment by tw2113** [comment]
I'm going to close this for now, until we get any sort of traction on the original trac ticket.
