### ISSUE TITLE
When the custom post type tries to get images from a post in the standard "Posts" section it returns nothing

### ISSUE THREAD

**Issue by WebSunCircle** [WebDevStudios/custom-post-type-ui#683]
Hi,

Sorry if the title of this question is a bit confusing.
I didn't know how to phrase it properly.

We have on old "Weekly Newletter" custom post type that was created a while ago by an outsourced dev team.
They used [Advanced Custom Fields PRO](https://www.advancedcustomfields.com/) to add field to the post type.

Now we are looking to update the newsletter post type without messing with the old version.
So I have created a "Weekly Newsletter - New" post type with your plugin.
I have attached the same custom fields as the old post type to the new post type.
One of the fields is a [Post Object](https://www.advancedcustomfields.com/resources/post-object/).

So the issue is:
For some reason when listing the posts that are selected in Post Object field, it will not display the featured images for the posts.
All the other content (title, excerpt, link, etc) gets displayed.
The get_the_post_thumbnail_url() and the_post_thumbnail() call returns nothing.

Just to make sure it wasnt the code, i pasted the new template code into the old "Weekly Newsletter" template file.
The images displayed perfectly.

Wordpress version: 4.9.2
Custom Post Type UI version: 1.5.6

Thanks

**Comment by tw2113** [comment]
@WebSunCircle did you get this one figured out on your own?

**Comment by WebSunCircle** [comment]
Yes, I did.

Thank You
