### ISSUE TITLE
Feature Request - Add delete link/option to the 'Registered Types/Taxes' list

### ISSUE THREAD

**Issue by garretthyder** [WebDevStudios/custom-post-type-ui#687]
Hello,

Just wanted to request the delete functionality be exposed on the 'Registered Types/Taxes' list here with the 'Edit' and 'Get code' links;
https://i.imgur.com/WId2AV1.png

Thanks

**Comment by tw2113** [comment]
This one I'm a bit less convinced with, as at least in my mind, those are just quick links to other areas in our supplied admin, and not so much an instant destructive action.

**Comment by garrett-eclipse** [comment]
Thanks Michael, in my opinion I'd find the function being exposed there as very helpful as it would reduce the amount of clicks to accomplish the task especially if you have numerous to remove.
Cheers

**Comment by tw2113** [comment]
1. Would need a nonce
2. Should get a popup prompt confirmation.
3. Possibly an inline icon related to deleting somehow to add extra warning.

Beyond that, I'm willing to roll with this one at this point.

**Comment by tw2113** [comment]
Sorry, going to bump this one to a later release.

**Comment by tw2113** [comment]
https://developer.wordpress.org/reference/functions/wp_nonce_url/

**Comment by tw2113** [comment]
@alokstha1 has anything been done with this one yet, or is it still pending any work? Asking because I may take it on myself since I want it part of the 1.13.0 release.

**Comment by tw2113** [comment]
Bumping this to 1.14.0 as i want to get what we have so far and also a new reported issue out the door

**Comment by tw2113** [comment]
Everything being done in the `687-add-delete-link` branch

**Comment by tw2113** [comment]
Due to how I'm picturing #891 going, this may actually become a key component in that, and needed.

We'll want to make sure that deleting in this fashion will NOT do any writing to the local JSON files from #891, so that we don't require restoring backups or resetting those files back to previous commits.

**Comment by tw2113** [comment]
Sorry Alok, but I moved everything to `687-add-delete-link-two` branch. Keeping what I can for your contributions, but ended up changing direction a fair amount.

This branch still needs to add modal popup confirmation for deleting.

It also needs to be tested with #891 to to help make sure that we're not deleting the JSON file when deleting in this method. I think as is we would be. We may need a flag inside `cptui_delete_post_type` and `cptui_delete_taxonomy` to prevent deleting, somehow. TBD.

**Comment by tw2113** [comment]
Hey @garretthyder Would love for a touch of extra testing from you if you're willing. Below is a link to a release build that should be install-ready with the current state of this release functionality in place. 

[custom-post-type-ui-687.zip](https://github.com/WebDevStudios/custom-post-type-ui/files/9679424/custom-post-type-ui-687.zip)

**Comment by garretthyder** [comment]
Sure thing @tw2113 give me the weekend here.

**Comment by tw2113** [comment]
Hey @garretthyder Sorry for sort of "falling off the radar" here, it was all vacation time I promise :D 

Did you have a chance to test this feature out at all?

**Comment by tw2113** [comment]
Going to close this task as finished, as it's been merged into the branch for Local JSON integration, which is still slated for 1.14.0 as well.

**Comment by garretthyder** [comment]
Sorry @tw2113  I did the same, hope you enjoyed yours. We got to the artic circle to see Polar Bears in Churchill.

Got a change to review, code looked good. Tested well two. Only comments are minor improvements that can be future iterations.

1. On the table 'Delete' it would be nice to mark it read to match the wp convention for a potentially dangerous action; #b32d2e See other row tables in wp that use trash/delete.
![Screen Shot 2022-10-26 at 3 37 36 PM](https://user-images.githubusercontent.com/8726005/198151760-fbcf14a4-60e0-4b1d-9845-9f8a95822b6e.png)

2.  Similar on the Edit screen the Delete button might do with being marked red or made into a link to match WP convention.
![Screen Shot 2022-10-26 at 3 26 57 PM](https://user-images.githubusercontent.com/8726005/198151807-2628f72d-b722-4546-9dde-41015268b67f.png)

3. Notices should e
![Screen Shot 2022-10-26 at 3 27 46 PM](https://user-images.githubusercontent.com/8726005/198151854-572047ce-30b6-4ab4-b8c4-75b2c0c9fd5f.png)
nd in periods to make them sentences.

Everything works great though, those are all just minor aesthetics.

All the best

**Comment by tw2113** [comment]
Noted and definitely good feedback. Thank.

Sounds like that was a wonderful trip too!

**Comment by tw2113** [comment]
touched up the link color and the punctuation in the 891-local-json branch

**Comment by garretthyder** [comment]
Thanks @tw2113
