### ISSUE TITLE
Feature Request - Add option to delete posts of post type being deleted

### ISSUE THREAD

**Issue by garretthyder** [WebDevStudios/custom-post-type-ui#688]
Hello,

I think it would be very useful to add an option for the 'Delete Post Type' maybe in the prompt which asks if all posts associated with the post type you're about to delete should also be removed. Checking this and deleting the post type would then purge the wp_posts table of any posts associated to the post type and purge the wp_postmeta table of any meta associated with the posts being purged.

Thank you

**Comment by tw2113** [comment]
Definitely worth considering, but at the same time I know we had at least one open issue from years ago about deleting content options as part of the uninstall process, that we passed on.

That said, this hook could be used as well.

```
/**
 * Fires after a post type is deleted from our saved options.
 *
 * @since 1.0.0
 *
 * @param array $data Array of post type data that was deleted.
 */
do_action( 'cptui_after_delete_post_type', $data );
```

Current slug would be part of the $data array. (I should probably add the slug itself as part of the arguments).

Not closing as a won't fix situation, but want to add some extra consideration. At minimum, I'll probably type up a quick docs/tutorial about using that hook to achieve the same thing.

Note for if we go with it: need to possibly amend js dialog confirmation to say data would be deleted if checked.

**Comment by garrett-eclipse** [comment]
Thanks @tw2113 that'd be awesome.

**Comment by tw2113** [comment]
I think I'm going to pass on this one overall. I still prefer retaining content over deleting it for users, and we don't get that many requests around recovering in some way, but it does come up at times.
