### ISSUE TITLE
Custom taxonomy metabox causes error in Gutenberg editor

### ISSUE THREAD

**Issue by greatislander** [WebDevStudios/custom-post-type-ui#689]
In testing CPT UI with Gutenberg, I found one incompatibility. The custom metabox that CPT UI adds does not work. A section under Extended Settings appears with the name of the taxonomy (`Custom` in the screenshot attached), but when expanded, there's an error (see below). I should note that the taxonomy appears to function properly in the native Gutenberg UI.

### Error Message

```
Warning: call_user_func() expects parameter 1 to be a valid callback, function 'post_tags_meta_box' not found or invalid function name in /Users/ned/Sites/gutenberg/wp-content/plugins/gutenberg/lib/meta-box-partial-page.php on line 227
```

### Screenshot

![screen shot 2018-03-01 at 9 15 32 pm](https://user-images.githubusercontent.com/605361/36878940-aa8d61ea-1d97-11e8-85be-b0ced69a826b.png)

### Versions & Configuration

WordPress: 4.9.4
Gutenberg: 2.2
CPT UI: 1.5.6

**Comment by tw2113** [comment]
Not sure what's going on with that, but I am not sure that's coming from CPTUI. We don't explicitly add any metaboxes, and let WP core handle all of that.

I am also not managing to recreate any section like "Extended Settings" and "Custom" with the post type i'm trying with locally. Do you know what may be helping provide those two sections?

The xdebug screenshot doesn't appear to show any part of CPTUI as well. `post_tags_meta_box` should exist in WP core, so why it's not found is a mystery to me.

wp-admin/includes/meta-boxes.php
453:function post_tags_meta_box( $post, $box ) {

**Comment by greatislander** [comment]
It appears to be a Gutenberg bug, although not one that has had much activity lately: https://github.com/WordPress/gutenberg/issues/4455

**Comment by greatislander** [comment]
Also a PR. I'm going to close this and see if I can get any traction there. Thanks! https://github.com/WordPress/gutenberg/pull/4691
