### ISSUE TITLE
Update text on help page

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#691]
Currently, at the top of the help/support page inside CPTUI there's a line of text that reads:

Please note that this plugin will not handle display of registered post types or taxonomies in your current theme. It simply registers them for you. To display your data, check out CPTUI Extended. If all else fails, visit us on the Support Forums

I want to change it to read:

Please note that this plugin will not handle display of registered post types or taxonomies in your current theme. It simply registers them for you. To display your data, check out CPTUI Extended. View our Layouts page to see some examples that are available with Custom Post Type UI Extended. If all else fails, visit us on the Support Forums

All existing links stay as is. Plus, I want to link the text that reads "View our Layouts page" to the following URL:

https://pluginize.com/cpt-ui-extended-features/?utm_source=faq-layouts&utm_medium=text&utm_campaign=cptui

**Comment by tw2113** [comment]
07a81e4
