### ISSUE TITLE
CPTs are loading very slowly bringing browser to a halt

### ISSUE THREAD

**Issue by ThePJDK** [WebDevStudios/custom-post-type-ui#693]
Hi CPT UI,
For a client I am using (a lot of) CPT UI posts - around 3000 cpts.

The posts listing is displayed by using Pro Reactive plugin shortcode on a Jupiter theme.

The listing loads evry slowly and finally halts the browser to an unresponsive state.

The CPTs are fairly simple set up.

I am still a newbie with CPT UI. What can I have missed in getting the many posts to load faster?

Thank you for your help. I using your Github - don't know where else to submit my question.

Thank you.

P.

**Comment by tw2113** [comment]
For future reference, our preferred support location is https://wordpress.org/support/plugin/custom-post-type-ui/ but I'll respond here.

There's not really anything with CPTUI that is going to help with performance here, nor are there settings related to it.

Just for clarity sake, is this 3000 post types? or is it 3000 posts within a single post type?

If it's 3000 registered post types, then WordPress is having to iterate over and register those on pretty much every single page load you make. It's understandable that things would begin to drag pretty quickly.

If that's 3000 posts in a single post type, are you querying for all of them all at once? or is it just querying for like 10 at a time? If it's trying to grab all of them, then that's also going to be a performance hit, but smaller subsets, even like 100 or so, shouldn't be that horrible unless the server isn't well optimized or performant.

**Comment by ThePJDK** [comment]
Hi Michael,

Thank you very much for your reply.

It is indeed 3000+ posts within one post type.

You’re right – it’s insane to have that kind of a load on a single page.

But; That’s what the client wants…

Thanks again and I’ll remember to use the wordpress.org forum.

Cheers

Peter Jorgensen



Med venlig hilsen

Peter Jørgensen

Mobil: 51 880 780
E-mail: thepjdk@outlook.com<mailto:thepjdk@outlook.com>


Fra: Michael Beckwith <notifications@github.com>
Sendt: 8. marts 2018 15:55
Til: WebDevStudios/custom-post-type-ui <custom-post-type-ui@noreply.github.com>
Cc: ThePJDK <thepjdk@outlook.com>; Author <author@noreply.github.com>
Emne: Re: [WebDevStudios/custom-post-type-ui] CPTs are loading very slowly bringing browser to a halt (#693)


For future reference, our preferred support location is https://wordpress.org/support/plugin/custom-post-type-ui/<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwordpress.org%2Fsupport%2Fplugin%2Fcustom-post-type-ui%2F&data=02%7C01%7C%7Cb5ed4ae40e7c4e71c06808d58504a3d8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636561177321510196&sdata=D%2Bnv2lQhzr1uht6bSGDDAPcidREXaxthb%2B0uezRh6tQ%3D&reserved=0> but I'll respond here.

There's not really anything with CPTUI that is going to help with performance here, nor are there settings related to it.

Just for clarity sake, is this 3000 post types? or is it 3000 posts within a single post type?

If it's 3000 registered post types, then WordPress is having to iterate over and register those on pretty much every single page load you make. It's understandable that things would begin to drag pretty quickly.

If that's 3000 posts in a single post type, are you querying for all of them all at once? or is it just querying for like 10 at a time? If it's trying to grab all of them, then that's also going to be a performance hit, but smaller subsets, even like 100 or so, shouldn't be that horrible unless the server isn't well optimized or performant.

**Comment by tw2113** [comment]
Closing the issue, but that doesn't mean you can't still ask some questions.
