### ISSUE TITLE
missing show_in_nav_menus in function cptui_register_my_cpts

### ISSUE THREAD

**Issue by redpik** [WebDevStudios/custom-post-type-ui#694]
On PHP code, in the `cptui_register_my_cpts()` function, the field `show_in_nav_menus` is missing.

**Comment by tw2113** [comment]
https://github.com/WebDevStudios/custom-post-type-ui/issues/593

I have it marked down for 1.6.0 however, I could easily be convinced to make it part of 1.5.8 as in a lot of ways it could be considered a bug.

**Comment by tw2113** [comment]
Closing as it has been resolved and intended for 1.5.8, hopefully released next week.

**Comment by redpik** [comment]
:+1:
