### ISSUE TITLE
Need functionality for Automated Import for CPT and taxonomies 

### ISSUE THREAD

**Issue by akhilkjuliyan** [WebDevStudios/custom-post-type-ui#695]
Is there any way to set up an automated import using the code from export option, upon activation of plugin in the themes.
what function you are using for importing , is it possible to call that function in theme and pass the import string data ,

**Comment by tw2113** [comment]
See my responses over at https://wordpress.org/support/topic/predifine-an-import-in-theme/

Thanks :D
