### ISSUE TITLE
Update sidebar links

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/custom-post-type-ui#696]
@tw2113 please update the sidebar links (see screenshot below) to use the following URLs:

https://pluginize.com/plugins/custom-post-type-ui-extended/?utm_source=cptui-sidebar&utm_medium=text&utm_campaign=cptui

https://pluginize.com/plugins/instago/?utm_source=cptui-sidebar&utm_medium=text&utm_campaign=instago

https://pluginize.com/plugins/buddypages/?utm_source=cptui-sidebar&utm_medium=text&utm_campaign=buddypages

![2018-03-23_09-05-32](https://user-images.githubusercontent.com/367562/37840129-7dfdeab2-2e79-11e8-825f-6bfcb2103df0.png)

**Comment by tw2113** [comment]
5a000da
