### ISSUE TITLE
Provide any appropriate and necessary information regarding GDPR compliance.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#702]
Closest thing we have is UTM parameters on pluginize.com links for tracking of clicks and origins for people reaching pluginize.com.

Nothing about users is tracked and stored otherwise.

**Comment by tw2113** [comment]
@vegasgeek can I get your thoughts on this one?

**Comment by davebonds** [comment]
@tw2113 I’ve had to deal with this sort of issue before, so I’ll just add my two cents: The plugin itself is not storing any user data, so we’re good. Tracking links are not prohibited and do not require consent. Custom implementations of how the plugin is used may have exceptions, but in those cases, it’s their responsibility to provide information to the Privacy Policy generator regarding their possible usage of user data through the provided WP hooks.
Maybe @vegasgeek can provide some additional insight?

**Comment by tw2113** [comment]
Good information to know. Thanks @davebonds. With this one, I just want to offer some sort of reassurance via readme file about the topic. Need to work out the verbiage for it.

**Comment by davebonds** [comment]
Indeed. Maybe just a note about: if your usage of CPTUI collects and/or stores personally identifiable information about a user, then please use the provided hooks to add your specific policy to the Privacy Policy generator.
