### ISSUE TITLE
Update or remove changelog.md 

### ISSUE THREAD

**Issue by Phoenix-One** [WebDevStudios/custom-post-type-ui#703]
The changelog.md in the main branch states:

“All notable changes to this project will be documented in this file.”

The most recent version mentioned in the changelog is 1.5.6, however 1.5.8 is available for update through the WordPress repository.

Recommend updating the changelog.md to include 1.5.7 and 1.5.8 details.

**Comment by tw2113** [comment]
https://github.com/WebDevStudios/custom-post-type-ui/commit/daf159b444f303d1e5d4e4a82801d093cbb4636a

Gonna be covered, just not done yet in master branch :D

**Comment by Phoenix-One** [comment]
Thanks for the update.  I assumed the published updates would have been from the Master branch.  Perhaps that’s something that can be explained in the changelog introduction?  I’m not a developer, and from the perspective of someone not familiar with your processes it looked like the changelog.md would have the changes for all released versions.

~f~

On Apr 25, 2018, at 7:54 PM, Michael Beckwith <notifications@github.com<mailto:notifications@github.com>> wrote:


daf159b<https://github.com/WebDevStudios/custom-post-type-ui/commit/daf159b444f303d1e5d4e4a82801d093cbb4636a>

Gonna be covered, just not done yet in master branch :D

**Comment by tw2113** [comment]
Part of it is that it's a relatively recent file and it hasn't fully gotten into my head that that one needs to be kept uptodate as well. Regarding where best to get the files, I probably should clarify that master isn't necessarily what's on wordpress.org.  I make judicious use of tagging as well, for the releases. 

Nonetheless, wordpress.org should be considered the official place, with https://github.com/WebDevStudios/custom-post-type-ui/releases being an alternative.

**Comment by Phoenix-One** [comment]
I’ll update my notes.  Thanks again!

If there’s something I can do to help out, let me know!  I’m not a stranger to coding.  Even though I’m not of any use with programming itself, I could help out with documentation (like the changelog file).

Either way, thank you very much for your time!

~f~

On Apr 25, 2018, at 9:55 PM, Michael Beckwith <notifications@github.com<mailto:notifications@github.com>> wrote:


Part of it is that it's a relatively recent file and it hasn't fully gotten into my head that that one needs to be kept uptodate as well. Regarding where best to get the files, I probably should clarify that master isn't necessarily what's on wordpress.org<http://wordpress.org>. I make judicious use of tagging as well, for the releases.

Nonetheless, wordpress.org<http://wordpress.org> should be considered the official place, with https://github.com/WebDevStudios/custom-post-type-ui/releases being an alternative.
