### ISSUE TITLE
Adjusting taxonomy capabilites

### ISSUE THREAD

**Issue by rob-gordon** [WebDevStudios/custom-post-type-ui#706]
I'm trying to adjust the custom taxonomy capabilities (not sure why that isn't available the same way it is for custom post types) but for some reason it doesn't appear to be applying my capabilities. Is there a reason this code wouldn't be working?

    function adjust_taxonomy_capabilities($args)
    {
        $args['capabilites'] = [
            'manage_terms' => 'custom_cap',
            'edit_terms' => 'custom_cap',
            'delete_terms' => 'custom_cap',
            'assign_terms' => 'custom_cap'
        ];
        return $args;
    }
    add_filter('cptui_pre_register_taxonomy', 'adjust_taxonomy_capabilities');

**Comment by tw2113** [comment]
What are you actually using for the capability slugs? Are you sure you're using the right taxonomy slug?

For example from the codex:
```
[
'manage_terms' => 'manage_categories'
'edit_terms' => 'manage_categories'
'delete_terms' => 'manage_categories'
'assign_terms' => 'edit_posts'
]
```

Also, just to make sure it's only a typo for your sample code above, are you making sure the array index is "capabilities" and not what you have above with "capabilites"? Note: you're missing the last i

**Comment by rob-gordon** [comment]
@tw2113 Thank you! It was the _capabilities_ typo. Sorry for opening an issue! Feel free to delete

**Comment by tw2113** [comment]
#easywin No worries, glad I could help
