### ISSUE TITLE
Setting 'Has Archive' to false doesn't disable the archive

### ISSUE THREAD

**Issue by garrett-eclipse** [WebDevStudios/custom-post-type-ui#709]
Hello, 

Came across this while trying to disable the archive for a custom page, the permastructure just didn't update after switching 'Has Archive' to false even with saving permalinks and cache flushing.

I found the issue was I had left a slug in the field just after the boolean toggle;
https://i.imgur.com/mAIERJv.png

I felt it would make sense to disable $has_archive completely if the toggle was set to False so am pushing in PR following this to update these lines with a $has_archive boolean check;
https://github.com/WebDevStudios/custom-post-type-ui/blob/1853a2a4915f87fe78b97193467858cff63b2335/custom-post-type-ui.php#L364

All the best,
Cheers

**Comment by tw2113** [comment]
I knew this one was sounding familiar.

https://github.com/WebDevStudios/custom-post-type-ui/commit/a22528588b46f1fab8f24cb44123dd6c42077a6c

;)

Slated to be addressed in 1.6.0 already.

**Comment by garrett-eclipse** [comment]
Awesome thanks @tw2113
