### ISSUE TITLE
The no_associated_type alert should be latched to both Tax Submits

### ISSUE THREAD

**Issue by garrett-eclipse** [WebDevStudios/custom-post-type-ui#711]
Hello,

The jQuery alert to block submit when there's no Post Type is only attached to .cptui-taxonomy-submit and should also be attached to the .cpt_submit one as well. Currently the first 'Save Taxonomy' won't trigger the alert.

Submitted a quick PR.

Cheers

**Comment by garrett-eclipse** [comment]
<img width="461" alt="screen shot 2018-06-13 at 11 08 40 pm" src="https://user-images.githubusercontent.com/8726005/41394739-f1f9ee80-6f5f-11e8-8c30-736626eee20f.png">
Speaking on this alert

**Comment by garrett-eclipse** [comment]
Looking at this further the issue isn't that another class needs to be added to the jQuery selector but that the two buttons differ on how they apply the .cptui-taxonomy-submit when $_GET['action'] == 'edit'.

Specifically speaking of the following two submit setups.

Firstly this one applies .cptui-taxonomy-submit when not in 'edit';
https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/taxonomies.php#L338

Then the lower one does apply it in edit;
https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/taxonomies.php#L881

So I guess the two buttons flip when they have the class. When in 'Add New Taxonomy' it's on the first button. And when on 'Edit Taxonomies' it's on the second button.

Is that intentional or should they both not always have the class in case the setting gets unchecked accidentally?

Let me know and I'll update the ticket/PR. 
Thanks

**Comment by tw2113** [comment]
Honestly probably just a missed detail with having two buttons and various potential states.

I'd say touch up the PR and just add the js-used class to all of the add/save primary buttons.

**Comment by garrett-eclipse** [comment]
Thanks @tw2113 I've submitted a PR with this modification. Cheers
