### ISSUE TITLE
Clarify available registered post types, provide gist or something

### ISSUE THREAD

**Issue by garretthyder** [WebDevStudios/custom-post-type-ui#712]
Hello,

The register_taxonomy function supports non-public post-types, I understand it gets messy and you don't want to display by default but wanted to clarify via verbiage and maybe a code snippet or even a toggle how to enable non-public post-types in the list.

Speaking of this list;
<img width="582" alt="screen shot 2018-06-13 at 11 37 07 pm" src="https://user-images.githubusercontent.com/8726005/41395476-b262f7a0-6f62-11e8-9c9b-11ecf846ce2e.png">

To enable non-public post types you just wipe out the args array in the `cptui_attach_post_types_to_taxonomy` filter;
https://gist.github.com/garrett-eclipse/e263baf4e49ab6e1ae433995f1685d89

Was thinking for the text;
"Add support for publicly registered post types. At least one is required. To enable non-public post types see ...'

Thoughts?
Thanks

**Comment by tw2113** [comment]
Honestly don't get this topic super frequently enough to feel need to mention and bring up in that spot. I'd be much more inclined to add a page about it to the CPTUI section of https://docs.pluginize.com/ which is our docs/quick tutorial area for a lot of our products.

**Comment by tw2113** [comment]
Related, instead of creating a custom function just to return an empty array, I recommend the following callback which is provided as part of WP core:

```
add_filter( 'cptui_attach_post_types_to_taxonomy', '__return_empty_array' );
```

All sorts of interesting goodies found in wp-includes/functions.php

**Comment by garrett-eclipse** [comment]
Thanks @tw2113 didn't know about that function good stuff.

And I'll leave it to you as to where to disclose the info for enabling non-public posts. But am thinking it would be nice to mention it within the plugin UI as I was confused at first when I updated the post-type to non-public and then found it vanished and when saving I got the following alert blocking my update which I'm glad it did as it may have wiped the setting.
<img width="461" alt="41394739-f1f9ee80-6f5f-11e8-8c30-736626eee20f" src="https://user-images.githubusercontent.com/8726005/41431336-763da8b4-6fc7-11e8-966e-17785d05da7b.png">

So it might be nice to indicate something about public/nonpublic post-types either in the help text or the alert, but I'll leave that to you.

All the best,
Cheers

**Comment by tw2113** [comment]
Leaving open because I want to consider deeper docs soon.

However, I did add 68f3185

**Comment by garrett-eclipse** [comment]
Thanks @tw2113 greatly appreciated

**Comment by garrett-eclipse** [comment]
Hi @tw2113 
I needed the opposite of this and realized your commit only covers inc/taxonomies.php. Could we also apply the same type of verbiage to the inc/post-types.php here;
https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/post-types.php#L1059

And if anyone browses this post the opposite to the `cptui_attach_post_types_to_taxonomy` filter is `cptui_attach_taxonomies_to_post_type` and the similar filter would be;
```
add_filter( 'cptui_attach_taxonomies_to_post_type', '__return_empty_array' );
```

Thanks
