### ISSUE TITLE
Clarify FAQ for supports from other third party plugins

### ISSUE THREAD

**Issue by kesenwang** [WebDevStudios/custom-post-type-ui#720]
Hey sorry so I just started to check out this plugin today but I feel the FAQ, is actually really lacking and doesn’t provide much documentation for plugin features unless there’s somewhere else on your website that I haven’t seen. 

[https://docs.pluginize.com/article/28-third-party-support-upon-registration](https://docs.pluginize.com/article/28-third-party-support-upon-registration)

For example instructions on Adding post type support for specific features from other plugins, like there’s not any actual instructions, it’s specific instructions for Genesis, jet pack and instant Articles? I don’t get how that answer the topic question, rather then just leave me more puzzled, I’m looking how to add those supports for any plugin and what we should be entering there but there’s not really any documentation...

**Comment by tw2113** [comment]
With that spot, and it probably needs to be clarified a bit more, is that if a given plugin says "add 'some-value' into the 'supports' portion of a post type registration", then this is the spot to do it in, with regards to CPTUI. It's not an open ended thing that will allow you to add any feature you can dream up and have ready, it's more specific to how other plugins handle their own support during post type registration.

At least thus far, this is the list of items we know about that use the "supports" part of post type registration. I don't doubt there's more, but we're simply not aware of them at the present time. If we were to be informed of more, we'd expand on the content at that link to include them.

Hope that makes sense.

**Comment by tw2113** [comment]
Updated with a bit more clarification.
