### ISSUE TITLE
How to display a Custom Post Type

### ISSUE THREAD

**Issue by Jump-Starx** [WebDevStudios/custom-post-type-ui#721]
Hi,

I have tried many times to catch variables in an array, to refresh permalinks but nothing appears. Just the title and blank page afterwards.
I use CPT UI with Custom Fields.

If anyone could help me to display the labels that i've created.

Thanks a lot !

![screen_1](https://user-images.githubusercontent.com/28926403/45043466-84c18900-b06d-11e8-86b4-be502d53e34c.PNG)

![screen_2](https://user-images.githubusercontent.com/28926403/45043467-85f2b600-b06d-11e8-9919-e7b26fce6fe9.PNG)

**Comment by tw2113** [comment]
Not quite following where things are failing for you. Sorry.

Is this something with regards to viewing a given post on the frontend? Working on and editing a post in your WP admin? Setting up a post type in CPTUI's settings area?

**Comment by Jump-Starx** [comment]
Hi,

Thanks for the response.
I just want to display labels that i've made and fill (first picture), and yes it concerns a display on the front-end.
As you see nothing displayed (second picture)

![screen_1](https://user-images.githubusercontent.com/28926403/45060904-5f02a700-b0a2-11e8-9839-0d48b234ab9a.PNG)
![screen_3](https://user-images.githubusercontent.com/28926403/45061007-cfa9c380-b0a2-11e8-891a-7dcba5955e8c.PNG)

**Comment by tw2113** [comment]
Looks like a PHP error is occurring in your template files that's preventing anything else from being rendered.

If you want I can look at that, but i'd need it shared via a github gist or some other method. Beyond that, there's nothing we can do with regards to CPTUI for this.

**Comment by tw2113** [comment]
Closing as it's not an issue with CPTUI itself, but we can keep discussing afterwards anyway.

**Comment by Jump-Starx** [comment]
Yeah sure, what do you need as folders or files ?

**Comment by tw2113** [comment]
Any theme files you've been working on for this post type you've created, really. Especially `single-flats.php` (Guessing the post type slug based on earlier screenshots).

**Comment by Jump-Starx** [comment]
Here it is, this is the single-flats.php (I use divi theme) : 

`<?php
get_header(); ?>

<div id="container">
	<div id="content" role="main">
	
	

	<?php if ( have_posts() ) while ( have_posts() ) : the_post(); ?>

		<div id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
			<h1 class="entry-title"><?php the_title(); ?></h1>

			<div class="entry-content">
				<?php the_content(); ?>
				<?php wp_link_pages( array( 'before' => '<div class="page-link">' . __( 'Pages:', 'Divi' ), 'after' => '</div>' ) ); ?>
			</div>


			<div class="entry-utility">
				<?php edit_post_link( __( 'Edit', 'Divi' ), '<span class="edit-link">', '</span>' ); ?>
			</div>
		</div>

	
	
	
		<?php
			// Contrôler si ACF est actif
			if ( !function_exists('get_field') ) return;
		?>
	
		<ul>
			<li><strong>Description: </strong><?php the_field('description'); ?></li>
			<li><strong>Bedrooms: </strong><?php the_field('bedrooms'); ?> personnes</li>
			<li><strong>Bathrooms: </strong><?php the_field('bathrooms'); ?></li>
			<li><strong>Minimum rental: </strong><?php the_field('minimum_rental'); ?></li>
			<li><strong>Availibility: </strong><?php the_field('availability'); ?></li>
			<li><strong>Distance: </strong><?php the_field('distance'); ?></li>
			<li><strong>Address: </strong><?php the_field('address'); ?></li>
			<li><strong>Price: </strong><?php the_field('price'); ?></li>
			<li><strong>Pictures: </strong><?php the_field('pictures_of_the_flat'); ?></li>
		</ul>


	

	<?php endwhile; // end of the loop. ?>

	</div>
</div>

<?php get_sidebar(); ?>
<?php get_footer(); ?>`

**Comment by tw2113** [comment]
Hmm, not seeing anything that would output the byline that is appearing in the screenshots. It seems to stop right after "Aug 16, 2018 |"

**Comment by Jump-Starx** [comment]
Yes i saw that, it corresponds to the title that i put (see the picture)
![screen_4](https://user-images.githubusercontent.com/28926403/45066971-38a03400-b0c1-11e8-83f2-68b819e61d8b.PNG)

**Comment by Jump-Starx** [comment]
The signature corresponds to this
![screen_4](https://user-images.githubusercontent.com/28926403/45067115-e3185700-b0c1-11e8-9dd1-4e7b0c505987.PNG)

**Comment by tw2113** [comment]
we're still going to need to look at a template that has the byline code in it, and the single-flats.php file doesn't have that, so we're looking at the wrong spot right now.

**Comment by Jump-Starx** [comment]
I see but is the byline code in a specific folder of the template or something else ?

**Comment by tw2113** [comment]
no idea, I can only guess what files you may or may not have and where it's coming from. Based on common files for custom post types, it could be a part of archive-flats.php or using non-CPT specific files and similar.

**Comment by Jump-Starx** [comment]
I didn't created an archive-flats file, do i need to create one and paste it where single-flats.php is ? 
And if yes, what should i put inside ? 

![screen_4](https://user-images.githubusercontent.com/28926403/45068026-e9a8cd80-b0c5-11e8-83f5-c998f5a681ab.PNG)

**Comment by tw2113** [comment]
No, it's not a required file to make, and you wouldn't replace single-flats.php with it either.

At this point, I don't know how much help I'm going to be, and it's definitely a theme integration issue rather than an issue with CPTUI itself. As a whole, my bets are some sort of php error is occurring in whatever template file is being used for this view in the website, but I simply don't have any access to effectively debug it.

**Comment by Jump-Starx** [comment]
Thank you for targeting the problem. 
You've been a great help.
I'll try to fix this template problem, I'll let you know.
