### ISSUE TITLE
Feature request: Taxonomy Images

### ISSUE THREAD

**Issue by zaccety** [WebDevStudios/custom-post-type-ui#723]
Would be useful to be able to attach an image to a taxonomy, and specify one for each of its terms rather than relying on an additional plugin to do this.

**Comment by tw2113** [comment]
Definitely a nice thought, and a "nice to have" but I'm not sure this is a "need to have" in terms of the core plugin. Internally I think this idea would end up being moved to its own extension, at which point there are already a fair amount of other plugins that handle the topic well enough or better than what we'd end up doing. At least personally, I also like to and want to help promote other plugins when I can, especially when I know they're a quality one.

We appreciate the idea, the feedback, and you submitting for consideration, by all means. Thank you for that.

**Comment by zaccety** [comment]
Thanks for the reply, and I understand your points.

In case anyone else looks at this thread, I've just realised that the Advanced Custom Fields Pro plugin allows you to add additional fields to taxonomy terms.
