### ISSUE TITLE
Set 'default featured image'

### ISSUE THREAD

**Issue by cfoellmann** [WebDevStudios/custom-post-type-ui#725]
I need to set a 'default featured image' for each post type.
An option is the plugin https://wordpress.org/plugins/default-featured-image/ which out of the box only supports setting one image for all posts (any post type).

I would like to suggest adding an action to the CPT UI which can be used to extend the functionality to create a post type. This way plugins (devs "by hand") can extend the options for a CPT.

Would you be open for that?
I think the author of the "Default Featured Image" plugin would be open to hooking into this.

**Comment by cfoellmann** [comment]
I need an action to add a field to the creation/edit form so I can select an image from the library.
I think it would even be a nice addition as a feature to cpt ui but it just is outside of the core cpt registration api

All this would „just“ save me the need to create a UI for the other plugin listing all cpts + the ability to set the images there.

**Comment by tw2113** [comment]
I'm thinking we probably have most, if not all, of what you need already.

For example, our CPTUI-Extended premium plugin adds its own fields to the add/edit screens for post types/taxonomies, and I also use the same ideas in this plugin here https://github.com/tw2113/custom-post-type-ui-capabilities

I can't give access to a copy of Extended, but, the link I provided to my own repo should do just fine as an example of how to accomplish what you need, or at minimum get started.

**Comment by cfoellmann** [comment]
Perfect. Looks like that should be enough to do what I want

**Comment by tw2113** [comment]
Closing as a non-issue, but feel free to continue commenting if/when necessary.
