### ISSUE TITLE
Add new post type labels for WP 5.0

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#737]
Wait until 5.0 is our minimum version supported.

https://make.wordpress.org/core/2018/12/05/new-post-type-labels-in-5-0/

**Comment by garrett-eclipse** [comment]
Was just coming here to request this, thanks for being on top of things Michael

**Comment by tw2113** [comment]
gonna make the supported version bump a part of 1.7.0. Gonna stick with just 5.0 instead of all the way to 5.2 to give a bit more time for people to upgrade core.

**Comment by tw2113** [comment]
3 months later, and i'm saying we're going to bump to 5.2 minimum WP.

**Comment by tw2113** [comment]
Added in c63c3d7
