### ISSUE TITLE
Maybe it's better to not use CDN

### ISSUE THREAD

**Issue by cloudinstone** [WebDevStudios/custom-post-type-ui#738]
Maybe it's better to not use CDN, for example: http://s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js, it will make admin settings page very slow for specific regions of users can't connect to CDN file, like China.

**Comment by tw2113** [comment]
Are you thinking we should utilize a local copy of the file? or perhaps find a way to not use at all in those cases?
