### ISSUE TITLE
Trying to utilise cptui_third_party_post_type_import

### ISSUE THREAD

**Issue by orangecactus** [WebDevStudios/custom-post-type-ui#742]
Hi

Trying to use the filter cptui_third_party_post_type_import to be able to create some CPT via a theme I am building but I cannot get it to fire?  I have tried the solution in #289 but it still does work. Could you please advise.

Thanks
Tom

**Comment by tw2113** [comment]
What's your code that you're using for this and do you have a sample blob to test importing?

Some off the top of my head troubleshooting thoughts. Are you sure you're successfully reading the json content you're meant to be importing? Also is it JSON data and not serialized data?
