### ISSUE TITLE
When Edit Custom Taxonomy Only Show 2 Level of Category

### ISSUE THREAD

**Issue by ezani92** [WebDevStudios/custom-post-type-ui#743]
Hello, THanks for great plugin. but i have an issues here

https://imgur.com/PrrIifH
(When create new post  all tree are showing)

https://imgur.com/dGoMqvk
(When editing only 2 level are showing)

can someone know what is my problem. i done goggling and cant find any solution

**Comment by tw2113** [comment]
Are the ones from the tree listed further down in the listing by chance? Have you done any customizations to the metabox showing the terms?

Last I knew, by default, WP shows you the post's selected terms at at top, with all the available ones below it.

We don't do anything to that metabox for the users, for what it's worth, so it should be doing all default behaviors.

**Comment by ezani92** [comment]
> Last I knew, by default, WP shows you the post's selected terms at at top, with all the available ones below it.

This comment has solve my issues. thanks!

**Comment by tw2113** [comment]
Glad I could help :)
