### ISSUE TITLE
Warning after importing

### ISSUE THREAD

**Issue by laurengriffin** [WebDevStudios/custom-post-type-ui#745]
"Warning: Invalid argument supplied for foreach() in /app/public/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php on line 352 Warning: in_array() expects parameter 2 to be array, null given in /app/public/wp-content/plugins/custom-post-type-ui/inc/utility.php on line 898"

I imported a post type from a previous website and I got this error from the plug-in. I'm trying to delete the post type but it doesn't have a name or any information so it won't let me delete it. I tried uninstalling and installing the plug-in in hopes that it would give me a clean start but I'm still getting this warning. 

Do you have any suggestions as to what I should do to remove this?

**Comment by tw2113** [comment]
Is this a persistent issue or was it just a one time thing?  The line of code in question is this:

```
if ( in_array( 'post-formats', $type['supports'], true ) ) {
```
Purpose of the overall code here is:

"Add missing post_format taxonomy support for CPTUI post types.
Addresses bug wih previewing changes for published posts with post types that have post-formats support."

However, your error above is indicating that the $type['supports'] index is null/non-existent. 

If you provide the JSON data in the Tools > Post Types setting page, we can get the JSON cleaned up enough to remove the post type you're wanting to delete and get updated settings imported.

**Comment by laurengriffin** [comment]
I imported a post type from a different plug-in that stores data differently so I think it's just not working well with this plug-in. 

The JSON data in the Post Types setting is:
[{"key":"group_5c7564629b1bc","title":"Providers","fields":[{"key":"field_58885344881f4","label":"Details","name":"details","type":"wysiwyg","instructions":"","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"default_value":"","toolbar":"full","media_upload":1,"tabs":"all","delay":0}],"location":[[{"param":"post_type","operator":"==","value":"approvedproviders"}]],"menu_order":0,"position":"normal","style":"seamless","label_placement":"top","instruction_placement":"label","hide_on_screen":[],"active":true,"description":""}]

**Comment by tw2113** [comment]
Ahh, that actually makes a lot more sense. That looks like it's Advanced Custom Field data, or at least rather similar.

We don't actually have any import support outside of CPTUI -> CPTUI between sites.

So for your case, it's probably going to be a case of re-creating manually to match settings as best possible. In terms of the JSON above, I'm not actually seeing much for post type parameters that would adjust how they're registered. That looks more like a field group that is used only when editing a "approvedproviders" post type. 

If you want/need to start fresh, we have a few ways to do this, that we have documented at https://docs.pluginize.com/article/20-resetting-cptui-settings I would probably recommend most the 3rd option with the "Delete from the Import/Export page" heading.

**Comment by laurengriffin** [comment]
That worked! Thanks so much

**Comment by tw2113** [comment]
Welcome.
