### ISSUE TITLE
Undefined index publicly_queryable

### ISSUE THREAD

**Issue by garretthyder** [WebDevStudios/custom-post-type-ui#747]
Hello,

I'm using CPTUI v1.6.1 and am finding the following PHP Notice;
PHP Notice:  Undefined index: publicly_queryable in /wp-content/plugins/custom-post-type-ui/inc/taxonomies.php on line 616

Looking at the line of code it's not checking that $current isset before tryign to retrieve publicly_queryable off of it;
`$select['selected'] = ( ! empty( $selected ) ) ? $current['publicly_queryable'] : '';`
Reference - https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/taxonomies.php#L616

Should probably be;
`$select['selected'] = ( ! empty( $selected ) && isset( $current ) ? $current['publicly_queryable'] : '';`

Scanning the code theres a few lines that could check $current isset;
https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/taxonomies.php#L600
https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/taxonomies.php#L616
https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/taxonomies.php#L656
https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/taxonomies.php#L676
https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/taxonomies.php#L696
https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/taxonomies.php#L716
https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/taxonomies.php#L745
https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/taxonomies.php#L774
https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/taxonomies.php#L794
https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/taxonomies.php#L814
https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/taxonomies.php#L837
https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/taxonomies.php#L873

Also wondering if disp_boolean should be used on all of the above lines as well.

THanks

**Comment by tw2113** [comment]
It simply needs to be done, but I would kind of like to move to perhaps a helper function to pass the variable into, and simply return the end result, utilizing something like https://www.php.net/manual/en/function.filter-var.php

This is especially true with the WP5.2 dropping old PHP, there's room to improve our codebase.

**Comment by tw2113** [comment]
Curious if this is one from an upgrade as opposed to a new/fresh install.

**Comment by garrett-eclipse** [comment]
Hi @tw2113 sadly I can't recall it's been a while and alot of projects since. If I can determine that will let you know.

**Comment by tw2113** [comment]
Sounds good. Thanks.

**Comment by tw2113** [comment]
I think I'm going to close this one for the time being, and if it comes up again in the future, we can re-investigate at that time with that state of the code.
