### ISSUE TITLE
CPT archive link states 'View Posts' unless 'View Items' field filled in

### ISSUE THREAD

**Issue by garrett-eclipse** [WebDevStudios/custom-post-type-ui#749]
Hello,

It seems there's a minor but on CPT listings for the 'View Posts' link. If you have a CPT but don't specify the 'View Items' it still states 'View Posts' instead of using the plural string to replace this.

Would be nice if you didn't have to set 'View Items' and it would just utilize the Plural form to create the string.

Thanks

**Comment by tw2113** [comment]
Marking as code QA, since it's not actually breaking anything, it's all labels.

**Comment by garrett-eclipse** [comment]
Thanks @tw2113 for sure nothing broken. Just would be nice to not have to fill in the field and have it automatically take the plural string. Cheers

**Comment by tw2113** [comment]
@garrett-eclipse  can you clarify where you're seeing this ? I'm not managing to find a case of a linked "View Posts"

**Comment by garrett-eclipse** [comment]
Hi @tw2113 this appears in the Toolbar when viewing the CPT list in the backend and links to the archive for that CPT.
<img width="141" alt="Screen Shot 2019-08-09 at 1 10 43 PM" src="https://user-images.githubusercontent.com/8726005/62806275-41ef0900-baa7-11e9-8978-7eb701377a35.png">
*You have to enable Archive on the CPT to have the link appear. In the above example my CPT is case (Cases / Case).

**Comment by tw2113** [comment]
I wonder if that's from a not yet released in CPTUI label that 5.0+ has. Regardless, will check on. Thanks for the pointer.

**Comment by tw2113** [comment]
Upon extra looking, I have a feeling that this is expected and the default behavior. There's definitely a number of spots that will fall back to "post" or "page" if zero custom label is provided.

I'm going to close as a won't fix, unless someone can provide any information that proves me incorrect.

**Comment by garrett-eclipse** [comment]
Hi @tw2113 I created a PR to address this in #759 would love your review. I was going to re-open this but don't have that ability. Thanks

**Comment by tw2113** [comment]
Fixed in https://github.com/WebDevStudios/custom-post-type-ui/commit/76435a25c3fc8dfae5fc8df11bcfd63d07e02e4a
