### ISSUE TITLE
3rd party addon: Save to file and sync

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#750]
Coupling with https://docs.pluginize.com/article/84-save-cptui-settings-data-to-file

Integrate UI and functionality to sync/read from found files that update the options in the plugin.

Very very much like ACF offers. Take the doc code we have above, add in the new UI/reading, and create a complete addon

**Comment by yangkennyk** [comment]
+1 would be useful for keep local + server data in sync. currently I'm either doing a DB push or manually updating with the php export

**Comment by tw2113** [comment]
Related: #879

**Comment by tw2113** [comment]
Removing this one from 1.14.0 as I re-read the issue title and realized I meant it to be an addon, and not part of the core plugin.

**Comment by tw2113** [comment]
Closing this because of #891 which is exactly the same thing here, and that enhancement issue has a lot more details at this point.

To be clear, this is in the works and planned, and not as a 3rd party addon.
