### ISSUE TITLE
Post Install: Update paragraph around Gutenberg and WP 5.0

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/custom-post-type-ui#751]
This needs to be updated.

![screenshot](https://dl.dropbox.com/s/34wa84jp1deqjks/Screenshot%202019-05-15%2011.41.09.png?dl=0)

**Comment by tw2113** [comment]
Definitely will be whenever we get to a 1.7.0 release. We traditionally haven't been updating these spots for the security/bugfix releases. Just happens that we released 1.6.0 in October and 5.0 came in December.

**Comment by tw2113** [comment]
Fixed in 80b4e6d
