### ISSUE TITLE
Add a link to Dashicons

### ISSUE THREAD

**Issue by JulieKuehl** [WebDevStudios/custom-post-type-ui#752]
Until you can get to the requested feature of having a dropdown list of available Dashicons, a link to the Dashicons site would be helpful.

I suggest in the Menu Icon area of the /wp-admin/admin.php?page=cptui_manage_post_types where the label reads "Image URL or Dashicon class name to use for icon. Custom image should be 20px by 20px." that the words "Dashicon class name" be made a link to https://developer.wordpress.org/resource/dashicons/

![dashicons-link](https://user-images.githubusercontent.com/1095701/59160958-e520a380-8aa1-11e9-9d05-d6bb916b3eeb.png)

**Comment by tw2113** [comment]
I see no issue with this idea. Thanks for the feedback Julie :D

**Comment by JulieKuehl** [comment]
Give me a day or two and I can submit a PR if you'd like.

**Comment by tw2113** [comment]
Sure. PR against the `release170` branch when you do.

**Comment by tw2113** [comment]
Merged in, but I did touch it up a little bit. Still will give you credit though :)

**Comment by JulieKuehl** [comment]
Oooh! Interesting. Thanks for the lesson - and the credit. You're the best!
