### ISSUE TITLE
WordPress additional CSS doesn't work on Custom Post Types.

### ISSUE THREAD

**Issue by JosiahHumphrey** [WebDevStudios/custom-post-type-ui#775]
Using WordPress's built in additional CSS option in the editor, I can't get custom CSS to work on custom post types. 

The css I'm using is for switches the CSS based on the @media (prefers-color-scheme:dark) rule. You can see this working here:
https://bakudex.com/index/

But not here:
https://bakudex.com/cards/absorb/

I'm not sure how I would go about fixing this.

Anyone interested in the CSS can view it here:
https://pastebin.com/HXHAdv7i

**Comment by tw2113** [comment]
Which aspect of the CSS isn't working?

I also don't have a new enough version of OSX to have prefers-color-scheme affect me, so if that's part of it, then I'm less useful than I intend.

Beyond that, there's no aspect of CPTUI that should be affecting anything CSS wise, we're a very behind the scenes plugin.

**Comment by tw2113** [comment]
Hey @JosiahHumphrey can you provide some extra clarity above?

**Comment by tw2113** [comment]
Closing due to lack of information and possible non-conflict with CPTUI itself
