### ISSUE TITLE
Update newsletter signup to EmailOctopus

### ISSUE THREAD

**Issue by williamsba** [WebDevStudios/custom-post-type-ui#776]
We're switching newsletter services to EmailOctopus. We need to update the newsletter signup form in the plugin sidebar to use the new server.

Here's a gist of the code generated for the form. Feel free to adjust so it fits/works within the plugin sidebar and about page.

https://gist.github.com/williamsba/c76c157f15e92c18b059eadb6bc94507

The newsletter form is currently located in two spots:

**Add/Edit Post Types and Taxonomy Submenus**
![Screen Shot on 2020-02-04 at 12-42-42](https://user-images.githubusercontent.com/484024/73771264-0b3f3600-474c-11ea-8b0a-17bb2def646d.png)

**About CPT UI**
![Screen Shot on 2020-02-04 at 12-44-57](https://user-images.githubusercontent.com/484024/73771429-5ce7c080-474c-11ea-9f75-5cb227a2bdaf.png)

**Comment by tw2113** [comment]
Merged in with #777
