### ISSUE TITLE
Get code -tools wrong value for "publicly_queryable"

### ISSUE THREAD

**Issue by iraudasoja** [WebDevStudios/custom-post-type-ui#778]
Exporting PHP-code for post types and taxonomies outputs always a value "false" for a key "publicly_queryable".

Reproduced by:
- Edit post type
- Set publicly_queryable to "true"
- Go Tools > Get code
-> Produced PHP code gives a value "false" for a key "publicly_queryable".

Same steps also for taxonomy.

Also, the key "publicly_queryable" is missing for the listing of Registered Types/Taxes menu.

Tested with CPT-UI version 1.7.3

**Comment by tw2113** [comment]
Not managing to recreate this @iraudasoja but I'm not denying that you may be experiencing it. It's just a question of why.

Are these older content types that you registered a long time ago? Or are they newly created ones?

The two spots in question are dependent on the options being saved to the options table, so I'm also curious what may be in those. You can get a JSON version of those via the Tools menu.

**Comment by iraudasoja** [comment]
Thank your for your reply. 

Yes they are the old ones. The problem was solved when I edit the post type and save it again.

**Comment by tw2113** [comment]
Glad to hear it was an easy enough fix. Let us know if anything else comes up.
