### ISSUE TITLE
After plugin activate page blank

### ISSUE THREAD

**Issue by rahulkathet** [WebDevStudios/custom-post-type-ui#785]
After plugin activate Wordpress frontend and backend both are blank.

**Comment by rahulkathet** [comment]
I am using PHP version 5.6.40

**Comment by tw2113** [comment]
Without some sort of error log readout, I'm not going to be able to help much. Impossible for me to say at the moment. If you can get something from that, I'll happily look it over and provide some thoughts.

**Comment by rahulkathet** [comment]
Hey, 
I have got the issue, there was some missing functions. have resolved it.

**Comment by tw2113** [comment]
Awesome, thanks for letting us know :)
