### ISSUE TITLE
Nonce check breaks wp-cli cptui import

### ISSUE THREAD

**Issue by dale42** [WebDevStudios/custom-post-type-ui#789]
On a fresh _WordPress_ install with the latest _Custom Post Type UI_ plugin, the WP-CLI **_cptui import_** command no longer works.

Command:

```
wp cptui import --type=post_type --data-path=cptui-post-types.json
Error: The link you followed has expired.
```

I think it's the nonce check that is doing it. For me the failure happens in the function _cptui_import_types_taxes_settings_, when _check_admin_referer_ is called. It appears $_REQUEST is empty so the function fails the check.

**Comment by tw2113** [comment]
Hi @dale42 

Interesting, and something I'm going to need to check on to see how to potentially resolve. On the flip side, I'm tickled pink that someone is making use of the WP-CLI integration I did up. That's very cool to see.

**Comment by tw2113** [comment]
Can't promise it will get released super soon, but I found that this is looking to work and allow for both CLI support as well as still making use of the nonce for admin usage.

```
$doing_wp_cli = ( defined( 'WP_CLI' ) && WP_CLI );
if ( ! $doing_wp_cli && ! check_admin_referer( 'cptui_typetaximport_nonce_action', 'cptui_typetaximport_nonce_field' ) ) {
	return 'nonce_fail';
}
```

**Comment by dale42** [comment]
@tw2113 I often do scripted site builds when I'm experimenting with content imports on new sites. It's nice being able to reset everything and rebuild fresh. This is definitely a nice feature. Thanks.

**Comment by tw2113** [comment]
Welcome. :)

**Comment by tw2113** [comment]
Just pushed up version 1.8.1 which includes my fix above.
