### ISSUE TITLE
Export/import of taxonomies fails, crashes my demosite.

### ISSUE THREAD

**Issue by oldrup** [WebDevStudios/custom-post-type-ui#790]
Hey!

I'm attempting to export/import 4 taxonomies from one site to another, and I fail miserably.

Never done that before, so that might be me doing it wrong, but I *think* its a bug?

Made a 1½ minute screencast https://www.youtube.com/watch?v=5JTUquLjtvc&feature=youtu.be

Please let me know, if there is anything I can do to troubleshoot this issue.

Stay safe"
Bjarne

**Comment by tw2113** [comment]
Responded initially over at https://wordpress.org/support/topic/several-errors-after-export-import-taxonomies/#post-13328632 for the moment. If we find that I need to take care of some parts at the code level, I'll move that back over to this GH issue.

**Comment by oldrup** [comment]
Thanks for the response. My reply on wp.org is stuck in the moderation queue. I accidentally attempted to import custom **taxonomies**, as a custom **post type,** so, totally my fault.

Have a great weekend!

**Comment by tw2113** [comment]
Been there! So you're not the first. Thanks for the update.
