### ISSUE TITLE
I've messed up and I need help urgently

### ISSUE THREAD

**Issue by cessholden** [WebDevStudios/custom-post-type-ui#792]
I've a dev site which is  going live first thing tomorrow. I had 20+ custom post types. I wanted to create a 21st and I stupidly imported just that post type. So guess what, I have lost all the other post types. And their data! My last back up is 22 hours ago, but I've done 22 hours worth of work on the site that I'll lose if I go to the backup. And of course I've made a ton of changes to the data itself.

Any ideas how I can get the data back without going to the backup?

Any help very gratefully received.

**Comment by tw2113** [comment]
Regarding getting CPTUI settings back, I would open up whatever sql file/files you have for the backup, and find the `wp_options` table section. We store our data in these two option keys: `cptui_post_types` and `cptui_taxonomies`.

Should be able to pluck those two out as needed and re-save back in via the database, without doing a complete db restore.

The post type data and whatnot shouldn't be lost as an import of our settings doesn't delete anything. We're very conscious of retaining user data whenever possible.

**Comment by cessholden** [comment]
On it. Thank you in advance if you have saved my life

**Comment by cessholden** [comment]
tw2113 thank you so so much. I love the CPT UI plugin, I have it on approximately 40 of my sites and it is one of my goto plugins. Now I'm also a fan of the support team.

For reference, your advice made me twig how to sort it out without having to use the sql files:

1. backup current state site. 
2. restore yesterdays backup
3. export cpt ui data
4. restore today's back up from step 1
5. import cpt ui data from step 3
6. celebrate

thanks so much for your prompt attention

**Comment by tw2113** [comment]
Glad we could help :)
