### ISSUE TITLE
Composer installation not working

### ISSUE THREAD

**Issue by OzzyTheGiant** [WebDevStudios/custom-post-type-ui#798]
Been trying to get composer to install the plugin into a wordpress project managed by composer. When running `composer update`, it keeps telling me there is either a typo, not available in a stable enough version or did not add custom repository. Here's part of my composer.json file:

```json
{
    "extra": {
        "installer-paths": {
            "wp-content/plugins/{$name}/": [
                "type:wordpress-plugin"
            ],
            "wp-content/themes/{$name}/": [
                "type:wordpress-theme"
            ]
        },
        "wordpress-install-dir": "wordpress",
        "repositories": [
            {
                "type": "composer",
                "url": "https://wpackagist.org"
            },
            {
                "type": "vcs",
                "url": "https://github.com/webdevstudios/custom-post-type-ui.git"
            }
        ]
    },
    "require": {
        "johnpbloch/wordpress": ">=5.6",
        "vlucas/phpdotenv": "^5.2",
        "elliotcondon/acf": "^4.4",
        "airesvsg/acf-to-rest-api": "^3.3",
        "webdevstudios/custom-post-type-ui": "1.8.2"
    }
}
```
Even tried using `minimum-stability` property as `dev` and nothing works.

**Comment by tw2113** [comment]
Looks like your version is trying to pull from https://packagist.org which we don't have CPTUI on https://packagist.org/?query=webdevstudios

However, it would be available via https://wpackagist.org via: `composer require wpackagist-plugin/custom-post-type-ui:1.8.2`

Hope this helps.

**Comment by OzzyTheGiant** [comment]
Ahh, suddenly it all makes sense. I couldn't find the plugin because I typed it in with spaces so I assumed it didn't exist there, but I had to hyphenate it: `custom-post-type-ui`. Managed to find all the other plugins this way.

Either way, still doesn't work. Same error :/

Composer version: 2.0.8

Current composer.json:
```json
{
    "require": {
        "johnpbloch/wordpress": ">=5.6",
        "vlucas/phpdotenv": "^5.2",
        "airesvsg/acf-to-rest-api": "^3.3",
        "wpackagist-plugin/advanced-custom-fields": "5.9.3",
        "wpackagist-plugin/custom-post-type-ui": "1.8.2",
        "wpackagist-plugin/wp-revisions-control": "1.3.0"
    },
    "extra": {
        "installer-paths": {
            "wp-content/plugins/{$name}/": [
                "type:wordpress-plugin"
            ],
            "wp-content/themes/{$name}/": [
                "type:wordpress-theme"
            ]
        },
        "wordpress-install-dir": "wordpress",
        "repositories": [
            {
                "type": "composer",
                "url": "https://wpackagist.org",
                "only": [
                    "wpackagist-plugin/*",
                    "wpackagist-theme/*"
                ]
            }
        ]
    }
}
```

**Comment by tw2113** [comment]
Best I maybe have at the moment is the Composer 2.x detail. My test earlier worked just fine with 1.x and I haven't reviewed recently what's changing for process between 1.x and 2.x. I'd need to do some trial/error there as well as reviewing upgrade processes.

**Comment by emilse-webdev** [comment]
Hi,
Here my findings:

1- webdevstudios/custom-post-type-ui works well with either composer 1 or composer 2

![image](https://user-images.githubusercontent.com/104102110/173593502-210012a2-4a94-41b3-a40e-08a9930fae0b.png)

My composer file for this test:
`{
    "name": "azulblanco/wp-content",
    "description": "Testing local site",
    "repositories": [
        {
            "type": "composer",
            "url": "https://wpackagist.org"
        },
        {
            "type": "vcs",
            "url": "https://github.com/WebDevStudios/custom-post-type-ui.git"
        }
    ],
    "require": {
        "perfopsone/decalog": "^3.0",
        "webdevstudios/custom-post-type-ui": "1.12.1"
    },
    "require-dev": {
        "monolog/monolog": "2.x-dev"
    },
    "license": "MTL",
    "authors": [],
    "minimum-stability": "dev",
    "config": {
        "allow-plugins": {
            "composer/installers": true
        }
    }
}`

2- Version 1.8.2 doesn't exist in the tags, 
![image](https://user-images.githubusercontent.com/104102110/173593727-69822d89-9b58-463c-9bc7-5d51a953fe4a.png)

3- CPTui is not listed in packagist, 

![image](https://user-images.githubusercontent.com/104102110/173594228-4090c0c8-b31a-4e0b-b0d3-005c5396abcc.png)

4- The package needs to be added by composer with prior requisite of adding the repositories section in composer.json and specifying the git repository of CPTui.
![image](https://user-images.githubusercontent.com/104102110/173594407-9b96201c-74da-4fca-a683-ca1947b0cab0.png)
`"repositories": [
        ...
        {
            "type": "vcs",
            "url": "https://github.com/WebDevStudios/custom-post-type-ui.git"
        }
    ],`

**Comment by tw2113** [comment]
I'm marking this as wontfix as we don't have CPTUI on packagist.org and wpackagist.org is just fine at the moment.
