### ISSUE TITLE
Add WPGraphQL support if available.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#802]
We are going to merge in code from https://github.com/wp-graphql/wp-graphql-custom-post-type-ui when WPGraphQL is installed and available, to output extra fields to add CPTUI-based post type and taxonomy support.

**Comment by tw2113** [comment]
Closed in https://github.com/WebDevStudios/custom-post-type-ui/pull/801

**Comment by tw2113** [comment]
Re-opening to re-add recent javascript meant to help prevent setting Show in GraphQL to true, but forgetting to fill in the singular and plural labels. All 3 need to be set to work.

**Comment by furqan-dev4** [comment]
WPGraphQL is broken when CPT UI 1.9.0+ is activated.
