### ISSUE TITLE
Add GraphQL fields to code exporter

### ISSUE THREAD

**Issue by jasonbahl** [WebDevStudios/custom-post-type-ui#805]
When visiting the `Tools > Get Code` Tab in Custom Post Type UI, the settings for GraphQL are not shown in the code. 

**Expectation:**

If the Post Type or Taxonomy is set to `show_in_graphql`, the `show_in_graphql`, `graphql_single_name` and `graphql_plural_name` fields should be output with the code. 

If the Post Type or Taxonomy is set to `show_in_graphql => false` or not set at all, then `show_in_graphql => 0` should be output with the code. 

----

I have a PR coming for this.

**Comment by jasonbahl** [comment]
Pr for this issue: https://github.com/WebDevStudios/custom-post-type-ui/pull/806

**Comment by tw2113** [comment]
Good catch and I'll handle this soon.

**Comment by tw2113** [comment]
Merged in via https://github.com/WebDevStudios/custom-post-type-ui/tree/release191 but am not going to release just quite yet. Going to wait to see if anything immediate comes in from elsewhere, and if not, then what else I could to for little quick fixes to beef up a 1.9.1 release a little more.

Thanks again Jason.
