### ISSUE TITLE
Custom Post issue with WP GraphQL

### ISSUE THREAD

**Issue by atexzonate** [WebDevStudios/custom-post-type-ui#813]
In my custom post type, when I set "show in graphQL" to "true" and also singular and plural name.

I get an error in GraphiQL IDE and also in the endpoint (path) for the GraphQL API on the site.
![image](https://user-images.githubusercontent.com/20685411/122284005-7ef07600-cf30-11eb-8904-586201b7c2ba.png)
![image](https://user-images.githubusercontent.com/20685411/122284033-8748b100-cf30-11eb-8187-e99feb0b95b3.png)

If the go back to my custom post type and unset "show in graphQL" to "false" the error go away.
I have tried everything possible. Can someone please help me out

Plugin Stack:
WP GraphQL version 1.4.2
Custom Post Type UI version 1.9.1
Advanced Custom Fields PRO version 5.9.5
WPGraphQL for Advanced Custom Fields version 0.5.2

**Comment by tw2113** [comment]
Your hosting accounts error log is going to be the best thing to check here for more information about existing errors. For whatever reason, when trying to save and everything, an "Internal Server Error 500" error is occurring.

**Comment by atexzonate** [comment]
Error log shows

#0 test.app.rccgaustraliapacific.org/wp-includes/class-wp-hook.php(292): WPGraphQL\Registry\TypeRegistry->init_type_registry(Object(WPGraphQL\Registry\TypeRegistry))

#1 test.app.rccgaustraliapacific.org/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)

#2 test.app.rccgaustraliapacific.org/wp-includes/plugin.php(484): WP_Hook->do_action(Array)

#3 test.app.rccgaustraliapacific.org/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php(198): do_action('init_graphql_ty...', Object(WPGraphQL\Registry\TypeRegistry))

#4 test.app.rccgau in /home/feastofesther18/public_html/test.app.rccgaustraliapacific.org/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php on line 411


I hope this information can help

**Comment by tw2113** [comment]
Sadly not looking like it. This is looking more like a stacktrace for some code that executed at some point, but nothing about any experienced errors that could cause an Internal Server Error. So I don't know what to suggest here other than maybe turning on the `WP_DEBUG_DISPLAY` constant in your wp-config.php file temporarily and trying to recreate the issue. Hopefully the error perhaps shows through to the browser and we could get information that way.

**Comment by atexzonate** [comment]
Thanks, guys for your help and support. After displaying the Log with WP_DEBUG_DISPLAY in my wp.config file.

I found out that GraphQL Single Name and GraphQL Plural Name * can not be the same.
