### ISSUE TITLE
Template for custom post type not working

### ISSUE THREAD

**Issue by argirostar** [WebDevStudios/custom-post-type-ui#816]
Hi,
I am working on a project with Elementor Pro. I have created two custom post types and a single post template for each of them. The first one (Post01.jpg) works fine (Template-showing-01.jpg ).

The second one though (Post02.jpg) when you click on a post it seems like it does not recognize the template and nothing is showing. (Template-not-showing-02.jpg).

I have tried to make  new custom types and templates but the same problem continues to be. When clicking on a post the template with the content does not appear even though in the breadcrumbs it seems like it is working.

Could please help me as soon as possible because I have to deliver the site really soon.

Thank you in advance.

This is the site where the problem is: https://elearning-website.dotsyntax.gr/

![Template-not-showing-02](https://user-images.githubusercontent.com/87847596/126743670-6d816e39-7340-4dd1-8894-4af637cf3b7d.jpg)
![Post02](https://user-images.githubusercontent.com/87847596/126743673-1c54437b-929b-4ff0-b893-d0a37b9260d0.jpg)
![Template-showing-01](https://user-images.githubusercontent.com/87847596/126743676-7baeaa82-0e9f-46d2-a5a5-6e91ff8155bb.jpg)
![Post01](https://user-images.githubusercontent.com/87847596/126743678-602110e1-ec8e-4910-9b34-ac739a091904.jpg)

**Comment by tw2113** [comment]
CPTUI doesn't really have any hand in template loading and which get used. The biggest thing to keep in mind is that at least in terms of the native WordPress template hierarchy, as long as you name them `single-$post_type_slug.php` WordPress would pick them up. If your post type is "movies", then it'd be `single-movies.php`. If it's "tv_shows", it'd be `single-tv_shows.php`

However, you're also working with Elementor Pro, and they may be doing things on their own with the templates and how things load and behave, however their support is going to be the better source of help than us. We don't have any specific Elementor integrations with our plugin.

**Comment by argirostar** [comment]
Thank you very much for your reply.

**Comment by tw2113** [comment]
Welcome.
