### ISSUE TITLE
Adding Taxonomies Screen Options to the Admin List View of Custom Posts

### ISSUE THREAD

**Issue by jboveri** [WebDevStudios/custom-post-type-ui#839]
Love the plugin! The ability to look, in the WordPress back end, at the list view of all my custom posts, and be able to see which taxonomies each has would be extremely useful. Could you add Screen Options to be able to see those in the table (much like you can see Author, Categories, Tags, etc. in standard list view of regular WordPress posts)?

**Comment by tw2113** [comment]
The "show admin column" option should handle that already, once set to true. It'll add that taxonomy column to your list table for the post type, and show which terms are currently used, if any, for each post.

**Comment by jboveri** [comment]
Oh, perfect! Thanks so much! You rock!
