### ISSUE TITLE
supports param should be false if no fields

### ISSUE THREAD

**Issue by Youdaman** [WebDevStudios/custom-post-type-ui#84]
If the users unchecks all of the boxes for the "supports" param, instead of an empty array, it should be set to false -- an empty array shows the default title/editor fields.

As per http://codex.wordpress.org/Function_Reference/register_post_type

"As of 3.5, boolean false can be passed as value instead of an array to prevent default (title and editor) behavior."

**Comment by tw2113** [comment]
This should be good at this point. Added a new checkbox for "None" which, when present in the saved option, will set the supports param to false, regardless of any others checked. As long as "none" is not checked, either an empty array that gives defaults, or the specified supports will be added.
