### ISSUE TITLE
Error during import --- Uncaught TypeError: in_array():  Argument #2 ($haystack) must be of type array, null given in /wp-content/plugins/custom-post-type-ui/inc/utility.php:941

### ISSUE THREAD

**Issue by lquidfire** [WebDevStudios/custom-post-type-ui#840]
Hi there!

Thanks very much for this plugin!

I installed the CPT UI on my staging site, configured it all to my liking (1 taxonomy). All was well.

Then I installed the plugin on my prod site, and tried to import the taxonomy from the staging site (see attachment for the export)
[leatimes-export.txt](https://github.com/WebDevStudios/custom-post-type-ui/files/8086274/leatimes-export.txt)
. However, it threw a fatal error at me. Please see below.

```
An error of type E_ERROR was caused in line 941 of the file [redacted]/wp-content/plugins/custom-post-type-ui/inc/utility.php.

Error message: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in [redacted]/wp-content/plugins/custom-post-type-ui/inc/utility.php:941

Stack trace: #0 [redacted]/wp-content/plugins/custom-post-type-ui/inc/utility.php(941): in_array()
#1 [redacted]/wp-includes/class-wp-hook.php(303): cptui_published_post_format_fix()
#2 [redacted]/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#3 [redacted]/wp-includes/plugin.php(470): WP_Hook->do_action()
#4 [redacted]/wp-content/plugins/custom-post-type-ui/custom-post-type-ui.php(325): do_action()
#5 [redacted]/wp-includes/class-wp-hook.php(303): cptui_create_custom_post_types()
#6 [redacted]/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#7 [redacted]/wp-includes/plugin.php(470): WP_Hook->do_action()
#8 [redacted]/wp-settings.php(578): do_action()
#9 [redacted]/wp-config.php(82): require_once('/home/6154aa92c...')
#10 [redacted]/wp-load.php(50): require_once('/home/6154aa92c...')
#11 [redacted]/wp-login.php(12): require('/home/6154aa92c...')
#12 {main} thrown
```

Also: I cannot activate the plugin now without it throwing an error. Where can I find the data that I need to delete so I can use the plugin again?

**Comment by tw2113** [comment]
Is it an error that's debilitating your ability to use the admin/site in general? or is it all usable still, except this gets thrown at the moment?

The error is coming from a spot that is regarding saved post types, apparently somehow the "supports" section doesn't have at least an empty array going on for one of the types. In this case, it's just null.

By any chance did you uncheck all of the items in the "supports" section and just leave them blank?

Really quick fix, that I'm more than willing to add to the plugin permanently is going to be changing line 941 from this file

https://github.com/WebDevStudios/custom-post-type-ui/blob/master/inc/utility.php#L941

from:

```
if ( in_array( 'post-formats', $type['supports'], true ) ) {
```
to
```
if ( is_array( $type['supports'] ) && in_array( 'post-formats', $type['supports'], true ) ) {
```

Hopefully that change would get you back up to full speed, for whatever errors you're encountering.

**Comment by tw2113** [comment]
Hmm. Noted on the debilitating part.

Good catch on the imported into the wrong spot part. I still want to guard against `foreach` errors so I will get that handled in a future release.

Finding a way to warn against importing in the wrong spot, feels like it'd be a tall challenge to figure out how to determine. Closest I can think of off the top of my head is checking for post type or taxonomy specific properties in the JSON being imported, and return early if things don't match up. However, I'm not sure how elegant that could be done either.

At least at the moment, I'm definitely going to better guard against PHP errors, and try to recall the note about which spot was imported into, in support requests where importing is mentioned.

Closing this task in terms of open issues, and will handle the PHP fixes in https://github.com/WebDevStudios/custom-post-type-ui/issues/841

Thanks for the feedback @lquidfire
