### ISSUE TITLE
Escape HTML special chars

### ISSUE THREAD

**Issue by Taolana** [WebDevStudios/custom-post-type-ui#843]
https://github.com/WebDevStudios/custom-post-type-ui/blob/c010508dd89d87fbaaf276a9591174ea4478ba6d/custom-post-type-ui.php#L410
When making a single quote to the sub menu of a custom post type it shows a html entity of a quote in the admin panel on several positions. There is my suggestion:

`$labels[ $key ]     = htmlspecialchars_decode(sprintf( $preserved_labels['post_types'][ $singular_or_plural ][ $key ], $label_plurality ));`

**Comment by tw2113** [comment]
Hmm.

Not sure how I want to potentially approach this. I know I set up a bunch of labels that were `Movie's` and it resulted in `Movie&amp;#39;s` which have some double encoding. Not sure I get enough requests/forum threads to try and make this a working thing for everyone, and push it out as part of a plugin update.

That said, I have done up the following snippet that would convert all of the entities back to a single quote. It hooks in to our filter that runs right before we do the actual registering.

```
add_filter( 'cptui_pre_register_post_type', function( $args, $post_type_slug, $post_type_array ) {
	// First we convert "&amp;" back to "&"
	$args['labels'] = array_map( 'htmlspecialchars_decode', $args['labels'] );
	// Then we convert "&#39;" back to "'"
	$args['labels'] = array_map( function( $value ) {
		return html_entity_decode( $value, ENT_QUOTES, 'utf-8' );
	}, $args['labels'] );
 	return $args;
}, 10, 3 );
```

You can use the `$post_type_slug` to conditionally run if needed. As is above, it'd run on all of the post types registered by  CPTUI.

**Comment by Taolana** [comment]
Ah, okay, thanks for your reply. 
Actually it works.
