### ISSUE TITLE
Fatal error: Uncaught TypeError: array_key_exists(): /inc/utility.php:878

### ISSUE THREAD

**Issue by lquidfire** [WebDevStudios/custom-post-type-ui#847]
Hi Michael!

(Also reported on wordpress.org. Link [here](https://wordpress.org/support/topic/fatal-error-uncaught-typeerror-array_key_exists-inc-utility-php878/).)

I am getting a PHP Fatal error on my site. I am not aware of having changed anything on the site since yesterday…

The stack trace:

```
#0 [redacted]/public_html/wp-content/plugins/custom-post-type-ui/inc/post-types.php(2135): cptui_get_cptui_post_type_object()

#1 [redacted]/public_html/wp-includes/class-wp-hook.php(307): cptui_custom_enter_title_here()

#2 [redacted]/public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters()

#3 [redacted]/public_html/wp-admin/includes/dashboard.php(569): apply_filters()

#4 [redacted]/public_html/wp-admin/includes/template.php(1395): wp_dashboard_quick_press()

#5 [redacted]/public_html/wp-admin/includes/dashboard.php(268): do_meta_boxes()

#6 [redacted]/public_html/wp-admin/index.php(203): wp_dashboard()

#7 {main}

thrown in [redacted]/public_html/wp-content/plugins/custom-post-type-ui/inc/utility.php on line 878
```
I have one CPT taxonomy on the website only.

Your help is much appreciated.

Kind regards,

**Comment by lquidfire** [comment]
Apologies, the latest update appears to have addresses the issue and it is sorted. Since I had trouble logging in to the back-end, I was unaware of the update being available.

**Comment by tw2113** [comment]
No worries,
