### ISSUE TITLE
Missed variable change for `can_export` in registration process

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#848]
Fixed by #845

**Comment by claborier** [comment]
Hi ! 

Using the `CPT Ui > Tools > Get Code` feature, I got this error right in the middle on the generated PHP : 
`<b>Notice</b>:  Undefined index: can_export in <b>/var/www/html/web/app/plugins/custom-post-type-ui/inc/tools.php</b> on line <b>580</b><br />`

Is it in any way related ? Or should I post a new issue ?

It happens for custom post type registered before 'can_export' appears.

Thanks

**Comment by tw2113** [comment]
Related yet not. Going in and saving your post types again, without changing anything, should clear the error out, but we should also consider doing some extra `empty()` checks as well on our end as well, as more users get upgraded.
