### ISSUE TITLE
featured image is not being shown

### ISSUE THREAD

**Issue by BelieveInBunny** [WebDevStudios/custom-post-type-ui#857]
Hi,
featured image is not being shown on the website, when I turn off custom post type ui. it works fine

Thank you

**Comment by tw2113** [comment]
Are you referring to the posts in a specific post type? or all posts regardless of post type? 

What about if/when you remove your CPTUI-based registered post types but leave the plugin active? You can test this out in the CPTUI > Tools menu and copy/paste the content on the right to somewhere safe, and then import `{""}` to clear out JUST THE SETTINGS. We don't delete the content in your content types, just the settings for CPTUI. The copy/paste mentioned above is so we can re-import all of your post types afterwards. Never hesitate to take a quick backup regardless, just in case.

**Comment by tw2113** [comment]
Any changes or news here @BelieveInBunny ?

**Comment by benramsay** [comment]
> Are you referring to the posts in a specific post type? or all posts regardless of post type?
> 
> What about if/when you remove your CPTUI-based registered post types but leave the plugin active? You can test this out in the CPTUI > Tools menu and copy/paste the content on the right to somewhere safe, and then import `{""}` to clear out JUST THE SETTINGS. We don't delete the content in your content types, just the settings for CPTUI. The copy/paste mentioned above is so we can re-import all of your post types afterwards. Never hesitate to take a quick backup regardless, just in case.

Hi @tw2113
I tried this and does not work :(
I have the same problem on all posts regardless of post type? The "featured image" is checked but there is no image box on the post type side

**Comment by tw2113** [comment]
@benramsay What about the Screen options tab in the upper right (assuming classic editor), potential that it's not visually shown at the moment while still having overall support registered. For block editor, I believe the toggle for some of the registered panels are in a settings section in the editor screen.
