### ISSUE TITLE
Hooks for everything

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#86]
How can we make this extensible for those who want to.

**Comment by tw2113** [comment]
Added a bunch of new hooks including WP-standard hooks documentation tonight.

**Comment by JulienMelissas** [comment]
:+1:

**Comment by tw2113** [comment]
@JulienMelissas check the dev branch commit log for all of the new ones :D I may be a bit familiar with BuddyPress' hooks and mimicking them a bit.

**Comment by JulienMelissas** [comment]
@tw2113, good stuff man, thanks for all the hard work!

**Comment by tw2113** [comment]
Since you're replying @JulienMelissas would you be willing to beta test for me? I'd appreciate it a lot, especially if you're upgrading a site that has been using it already and has settings saved and posts created. I need to make sure it doesn't break anything.

**Comment by JulienMelissas** [comment]
@tw2113, honestly I can't think of a site I'm using it on actively ATM, but let me dig through some stuff and see what I've got. I'll at least be happy to test it on a new project coming up in the next week or so!

**Comment by tw2113** [comment]
I'm going to be needing fresh users testing as well, so either way works out :)

**Comment by JulienMelissas** [comment]
Cool I'll let you know when I'm able to dig in :smile:
