### ISSUE TITLE
Setting Hierarchical = true, adds "Parent Page: <parent>" but HOW do I set the parent?

### ISSUE THREAD

**Issue by blaasvaer** [WebDevStudios/custom-post-type-ui#860]
I'm having a really really hard time figuring out from the interface itself (and googlin' the crap out of it) how to actually make things "Hierarchical". If I set Hierarchical to true for a post type and check the Support: "Page "Attributes", it adds "Parent Page: <parent>" to the list in the admin, and a Page Attribute to the post itselft ... but it's just and empty intput field?

How can I actually set the parent for the post?

**Comment by tw2113** [comment]
Do you have more than 1 post **published** ? You can't set a post to be a child of a draft post. Need at least 2 published to set up a hierarchy.

**Comment by tw2113** [comment]
Are you getting any Javascript errors in your browser console? In terms of published posts, that looks like it's not the issue in the end.

We don't have any code that interacts or changes behavior of the editor in this place, so while something is definitely going on, it's hard to say what.

**Comment by blaasvaer** [comment]
Nope, no funky stuff in the console ... just this weird behavior.

**Comment by blaasvaer** [comment]
{"vehicles":{"name":"vehicles","label":"Vehicles","singular_label":"Vehicle","description":"","public":"true","publicly_queryable":"true","show_ui":"true","show_in_nav_menus":"true","delete_with_user":"false","show_in_rest":"true","rest_base":"","rest_controller_class":"","has_archive":"false","has_archive_string":"","exclude_from_search":"false","capability_type":"post","hierarchical":"false","can_export":"false","rewrite":"true","rewrite_slug":"","rewrite_withfront":"true","query_var":"true","query_var_slug":"","menu_position":"","show_in_menu":"true","show_in_menu_string":"","menu_icon":"","supports":["title","editor","thumbnail","custom-fields"],"taxonomies":["category","post_tag"],"labels":{"menu_name":"","all_items":"","add_new":"","add_new_item":"","edit_item":"","new_item":"","view_item":"","view_items":"","search_items":"","not_found":"","not_found_in_trash":"","parent_item_colon":"","featured_image":"","set_featured_image":"","remove_featured_image":"","use_featured_image":"","archives":"","insert_into_item":"","uploaded_to_this_item":"","filter_items_list":"","items_list_navigation":"","items_list":"","attributes":"","name_admin_bar":"","item_published":"","item_published_privately":"","item_reverted_to_draft":"","item_scheduled":"","item_updated":""},"custom_supports":"","enter_title_here":""},"carbrands":{"name":"carbrands","label":"Car Brands","singular_label":"Car Brand","description":"","public":"true","publicly_queryable":"true","show_ui":"true","show_in_nav_menus":"true","delete_with_user":"false","show_in_rest":"true","rest_base":"","rest_controller_class":"","has_archive":"false","has_archive_string":"","exclude_from_search":"false","capability_type":"post","hierarchical":"true","can_export":"false","rewrite":"true","rewrite_slug":"","rewrite_withfront":"true","query_var":"true","query_var_slug":"","menu_position":"","show_in_menu":"true","show_in_menu_string":"","menu_icon":"","supports":["title","editor","thumbnail","custom-fields","page-attributes"],"taxonomies":["category","post_tag"],"labels":{"menu_name":"","all_items":"","add_new":"","add_new_item":"","edit_item":"","new_item":"","view_item":"","view_items":"","search_items":"","not_found":"","not_found_in_trash":"","parent_item_colon":"","featured_image":"","set_featured_image":"","remove_featured_image":"","use_featured_image":"","archives":"","insert_into_item":"","uploaded_to_this_item":"","filter_items_list":"","items_list_navigation":"","items_list":"","attributes":"","name_admin_bar":"","item_published":"","item_published_privately":"","item_reverted_to_draft":"","item_scheduled":"","item_updated":""},"custom_supports":"","enter_title_here":""},"carbrandmodels":{"name":"carbrandmodels","label":"Car Brand Models","singular_label":"Car Brand Model","description":"","public":"true","publicly_queryable":"true","show_ui":"true","show_in_nav_menus":"true","delete_with_user":"false","show_in_rest":"true","rest_base":"","rest_controller_class":"","has_archive":"false","has_archive_string":"","exclude_from_search":"false","capability_type":"post","hierarchical":"false","can_export":"false","rewrite":"true","rewrite_slug":"","rewrite_withfront":"true","query_var":"true","query_var_slug":"","menu_position":"","show_in_menu":"true","show_in_menu_string":"","menu_icon":"","supports":["title","editor","thumbnail","custom-fields"],"taxonomies":["category","post_tag"],"labels":{"menu_name":"","all_items":"","add_new":"","add_new_item":"","edit_item":"","new_item":"","view_item":"","view_items":"","search_items":"","not_found":"","not_found_in_trash":"","parent_item_colon":"","featured_image":"","set_featured_image":"","remove_featured_image":"","use_featured_image":"","archives":"","insert_into_item":"","uploaded_to_this_item":"","filter_items_list":"","items_list_navigation":"","items_list":"","attributes":"","name_admin_bar":"","item_published":"","item_published_privately":"","item_reverted_to_draft":"","item_scheduled":"","item_updated":""},"custom_supports":"","enter_title_here":""}}

**Comment by blaasvaer** [comment]
It works for the other custom post type ... for whatever reason. But I think I'm also trying to do something that the plugin is not built for. I have set the parent id of ONE custom post type  to the ID of the parent for ANOTHER custom post type (manually running a custom js). And I wass 'somehow' expecting this to work some magic. I think you can't relate stuff like that. Basically I want to have one custom post type act as parent for another custom post type. And I seriously have a hard time figuring out why this is so cumbersom in Wordpress. I would expect something like that to be damn easy. Well, ... sigh.

**Comment by tw2113** [comment]
In what way are you trying to modify things to have that attempted cross-post type hierarchy? For example do you have custom code elsewhere trying to do that?

I've never seen UI provided by WP core to have that type of relationships, even though the "post_parent" column in the database is just a post ID.

I know with CPTUI, we don't attempt anything like that.

I also know that https://wordpress.org/plugins/posts-to-posts/ still technically exists, and isn't 100% horribly outdated, even though it's been 2 years for an update. HOWEVER that may not facilitate the parent/child details.

I'm fairly confident that part of WHY WP core doesn't facilitate this is because of permalinks.

https://www.mysite.com/post-type-slug/parent-post-type-post/child-post-type-post/

The post type is derived from the first part after the `.com` but there's no great way to consistently and reliably provide the post type for the "child post type post" portion.

**Comment by tw2113** [comment]
Any news or changes here?

**Comment by blaasvaer** [comment]
No, I think I’m going for another hack of sorts, thanks.
