### ISSUE TITLE
PHPCS Cleanup 2022

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/custom-post-type-ui#870]
Current report as of my issue filing: https://gist.github.com/tw2113/6cbe9384993ae1a3fcafa8dea86e6a5d

Branch: phpcs-cleanup

**Comment by alokstha1** [comment]
Getting an issue in VSCode **phpcs: Referenced sniff "WordPress-Extra" does not exist**

**Comment by tw2113** [comment]
Can you re-confirm which branch you're working from and any of the commands run, if any?

**Comment by alokstha1** [comment]
I'm working on `phpcs-cleanup` branch. The installed coding standards are PEAR, Zend, PSR2, MySource, Squiz, PSR1, PSR12, WordPress, WordPress-Extra, WordPress-Docs and WordPress-Core. And when I try to save or make changes, I get `phpcs: Referenced sniff "PHPCompatibilityWP" does not exist` error in VSCode.

**Comment by tw2113** [comment]
Closing as it has been merged already.
