### ISSUE TITLE
Help - How to track / revert changes made to CPT Settings

### ISSUE THREAD

**Issue by melaniejaane** [WebDevStudios/custom-post-type-ui#881]
Is there a way to track changes or see revisions / history of updates made to the CPT UI settings? A contractor has accidentally changed multiple CPT settings, so trying to figure out exactly what and when these changes were made. Is there a way to restore previous versions of our CPT set up like you can do previous revisions with posts? 

@tw2113 I saw you mentioned similar features in a few enhancement threads in 2016, but couldn't see if any resolutions had been made?

Thanks

**Comment by tw2113** [comment]
Chances are, you're referring to https://github.com/WebDevStudios/custom-post-type-ui/issues/540 but that's not anything we've thus far attempted. So the best/easiest way to recover settings would be to either find a backup that's old enough to for sure be before this contractor made any changes and fetch from there, or if there's a staging copy of the site that they haven't touched, you could compare to that. Or just check how they're behaving now, vs how they are expected to be behaving, and work out what settings need updated from that. Below I have some examples of this last item, off the top of my head.

For example were you able to create parent/child relationships but can't any more, that'd be the "hierarchical" setting needing to be true. Are you no longer seeing UI for specific taxonomies, make sure to check on which are associated. Did permalinks break in some way, double check the rewrite slug value. Is it no longer working with the Block Editor? Make sure "Show In Rest" is set back to true.

**Comment by tw2113** [comment]
I'm closing this as not an issue with the plugin itself, but feel free to continue the discussion if/as needed @melaniejaane
