### ISSUE TITLE
Remove these ads? link is broken

### ISSUE THREAD

**Issue by Zodiac1978** [WebDevStudios/custom-post-type-ui#886]
The link to https://pluginize.com/plugins/custom-post-type-ui-extended/ref/pluginizeaff/?campaign=cptui-sidebar-remove is broken for me:

https://github.com/WebDevStudios/custom-post-type-ui/blob/7e65f7db64ec6c1ffb6c9512fd88cbe8449f1743/inc/utility.php#L363

**Comment by tw2113** [comment]
where does it drop you on to? Just the base pluginize.com domain?

**Comment by Zodiac1978** [comment]
404
![Screenshot 2022-09-08 at 16-23-00 Page not found - Pluginize](https://user-images.githubusercontent.com/870475/189147475-745cb4fc-2bff-4e39-8a7f-098e8fbb2bda.png)

**Comment by tw2113** [comment]
Interesting, will need to look into that because I didn't end up at a 404. The URL parameters are just meant to see where traffic comes from, so visiting the shop will be the next step if you're wanting to get rid of the ads and more hopefully the features of Extended are appealing :D

**Comment by tw2113** [comment]
For future me, this is because AffiliateWP is deactivated. Waiting on feedback for how to approach.

**Comment by tw2113** [comment]
Fixed in 3682b2b
