### ISSUE TITLE
Errors displayed when using  Custom Post Type block in WP 6.0.2

### ISSUE THREAD

**Issue by davidvc** [WebDevStudios/custom-post-type-ui#893]
When we use the Custom Post Types block to create a block from a custom post, we get this error when we try to render the page: 

" Function rest_validate_value_from_schema was called incorrectly. The "type" schema keyword for term can only be one of the built-in types: array, object, string, number, integer, boolean, and null"

I printed out the call stack in the debug log, and this error is hit inside Wordpress, where it is validating a type specification against the list of valid types. The type coming in is "int" and WP only allows "integer" or "number."  

```
    [1] => Array
        (
            [file] => /srv/www/siddhayoga.org/releases/20220924201623/web/wp/wp-includes/functions.php
            [line] => 5831
            [function] => trigger_error
            [args] => Array
                (
                    [0] => Function rest_validate_value_from_schema was called <strong>incorrectly</strong>. The "type" schema keyword for term can only be one of the built-in types: array, object, string, number, integer, boolean, and null. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.)
                    [1] => 1024
                )

        )
```

I'll provide the full call stack as a comment

**Comment by davidvc** [comment]
Here is a gist for the full debug output: https://gist.github.com/davidvc/340992116c2b7f16e49e274b043372c9

**Comment by tw2113** [comment]
Not managing to figure out who the author is based on details from the log, but this feels like something that needs to be brought up with whoever authored the plugin providing this block.

If you're using CPTUI-Extended, then that's definitely us, but I'm not seeing any reference to that or CPTUI itself in the logs. So at least until shown otherwise, I think our role in this is just the post type registry.

**Comment by davidvc** [comment]
Oh, thanks, I misunderstood how this works. We are using "Custom Post Types Widget Blocks" by thingsym. I'll go bug them, and will close this issue.

**Comment by tw2113** [comment]
No worries, hopefully they can get things figured out for you.
