### ISSUE TITLE
French characters not recognized

### ISSUE THREAD

**Issue by yafortier** [WebDevStudios/custom-post-type-ui#911]
Since the latest update, all my CPT French translations transform into other characters : 

Ex: Catégories de formation becomes Cat&eacute;gories de formation. 

<img width="1161" alt="Screenshot 2022-12-16 at 8 14 14 AM" src="https://user-images.githubusercontent.com/10333270/208106270-2e58ed7b-0ea3-4ba8-a53d-8791cd34ca0c.png">

**Comment by tw2113** [comment]
Hmm, I know we switched from `FILTER_SANITIZE_STRING` sanitization to `FILTER_SANITIZE_FULL_SPECIAL_CHARS` but that should only be on saving, not on general display. This was done in relation to the former being deprecated by PHP version 8.1 and above.

To confirm, is this happening only after you save the content type?

**Comment by yafortier** [comment]
Yes, exactly. All the previously made content is unaffected but when I re-save old content it changes the characters.

**Comment by tw2113** [comment]
@yafortier Can you try this version out? 

[custom-post-type-ui.zip](https://github.com/WebDevStudios/custom-post-type-ui/files/10248409/custom-post-type-ui.zip)

**Comment by tw2113** [comment]
For me: bug/911-special-chars-issue

**Comment by yafortier** [comment]
Tried it, fixed the issue. :-)

**Comment by tw2113** [comment]
Awesome, pending potentially a couple more who reported similar issues, before I likely push out the fix.

**Comment by tw2113** [comment]
And handled. Thanks again.
