### ISSUE TITLE
Plugin conflicting with pretty link permalink structure

### ISSUE THREAD

**Issue by sipayton** [WebDevStudios/custom-post-type-ui#941]
I have a site that was created by a developer using your plug-in. At some point, CPTUI plugin started having issues with the pretty link permalink structure. In the WP admin, it is not allowing me to update or publish one of my post types. I get "Updating failed. No route was found matching the URL and request method." I checked with Bluehost and they said when they changed to the default wordpress permalink structure the updates appeared to be able to be saved. How can I get it to work with the pretty permalink structure? I am not a developer...so I don't know php, etc.

**Comment by tw2113** [comment]
Hi Sarah,

Hard to say what may be going on here as that error could be coming from any other plugin that's active at the moment as well. Without being able to access and see the editor screen, impossible for me to say. That's also not an error that we provide via our plugin.

That said, does the issue return when you re-set the permalinks to the previous version? Also to make sure I'm following correctly, this is happening when you're trying to save a post in one or many of the post types you've registered?

**Comment by sipayton** [comment]
Hi.
Thanks for the quick reply. Yes, the error returns when the permalink structure is changed back to the pretty link structure. When the permalink is the default structure it works, but I need to use the pretty link structure since I have so many links with that structure already that would break.

Bluehost's migration team went through all the plugins turning them on and off. That is how they identified the conflict with your plugin and the permalink structure.
As you can see from the image below, when I go into my 'state trainings' post section that the developer created, I try to make a new post, but It will not let me save or publish it, so it will just leave an "auto draft". If I try to go into an existing post, I cannot update it.

And unfortunately I no longer have access to that developer.

***@***.***


Sarah I. Payton, MBA
National Center for Pyramid Model Innovations
University of South Florida
***@***.******@***.***>| 813-974-7502

***@***.***

**Comment by sipayton** [comment]
screenshot 1: (https://github.com/WebDevStudios/custom-post-type-ui/assets/42245855/2325ea72-17c0-481e-b329-103e763f5054)

screenshot 2: (https://github.com/WebDevStudios/custom-post-type-ui/assets/42245855/eb94fb52-26ec-4c2d-a6ae-0333f7d3b785)

**Comment by tw2113** [comment]
Responded to the private email you sent WebDevStudios as well, as there's some questions that don't need to be done publicly on GitHub.

**Comment by tw2113** [comment]
Custom "REST base" ended up being the source of the issue and once that was removed, so that the post type defaulted to the post type slug, things worked as expected.
