### ISSUE TITLE
Warning when taxonomy has no description

### ISSUE THREAD

**Issue by anmonite** [WebDevStudios/custom-post-type-ui#976]
In version 1.17.1 using PHP 8.3.12 environment, I caught an PHP warning as follows.

"PHP message: PHP Warning:  Undefined array key "description" in /home/kusanagi/*******/DocumentRoot/wp-content/plugins/custom-post-type-ui/inc/tools.php on line 442; PHP message: PHP Deprecated:  html_entity_decode(): Passing null to parameter #1 ($string) of type string is deprecated in /home/kusanagi/*******/DocumentRoot/wp-content/plugins/custom-post-type-ui/inc/tools.php on line 442"

custom-post-type-ui/inc/tools.php:

```
439                     $cptui_taxonomies = cptui_get_taxonomy_data();
440                     if ( ! empty( $cptui_taxonomies ) ) {
441                         foreach ( $cptui_taxonomies as $tax => $values ) {
442                             $cptui_taxonomies[ $tax ]['description'] = wp_slash( html_entity_decode( $values['description'] ) );
443                         }
```

It seems that there is a case that a taxonomy has no description data.
When "$values['description']" is empty, it may cause above warning.

I think it needs to be fixed to check "$values['description']" is empty or not before using as parameter like as below.

```
439                     $cptui_taxonomies = cptui_get_taxonomy_data();
440                     if ( ! empty( $cptui_taxonomies ) ) {
441                         foreach ( $cptui_taxonomies as $tax => $values ) {
442                             if ( !empty($values['description']) ) {
443                                 $cptui_taxonomies[ $tax ]['description'] = wp_slash( html_entity_decode( $values['description'] ) );
444                             }
445                         }
```

Please check.
Thanks.

**Comment by tw2113** [comment]
I can definitely see this as a possible case, and am willing to get a solution for this put in place.

**Comment by tw2113** [comment]
Will be a part of a 1.17.2 release, but not quite set on when that will go out. 

See https://github.com/WebDevStudios/custom-post-type-ui/commit/7943999c40761ee0be7feb15f8d14683493abbe4

Marking this issue as closed, but feel free to comment if/as needed.

**Comment by anmonite** [comment]
Thanks for your rapidly support !
